/*  File:  gen_util.h  */

 int if_arerror_exit( ARControlStruct *controlPtr, char *header,
 int returnCode, ARStatusList *statusPtr );
void if_nterror_exit();
void PrintARDataType();

void PrintARBoolean();
void PrintInt();
void PrintLong();
void PrintReal();
void PrintChar();
void PrintARTimestamp();
void PrintAREntryIdList();
void PrintARInternalId();
void PrintARInternalIdList();
void PrintARNameList();
void PrintARServerNameList();
void PrintARStatusStruct();
void PrintARStatusList();
void PrintNTStatusStruct();
void PrintNTStatusList();

void PrintARByteList();
void PrintARControlStruct();
void PrintARCoordList();
void PrintARValueStruct();
void PrintARValueList();
void PrintARValueListList();
void PrintAREntryListFieldStruct();
void PrintAREntryListFieldList();
void PrintARSortList();
void PrintAREntryListStruct();
void PrintAREntryListList();
void PrintARFieldValueStruct();
void PrintARFieldValueList();
void PrintARFieldValueListList();
void PrintAREntryListFieldValueList();
void PrintARFieldValueOrArithStruct();
void PrintARArithOpStruct();
void PrintARRelOpStruct();
void PrintARQualifierStruct();
void PrintARIndexStruct();
void PrintARIndexList();
void PrintARCompoundSchema();
void PrintARPropList();
void PrintARDisplayInstanceList();
void PrintARAssignFieldStruct();
void PrintARAssignSQLStruct();
void PrintARAssignStruct();
void PrintARFieldAssignList();
void PrintARArithOpAssignStruct();
void PrintARFunctionAssignStruct();
void PrintARFieldAssignStruct();
void PrintARFieldCharacteristics();
void PrintARDDEStruct();
void PrintARAutomationStruct();
void PrintARCOMValueStruct();
void PrintARCOMMethodList();
void PrintARCOMMethodStruct();
void PrintARCOMMethodParmList();
void PrintARCOMMethodParmStruct();
void PrintARFilterActionNotify();
void PrintARPushFieldsList();
void PrintARSQLStruct();
void PrintARFilterActionStruct();
void PrintARFilterActionList();
void PrintARActiveLinkMacroStruct();
void PrintARActiveLinkActionStruct();
void PrintARActiveLinkActionList();
void PrintARPermissionStruct();
void PrintARPermissionList();
void PrintARGroupInfoStruct();
void PrintARGroupInfoList();
void PrintARUserLicenseStruct();
void PrintARUserLicenseList();
void PrintARUserInfoStruct();
void PrintARUserInfoList();
void PrintARIntegerLimitsStruct();
void PrintARRealLimitsStruct();
void PrintARCharLimitsStruct();
void PrintARFieldLimitStruct();
void PrintARCharMenuItemStruct();
void PrintARCharMenuQueryStruct();
void PrintARCharMenuStruct();
void PrintARCharMenuList();
void PrintARStructItemStruct();
void PrintARStructItemList();
void PrintARServerInfoStruct();
void PrintARServerInfoStruct2();
void PrintARServerInfoList();
void PrintARServerInfoList2();
void PrintARServerInfoRequestList();
void PrintARStatisticsResultStruct();
void PrintARStatisticsResultList();
void PrintARStatusHistoryList();
void PrintARFullTextInfoList();
void PrintARDiaryList();
void PrintARFieldMapping();
void PrintARBooleanList();
void PrintARContainerInfo(char *, ARContainerInfo *);
void PrintARContainerInfoList(char *, char *, ARContainerInfoList *);
void PrintARContainerOwnerObj(ARContainerOwnerObj *);
void PrintARReferenceList(ARReferenceList *);
void PrintARReferenceStruct(char *, ARReferenceStruct *);
void PrintARExtReferenceStruct(char *, ARExtReferenceStruct *);

void PrintReturnCode();
int arLoadARArithStruct();
