#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile a3a$  $Revision$

# rsh rip1 "/usr/local/bin/traceMode 1"

$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon1 $ENSTORE_DIR/test/rip3a.in 5 -1
$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon1 $ENSTORE_DIR/test/rip3b.in 6 -1
$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 $ENSTORE_DIR/test/rip3a.in 7 -1
$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 $ENSTORE_DIR/test/rip3b.in 8 -1
