#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile a0$  $Revision$

/usr/local/bin/traceMode 1

cd $ENSTORE_DIR/test
make jobs
volume-declare ait
ecmd delvol CA2902
ecmd delvol CA2904
cd /pnfs/grau/ait/
for i in 1 2 3; do mkdir jon$i; cd jon$i; pcmd file_family jon-ait-$i; cd ..; done
cd $ENSTORE_DIR/test
