#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile a2a$  $Revision$

rsh rip1 "/usr/local/bin/traceMode 1"

#$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 $ENSTORE_DIR/test/scratch.in 15 0
#$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 $ENSTORE_DIR/test/rip8a.in   16 0
$ENSTORE_DIR/test/roll  -noread /pnfs/grau/ait/jon2 $ENSTORE_DIR/test/rip8b.in   17 0
#$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 $ENSTORE_DIR/test/fnal.in    18 0
