#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile a3a$  $Revision$

/usr/local/bin/traceMode 1

#$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 /home/bakken/enstore/test/scratch.in 15 0
#$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 /home/bakken/enstore/test/rip8a.in   16 0
#$ENSTORE_DIR/test/roll -noread /pnfs/grau/ait/jon2 /home/bakken/enstore/test/rip8b.in   17 0
$ENSTORE_DIR/test/roll  -noread /pnfs/grau/ait/jon2 /home/bakken/enstore/test/raid.in    18 0
