#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile a3a$  $Revision$

# rsh rip1 "/usr/local/bin/traceMode 1"

$ENSTORE_DIR/test/roll -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/rip3a-1.in 9  0
$ENSTORE_DIR/test/roll -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/rip3b-1.in 10 0
$ENSTORE_DIR/test/roll -noread /pnfs/grau/dlt/jon2 /home/bakken/enstore/test/rip3a-1.in 11 0
$ENSTORE_DIR/test/roll -noread /pnfs/grau/dlt/jon2 /home/bakken/enstore/test/rip3b-1.in 12 0
