#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile a3a$  $Revision$

#rsh rip1 "/usr/local/bin/traceMode 1"

$ENSTORE_DIR/test/roll  -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/rip4a.in  9 -1
$ENSTORE_DIR/test/roll  -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/rip4b.in 10 -1
$ENSTORE_DIR/test/roll  -noread /pnfs/grau/dlt/jon2 /home/bakken/enstore/test/rip4a.in 11 -1
#$ENSTORE_DIR/test/roll -noread /pnfs/grau/dlt/jon2 /home/bakken/enstore/test/rip4b.in 12 -1
