#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile d0$  $Revision$

rsh rip2 "/usr/local/bin/traceMode 1"

cd $ENSTORE_DIR/test
make jobs
volume-declare dlt
ecmd delvol CA2501
ecmd delvol CA2503
cd /pnfs/grau/dlt/
for i in 1 2 3; do mkdir jon$i; cd jon$i; pcmd file_family jon-dlt-$i; cd ..; done
cd $ENSTORE_DIR/test
