#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile d1$  $Revision$

#rsh rip1 "/usr/local/bin/traceMode 1"

./roll -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/scratch.in  9 100
./roll -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/rip8a.in    10 100
#./roll -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/rip8b.in   11 100
#./roll -noread /pnfs/grau/dlt/jon1 /home/bakken/enstore/test/fnal.in    12 100
 