#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile d1$  $Revision$

#rsh rip1 "/usr/local/bin/traceMode 1"

#$ENSTORE_DIR/test/roll -noread /pnfs/grau/dlt/jon1 $ENSTORE_DIR/test/scratch.in  9 0
$ENSTORE_DIR/test/roll  -noread /pnfs/grau/dlt/jon1 $ENSTORE_DIR/test/rip8a.in   10 0
$ENSTORE_DIR/test/roll  -noread /pnfs/grau/dlt/jon1 $ENSTORE_DIR/test/rip8b.in   11 0
#$ENSTORE_DIR/test/roll -noread /pnfs/grau/dlt/jon1 $ENSTORE_DIR/test/fnal.in    12 0
 