#!/bin/sh

while /bin/true; do
    cat $ENSTORE_DIR/test/files.in | while read f; do
        python $ENSTORE_DIR/src/encp.py $f out.out;
        diff out.out $ENSTORE_DIR/test/data/`basename $f` ;
    done ;
done
