#!/bin/sh

while /bin/true; do
    cat $ENSTORE_DIR/test/files.in | while read f; do
        rm -f loop_longtest.pids
        echo $$ > loop_longtest.pids
        rm -f longtest.out
        ecmd encp $f longtest.out;
        diff longtest.out $ENSTORE_DIR/test/data/`basename $f` ;
    done ;
done
