#!/bin/sh

while /bin/true; do
    cat $ENSTORE_DIR/test/files.in | while read f; do
        if [ -r $ENSTORE_DIR/test/longstop ] ; then exit 0; fi
        rm -f longtest.out
        encp $f longtest.out;
        diff longtest.out $ENSTORE_DIR/test/data/`basename $f` ;
    done ;
done
