#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile$  $Revision$

# rsh rip1 "/usr/local/bin/traceMode 1"

$ENSTORE_DIR/test/roll -noread /pnfs/grau/mammoth/jon1 $ENSTORE_DIR/test/rip3a.in 20 -1
$ENSTORE_DIR/test/roll -noread /pnfs/grau/mammoth/jon2 $ENSTORE_DIR/test/rip3b.in 21 -1
