#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile m0$  $Revision$

#rsh rip1 "/usr/local/bin/traceMode 1"

cd $ENSTORE_DIR/test
make jobs
volume-declare mam
cd /pnfs/grau/mammoth/
for i in 1 2 3; do mkdir jon$i; cd jon$i; pcmd file_family jon-mam-$i; cd ..; done
cd $ENSTORE_DIR/test
