#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile m1$  $Revision$

#rsh rip1 "/usr/local/bin/traceMode 1"

$ENSTORE_DIR/test/roll -noread /pnfs/grau/mammoth/jon1 $ENSTORE_DIR/test/rip8a.in  20 0
$ENSTORE_DIR/test/roll -noread /pnfs/grau/mammoth/jon1 $ENSTORE_DIR/test/rip8b.in  21 0
 