#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile m2$  $Revision$

#rsh rip1 "/usr/local/bin/traceMode 1"

$ENSTORE_DIR/test/roll -noread /pnfs/grau/mammoth/jon2 $ENSTORE_DIR/test/raid.in  22 0
$ENSTORE_DIR/test/roll -noread /pnfs/grau/mammoth/jon2 $ENSTORE_DIR/test/fnal.in  23 0
