#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

usage="USAGE: $0 base_read_dir_path"

if [ -n "${1-}" ] ; then
    base=$1
else
    echo "$usage"
    exit 1
fi

set -u  # force better programming and ability to use check for not set

rm -f reader_list*
rm -f *.out

read_list=./reader_list.$$

while /bin/true; do
    rm -f reader_list*
    if [ -r $ENSTORE_DIR/test/readstop ] ; then exit 2; fi
    find $base/ -type f -print >> $read_list
    cat $read_list | while read f; do
        if [ -r $ENSTORE_DIR/test/readstop ] ; then exit 2; fi
        fb=`basename $f`
        fo=$fb.out.$$
        ecmd encp $f $fo
        rm -f $fo
    done
    if [ $? -eq 2 ] ; then
       echo "FINISHED $base"
       exit 2
    fi
done
