#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

usage="USAGE: $0 base_read_dir_path"

if [ -n "${1-}" ] ; then
    base=$1
else
    echo "$usage"
    exit 1
fi

set -u  # force better programming and ability to use check for not set

read_list=./reader_list.$$
rm -f reader.pids
echo $$ > reader.pids

while /bin/true; do
    rm -f readerWT.pids
    echo $! > readerWT.pids
    rm -fr $read_list
    find $base/ -type f -print >> $read_list
    cat $read_list | while read f; do
        rm -f readerWC.pids
        echo $! > readerWC.pids
        rm -f reader.out
        ecmd encp $f reader.out
    done
done
