#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
set -u  # force better programming and ability to use check for not set

for i in fndapr hppc fntt1 8500-tests; do
    $ENSTORE_DIR/roll $i
done