#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
set -u  # force better programming and ability to use check for not set

writem=1
if [ "${1:-}" = "-nowrite" ] ; then
    shift
    writem=0
fi

readem=1
if [ "${1:-}" = "-noread" ] ; then
    shift
    readem=0
fi

if [ -z "${1-}" ] ; then
  echo "No output directory specified"
  exit 1
else
  place=$1
fi

if [ -z "${2-}" ] ; then
  datain="../data.in"
else
  datain="$2"
fi

if [ -z "${3-}" ] ; then
  subdirs="1 2 3"
else
  subdirs="$3"
fi

if [ -z "${4-}" ] ; then
  sleep_time="10"
else
  sleep_time="$4"
fi

if [ -z "${5-}" ] ; then
  delayed_dismount="0"
else
  delayed_dismount="$5"
fi

if [ -z "${6-}" ] ; then
  test_mode=" "
else
  test_mode="1073741824"
fi

if [ $writem -eq 1 ] ; then
   for d in $subdirs; do
      (cd $d; echo starting writer. directory: `pwd`,  files to write: $datain,  next request delay: $sleep_time; \
       rm -f writestop writer.output; ./writer $place $datain $sleep_time $delayed_dismount $test_mode>writer.output 2>&1 &)
   done
fi

if [ $readem -eq 1 ] ; then
   for d in $subdirs; do
      (cd $d; echo starting reader. directory:`pwd`, next request delay: $sleeptime; \
       rm -f readstop reader.output; ./reader $place $sleep_time >reader.output 2>&1 &)
   done
fi








