#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
set -u  # force better programming and ability to use check for not set

rm -f longstop
rm -f readstop
rm -f writestop

make datafiles
rm data.in
find $ENSTORE_DIR/test/data -type f -print > $ENSTORE_DIR/test/data.in

make jobs

for d in 1 2  ; do
   (cd $d; rm -f writer.output; ./writer /pnfs/enstore/fndapr ../data.in >writer.output 2>&1 &)
done

for d in 1 2  ; do
   (cd $d; rm -f reader.output; ./reader /pnfs/enstore/fndapr  >reader.output 2>&1 &)
done
