CCOPTS = -qlanglvl=ansi -c -I$(PYTHONINC)
LDOPTS = -bM:SRE -T512 -H512  -bI:$(PYTHONMOD)/python.exp

.SUFFIXES:
.SUFFIXES : .c .so

.c.so :
	$(CC) $(CCOPTS) $< -o $*.o
	ld $(LDOPTS) -bE:$*.exp -einit$* $*.o -o $*.so
	rm $*.o
