# Build a dynamically loadable, sharable object

.SUFFIXES:
.SUFFIXES: .c .so


CCOPTS = -ansiposix -c 
LDOPTS = -shared

.c.so :
	$(CC) $(CCOPTS) -I$(PYTHONINC) $< -o $*.o
	$(LD) $(LDOPTS)                 $*.o -o  $*.so
	rm $*.o
