#!/bin/sh

# we need one parameter which is the alarm msg
if [ ${#} -ne 1 ]; then exit;fi

if [ "${ENSTORE_DIR}" = "" ];
then
 . /usr/local/etc/setups.sh
 setup enstore
else
 . /usr/local/etc/setups.sh
 setup python
fi

enstore alarm --raise --root_error="${1}"
