#!/bin/sh

# we need one parameter which is the alarm msg
if [ ${#} -ne 1 ]; then exit;fi

# need to do this in order to do a setup
 . /usr/local/etc/setups.sh

if [ "${ENSTORE_DIR}" = "" ];
then
 setup enstore
fi

# do this so do not pick up python from /usr/bin
setup python
enstore alarm --raise --root_error="${1}"
