#!/bin/ksh
# @(#) $Id$
#===============================================================================
# This will erase a tape
#===============================================================================
 
#===============================================================================
# Get the tape device by looking in $1. If that's not set,
# try FTT_TAPE. If that's not set either, then exit.
export FTT_TAPE
FTT_TAPE=${1:-${FTT_TAPE:-""}}
FTT_TAPE=${FTT_TAPE:?"No device specified"}
#===============================================================================

ftt_test << EOD
ftt_open
ftt_write_vol_label -label fttest -type FTT_ANSI_HEADER
ftt_rewind
ftt_erase
ftt_verify_vol_label -label fttest -type FTT_BLANK_HEADER
ftt_close
quit
EOD
