#!/bin/sh

if [ $# = 0 ]
then
    echo "usage: $0 [options] script drive1 drive2 ... "
    echo "	options are:"
    echo "	-s	run sequentially"
    echo "	-p	run in parallel (default)"
    exit 1
fi

sequential=false

case x$1 in 
x-s)	sequential=true; 
	shift
	;;
x-p)	sequential=false; 
	shift
	;;
*)	;;
esac

base="$1"

script="$FTT_DIR/ftt_test/scripts/$1"

shift

for drive in $*
do
    outfile="`echo out $base $drive | sed -e 's;[/ ];_;g'`"
    cmd="$script $drive 2>&1 | tee $outfile" 
    if $sequential
    then
	$cmd
    else
	xterm	-T "$base $drive" \
		-n "$base $drive" \
		-e /bin/sh -c "$cmd;echo 'Press Enter';read line" &
    fi
done
