#!/bin/ksh
#===============================================================================
# This will dump a tape - used in recovering overwritten data tapes
#===============================================================================
 
#===============================================================================
# Get the tape device by looking in $1. If that's not set,
# try FTT_TAPE. If that's not set either, then exit.
export FTT_TAPE
FTT_TAPE=${1:-${FTT_TAPE:-""}}
FTT_TAPE=${FTT_TAPE:?"No device specified"}
#===============================================================================
 
ftt_test << EOD
ftt_open -read
ftt_dump
ftt_close
quit
EOD

