#!/bin/sh
# @(#) $Id$

if [ $# = 0 ]
then
    echo "usage: $0 [options] script drive1 drive2 ... "
    echo "	options are:"
    echo "	-s	run sequentially"
    echo "	-p	run in parallel (default)"
    exit 1
fi

sequential=false

case x$1 in 
x-s)	sequential=true; 
	shift
	;;
x-p)	sequential=false; 
	shift
	;;
*)	;;
esac

base="$1"

script="$1"

shift

kids=""
trap 'kill -9 $kids; exit' 2 3 15

for drive in $*
do
    outfile="`echo out $base $drive | sed -e 's;[/ ];_;g'`"
    cmd="$script $drive 2>&1 | tee $outfile" 
    if $sequential
    then
	$cmd
    else
	if [ "$DISPLAY" != "" ]
	then
	    xterm -T "$base $drive" -n "$base $drive" -sb -sl 1024 \
		-e /bin/sh -c "$cmd;echo 'Press Enter';read line" &
	    kids="$kids $!"
	else
	    $cmd 2>&1 | sed -e "s;^;$drive:	;" &
	    kids="$kids $!"
	fi
    fi
done

for drive in $*
do
    wait
done
