#!/bin/ksh
# $Id$
#===============================================================================
# This will write to end of tape
#===============================================================================
 
#===============================================================================
# Get the tape device by looking in $1. If that's not set,
# try FTT_TAPE. If that's not set either, then exit.
export FTT_TAPE
FTT_TAPE=${1:-${FTT_TAPE:-""}}
FTT_TAPE=${FTT_TAPE:?"No device specified"}
#===============================================================================
 
ftt_test << EOD
ftt_open
ftt_rewind

ftt_max_error 2
ftt_write_tblock -nblock 1000000 -bsize 65534 
ftt_max_error 5
ftt_test_status -FTT_AEOT
ftt_close
quit
EOD
