#!/bin/ksh
#===============================================================================
# This will test positioning withing a test tape.
# It assumes that the tape has been written with write.ftt.
#===============================================================================
 
#===============================================================================
# Get the tape device by looking in $1. If that's not set,
# try FTT_TAPE. If that's not set either, then exit.
export FTT_TAPE
FTT_TAPE=${1:-${FTT_TAPE:-""}}
FTT_TAPE=${FTT_TAPE:?"No device specified"}
#===============================================================================
 
ftt_test << EOD
ftt_open
ftt_rewind
ftt_test_status -FTT_ABOT
#===============================================================================
# first check to see if when we forward skip a file we are where
# we should be.
#===============================================================================
ftt_skip_fm 1
ftt_skip_fm 1
ftt_verify_position 2 0
ftt_verify_tblock -nblock 1
ftt_rewind
ftt_skip_fm 2
ftt_verify_position 2 0
ftt_verify_tblock -nblock 1
#
# forward skip too far
#
ftt_rewind
ftt_skip_fm 6 -status FTT_EBLANK
ftt_get_position -status FTT_EUNRECOVERED
#===============================================================================
# then check that if we backspace a file, we are where we should be.
#===============================================================================
ftt_rewind
ftt_skip_fm 3
ftt_skip_fm -1
ftt_verify_tblock -filemark
ftt_verify_position 3 0
ftt_verify_tblock -nblock 1
#
ftt_skip_fm -2
ftt_verify_tblock -filemark
ftt_verify_position 2 0
ftt_verify_tblock -nblock 1
#
# backward skip too far
#
ftt_skip_fm -10 -status FTT_ELEADER
ftt_get_position -status FTT_EUNRECOVERED
#
#===============================================================================
# do the same with records
#===============================================================================
ftt_rewind
ftt_skip_fm 1
ftt_skip_rec 500
ftt_verify_position 1 500
ftt_verify_tblock -nblock 1
ftt_skip_rec -100
ftt_verify_position 1 401
ftt_verify_tblock -nblock 1
#
# forward skip too far
#
ftt_skip_rec 700 -status FTT_EFILEMARK
ftt_get_position -status FTT_EUNRECOVERED
#
# backward skip too far
#
ftt_rewind
ftt_skip_fm 3
ftt_skip_rec 50
ftt_skip_rec -100 -status FTT_EFILEMARK
ftt_get_position -status FTT_EUNRECOVERED
#===============================================================================
# now skip to end of file
#===============================================================================
ftt_rewind
ftt_skip_to_double_fm
ftt_verify_tblock -filemark
ftt_verify_tblock -filemark -status FTT_EBLANK
ftt_echo "look at output. next line should say File no: 5 block no: 0"
ftt_get_position
ftt_rewind
ftt_close
EOD
