#!/bin/ksh
# @(#) $Id$
#==============================================================================
# This will change all the protections of a device file
#==============================================================================
#
 
#===============================================================================
# Get the tape device by looking in $1. If that's not set,
# try FTT_TAPE. If that's not set either, then exit.
export FTT_TAPE
FTT_TAPE=${1:-${FTT_TAPE:-""}}
FTT_TAPE=${FTT_TAPE:?"No device specified"}
#===============================================================================
 
ftt_test << EOD
ftt_open
ftt_verify_exist
ftt_chall votava products 777
ftt_close
quit
EOD
