#!/bin/ksh
#===============================================================================
# This will test the statistics routine.
#===============================================================================
 
#===============================================================================
# Get the tape device by looking in $1. If that's not set,
# try FTT_TAPE. If that's not set either, then exit.
export FTT_TAPE
FTT_TAPE=${1:-${FTT_TAPE:-""}}
FTT_TAPE=${FTT_TAPE:?"No device specified"}
#===============================================================================
 
ftt_test << EOD
ftt_open
ftt_rewind
ftt_echo "this is output of all the statistics. seem reasonable?"
ftt_get_stats
ftt_dump_stats

#***********************************
ftt_echo "writing 200k of data" 
ftt_echo "look at output, make sense?" 
#***********************************
ftt_init_stats
ftt_write_tblock -nblock 100 -bsize 2048
ftt_close_dev
ftt_update_stats -part_display

#***********************************
ftt_echo "reading 200k of data"
ftt_echo "look at output, make sense?"
#***********************************
ftt_rewind
ftt_init_stats
ftt_verify_tblock -nblock 100
ftt_close_dev
ftt_update_stats -part_display
#***********************************
ftt_echo "writing additional 200k of data"
ftt_echo "look at output, make sense?"
#***********************************
ftt_write_fm 
ftt_write_tblock -nblock 100 -bsize 2048
ftt_close_dev
ftt_update_stats -part_display
ftt_close
EOD
