#!/bin/ksh
#==============================================================================
# This will verify the data from the test tape.
# It assumes that the tape has been written with write.ftt.
#==============================================================================
 
#===============================================================================
# Get the tape device by looking in $1. If that's not set,
# try FTT_TAPE. If that's not set either, then exit.
export FTT_TAPE
FTT_TAPE=${1:-${FTT_TAPE:-""}}
FTT_TAPE=${FTT_TAPE:?"No device specified"}
#===============================================================================
 
ftt_test << EOD
ftt_open
ftt_verify_vol_label -label fttest -type FTT_ANSI_HEADER
ftt_verify_tblock -filemark
ftt_verify_tblock -nblock 1000 
ftt_verify_tblock -filemark
ftt_verify_tblock -nblock 2000 
ftt_verify_tblock -filemark
ftt_verify_tblock -nblock 3000
ftt_verify_tblock -filemark
ftt_verify_tblock -filemark
ftt_verify_tblock -status FTT_EBLANK
ftt_close
EOD
