#!/bin/sh

# This script creates an empty drivestat from scratch:
# 1. rename current database area, if exists
# 2. create directory for database area
# 3. initialize database area
# 4. copy appropriate pg_hba.conf from $ENSTORE_DIR/databases/conftol_files
# 5. start up databse server
# 6. create user "enstore"
# 7. create database owned by user "enstore"
# 8. create schema from $ENSTORE_DIR/databases/schemas/enstoredb.schema

enstore_dir=${ENSTORE_DIR}
database_area=/diska/enstore-pgdb
database_scripts=$enstore_dir/databases/scripts
database_owner=products
db_name=enstore
db_owner=enstore
db_port=5432
db_startup_script=$database_scripts/enstore-pgdb
db_schema=$enstore_dir/databases/schemas/accounting.schema

# find the host
host=`uname -n | cut -d. -f1`

case $host in
	stkensrv6|cdfensrv6|d0ensrv6)
		hba_file=$enstore_dir/databases/control_files/pg_hba.conf-$host-accounting
		;;
	*)
		hba_file=$enstore_dir/databases/control_files/pg_hba.conf-stkensrv6-accounting
		;;
esac

# need to setup enstore first
if [ "$enstore_dir" == "" ]
then
	echo "need to set up enstore first"
	exit
fi

# must be root
if [ "`whoami`" != "root" ]
then
	echo "must run as root"
	exit 0
fi

# check if $database_area exist. If so, rename it

if [ -d $database_area ]
then
	echo $database_area exists, rename it
	dest=$database_area.`date +%F.%T`
	echo mv $database_area $dest
	mv $database_area $dest
fi

# create initial database area
echo create database area $database_area
echo mkdir -p $database_area
mkdir -p $database_area
echo chown $database_owner.$database_owner $database_area
chown $database_owner.$database_owner $database_area
echo chmod go-rwx $database_area
chmod go-rwx $database_area
echo su $database_owner -c \"initdb -D $database_area\"
su $database_owner -c "initdb -D $database_area"

#  modify create pg_hba.conf
echo su $database_owner cp \"$hba_file $database_area/pg_hba.conf\"
su $database_owner -c "cp $hba_file $database_area/pg_hba.conf"

# bring up database server
echo su $database_owner -c \"postmaster -D $database_area -p $db_port -i \&\"
su $database_owner -c "postmaster -D $database_area -p $db_port -i &"
# echo su $database_owner -c "$db_startup_script start"
# su $database_owner -c "$db_startup_script start"

# wait for database server startup
echo waiting for database server to start up
sleep 10

# create user enstore
#
# This is a little bit different in batch mode
echo su $database_owner createuser -p $db_port -d -S -R -P enstore 
su $database_owner -c "psql template1 -p $db_port -c \"create user enstore password 'enstore_user' createdb;\""

# create database enstoredb
echo su $db_owner createdb -p $db_port $db_name
su $db_owner -c "createdb -p $db_port $db_name"

# # create languages for enstoredb
# echo su $database_owner -c \"createlang -p $db_port plpgsql $db_name\"
# su $database_owner -c "createlang -p $db_port plpgsql $db_name"
# echo su $database_owner -c \"createlang -p $db_port c $db_name\"
# su $database_owner -c "createlang -p $db_port c $db_name"

# create schemas
echo su $database_owner psql -p $db_port $db_name -f $db_schema
su $database_owner -c "psql -p $db_port $db_name -f $db_schema"
