#!/bin/sh

# To start, stop and restart postgres database server for enstore-pgdb.
# It shall be installed in /etc/rc.d/init.d/enstore-pgdb and linked from
# /etc/rc.d/rc3.d/S88enstore-pgdb and /etc/rc.d/rc6.d/S88enstore-pgdb

# need to be run as user 'products'
if [ "`whoami`" != 'products' ]
then
	su products -c "$0 $*"
	exit 0
fi

# get the host
host=`uname -n | cut -d. -f1`

# get db directory
case $host in
	rip1)
		db=/diska/postgres_db
		;;
	stkensrv6|cdfensrv6|d0ensrv6)
		db=/diska/enstore-pgdb
		;;
	*)
		echo no enstore-pgdb for this node: $host
		exit 0
		;;
esac

# setup postgres
. /usr/local/etc/setups.sh
setup postgres

pg=`which postmaster`
cmd=$1

# what to do?
case $cmd in
	start)
		# make sure there is no other running
		pid=`ps -axw| grep postmaster | grep $db | awk '{print $1}'`
		if [ "${pid}x" == "x" ]
		then
			# take care of the left over pid info, if any
			/bin/rm -f $db/postmaster.pid
			echo $pg -D $db -i &
			$pg -D $db -i &
		else
			echo enstore-pgdb has already started
		fi
		;;
	stop)
		# find the pid
		pid=`ps -axw| grep postmaster | grep $db | awk '{print $1}'`
		# make sure that we really have a process to kill
		if [ "${pid}x" == "x" ]
		then
			echo enstore-pgdb is not running
		else
			echo kill $pid
			kill $pid
		fi
		;;
	restart)
		$0 stop
		sleep 5
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac
exit 0
