#!/bin/sh

# This script dumps current schema from running databases
#
# usage: get_schema enstoredb|accounting|drivestat

enstore_dir=${ENSTORE_DIR}
schema_dir=$enstore_dir/databases/schemas

# need to setup enstore first
if [ "$enstore_dir" == "" ]
then
	echo "need to set up enstore first"
	exit
fi

if [ "$1" == "" ]
then
	echo "usage: $0 enstoredb|accounting|drivestat"
	exit
fi

case "$1" in
	enstoredb)
		db_host=stkensrv0.fnal.gov
		db_port=8888
		db_name=enstoredb
		schema_name=enstoredb.schema
		;;
	accounting)
		db_host=stkensrv6.fnal.gov
		db_port=5432
		db_name=enstore
		schema_name=accounting.schema
		;;
	drivestat)
		db_host=stkensrv6.fnal.gov
		db_port=8076
		db_name=drivestat
		schema_name=drivestat.schema
		;;
	*)
		echo usage: $0 "enstoredb|accounting|drivestat"
		exit
		;;
esac

echo pg_dump -p $db_port -h $db_host $db_name -f $schema_dir/$schema_name -i -s -x
pg_dump -p $db_port -h $db_host $db_name -f $schema_dir/$schema_name -i -s -x

# initialize some parameters in enstoredb

if [ "$1" == "enstoredb" ]
then
	echo "cat $enstore_dir/databases/scripts/init_enstoredb >> $schema_dir/$schema_name"
	cat $enstore_dir/databases/scripts/init_enstoredb >> $schema_dir/$schema_name
fi
