#!/bin/sh

set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

if [ -z "${1:-}" ] ; then echo `date` Usage $0 volume; exit 1; fi

tape=$1
log=/tmp/$tape.migrate
gotit=/tmp/$tape.gotit.$$
status=/data1/status
copy=$status/$tape.copy2b
done=$status/$tape.done
stop=$status/$tape.stop
halt=$status/HALT

if [ -r $halt ]; then echo `date` ERROR: $halt exists ... trouble; exit 0; fi

if [ -r $done ]; then echo `date` $tape already migrated; exit 0; fi

if [ -r $copy ]; then
   /data1/migrate_tape -v $tape >> $log 2>&1
   rc=$?
   if [ $rc -eq  0 ]; then
      echo `date` $tape already ready for migrating
      exit 0
   else
      echo `date` $tape NOT ready, but copy2b file found. doing rm $copy
      rm $copy
   fi
fi

/data1/migrate_tape -v $tape >> $log 2>&1
rc=$?
if [ $rc -eq 0 ]; then
   echo `date` $tape already ready for migrating
   touch $copy
   exit 0
fi

echo `date` Starting to get files from $tape

/data1/migrate_tape -l $tape >> $log 2>&1

rm -f $gotit
max_try=5
try=0
while [ $try -le $max_try ]; do
  try=`expr $try + 1`
  if [ `enstore vol --vol $tape| grep -c NOACCESS` -ne 0 ]; then
      echo `date` Clearing NOACCESS from $tape assuming trouble reading 
      enstore vol --clear $tape
  fi

  /data1/migrate_tape -0 -a -g -v $tape >> $log 2>&1
  /data1/migrate_tape -v $tape >> $log 2>&1
  rc=$?
  if [ $rc -eq 0 ]; then
     touch $copy
     touch $gotit
     break
  fi
done

if [ -r $gotit ]; then
    rm $gotit
    exit 0
else
    exit 1
fi
