#!/bin/sh
. /home/enstore/enstore/test/CDF_migration/migration-setup-enstore
set -u
tape=$1
files=/tmp/scan.$tape
command=/tmp/command.$tape
finalscan=/data1/status/finalscan.$tape
rm -f $files $command $finalscan 2>/dev/null
enstore fil --ls-active $tape >$files

#echo "export  ENSTORE_SPECIAL_LIB=CDF-Migration;"  > $command
#echo "export ENSTORE_SPECIAL_LIB" >> $command 
echo "encp --delayed=3 --priority=300000 "          >> $command
n=0
cat $files | while read f; do
  n=`expr $n + 1`
  echo `date` $n $f
  echo $f " " >>$command
done
echo "/dev/null" >>$command

cmd=`cat $command`
rm -f $command $files 2>/dev/null
echo `date` $cmd
eval $cmd >$finalscan 2>&1
rc=$?
if [ $rc -ne 0 ]; then
    echo `date` ERROR $tape bad return code
    /usr/bin/Mail -s "$tape migration error" enstore-admin@fnal.gov < $finalscan
else
    echo `date` $tape All files read
fi
date
exit $rc
