#!/bin/sh

cat badfiles |  while read o d n rest; do
    V=`enstore pnfs --cat $o 4 | grep IA`
    family=`enstore volume --vol $V | grep volume_family | cut -f2 -d.` 
    cd `dirname $n`
    dfamily=`enstore pnfs --file_family`
    echo $o ff=$family dff=$dfamily
    echo encp --priority=300000 --delayed-dismount=10 $o /data1/bja/$o 
    #     encp --priority=300000 --delayed-dismount=10 $o /data1/bja/$o 
    echo encp --priority=300000 --delayed-dismount=10 /data1/bja/$o $n
    #     encp --priority=300000 --delayed-dismount=10 /data1/bja/$o $n
    echo
done
