#!/bin/sh
#set -xv
if [ -n "${1:-}" ]; then
   vol=$1
else
   echo `date` USAGE: $0 volume
   exit 1
fi

ENCP="encp --delay=3"

files=/tmp/files.$vol
rm -f $files

pid1=""
pid2=""
enstore file --ls $vol >>$files
n=0
nmax=`wc -l $files|awk '{print $1}'`
nmax=`expr $nmax - 1`

while [ $n -le $nmax ]; do
  if [ -z "${pid1:-}" ]; then
     n=`expr $n + 1`
     file1=`head -n$n $files|tail -n1`
     cmd1="$ENCP $file1 /dev/null"
     echo `date` $cmd1
     eval $cmd1 &pid1=$!;echo '                             process' $pid1
  fi
  if [ -z "${pid2:-}" ]; then
     n=`expr $n + 1`
     file2=`head -n$n $files|tail -n1`
     cmd2="$ENCP $file2 /dev/null"
     echo `date` $cmd2
     eval $cmd2 &pid2=$!;echo '                             process' $pid2
  fi
  active1=`ps axuww | egrep "$cmd1" |grep -v grep`
  active2=`ps axuww | egrep "$cmd2" |grep -v grep`
  if [ -z "${active1:-}" ]; then
     echo `date` finished $file1 $pid1
     pid1=""
  fi
  if [ -z "${active2:-}" ]; then
     echo `date` finished $file2 $pid2
     pid2=""
  fi
  sleep 10
done
wait $pid1
echo `date` finished $file1 $pid1
wait $pid2
echo `date` finished $file2 $pid2
exit 0
