#!/bin/sh

if [ -r $1 ]; then
 f=$1
else
 f=/tmp/f.$$
 rm -f $f
 echo $1 >$f
fi

cat $f| while read tape; do 
	 echo $tape
	 $ENSTORE_DIR/test/CDF_migration/CDF_migrate1 $tape
	 $ENSTORE_DIR/test/CDF_migration/CDF_migrate2 $tape
	 done

rm -f $f
