#!/bin/sh
set -u
. /data1/setup-enstore
files=/tmp/scan.$1
pids=/tmp/pids.$1
rm -f $files $pids
enstore fil --ls-active $1 >$files

n=0
cat $files | while read f; do
  n=`expr $n + 1`
  echo `date` $n $f
  encp --delayed=3 $f /dev/null &pid=$!
  echo $pid >> $pids
done

cat $pids | while read pid; do
    notdone=1
    print=1
    while [ $notdone -eq 1 ]; do
        present=`pstree -acpu | egrep $pid|egrep -v egrep`
        if [ $print -eq 1 ]; then
           echo `date` $pid $present
           print=0
        fi
        if [ `echo $present | grep -c encp ` -eq 0 ]; then
           notdone=0
        else
           sleep 5
        fi
    done
done

rm -f $files $pids
date
