#!/bin/sh 

watch -n60 'f=/tmp/finalscan.*
        grep Starting $f|tail -n25
        grep Starting $f|wc -l
        ndone=`grep Starting $f|wc -l`
        wc -l /data1/work* 
        ntot=`wc -l /data1/work*`
        ntot=`echo $ntot | cut -f1 -d\ `
        tail -n1 $f
        left=`expr $ntot - $ndone`
        days=`expr $left \/ 26`
        echo 
        echo `date` $left tapes left or about $days days left
'
