#!/bin/sh 

watch -n60 'grep "Starting tape" /tmp/CDF_migrate1*|tail -n30
        grep "Starting tape" /tmp/CDF_migrate1*|wc -l
        echo; grep "Starting tape" /tmp/CDF_migrate2*|tail -n30
        grep "Starting tape" /tmp/CDF_migrate2*|wc -l
        ndone=`grep "Starting tape" /tmp/CDF_migrate2*|wc -l`
        echo
        tail -n1 /tmp/CDF_migrate*
        echo
        wc -l /data1/work*
        ntot=`wc -l /data1/work*`
        ntot=`echo $ntot | cut -f1 -d\ `
        tail -n1 /data1/work*
        df /data1
        left=`expr $ntot - $ndone`
        days=`expr $left \/ 10`
        echo 
        echo `date` $left tapes left or about $days days left
'
