#
# $Id$
#

#
# Makefile for AIX
#

CC = cc
CFLAGS = -g -I. -D_REENTRANT

LD = echo
MAKEDEP = $(CC) -M

SO_EXT =
EXE_EXT =
A_EXT = .a

RANLIB = ranlib
ARFLAGS = rv


LIBS = -lpthread
LDFLAGS = No shared library for AIX

include Makefile.inc

