#
# $Id$
#

#
#  Makefile for Sun Solaris 2.x
#

CC = /opt/SUNWspro/bin/cc
CFLAGS = -v -g -I. -Xa -KPIC -D_REENTRANT -DBSD_SYSCALLS
MAKEDEP = $(CC) -xM1


SO_EXT = .so
A_EXT = .a
EXE_EXT =

RANLIB = ranlib
ARFLAGS = rv

#MAP = -M mapfile

CPP = $(CC) -E

# for gcc

# CC = gcc
# CFLAGS = -Wall -pedantic -g -I. -O0 -D_REENTRANT -DBSD_SYSCALLS
# MAKEDEP = $(CC) -M


LIBS = -ldl -lnsl -lsocket -lresolv -lthread
LDFLAGS = -G


include Makefile.inc
