#
# $Id$
#

#
# Makefile for SGI IRIX
#

#CC = 
CFLAGS = -g -mips3 -n32 -I. -D_REENTRANT -DBSD_SYSCALLS

SO_EXT = .so
A_EXT = .a
EXE_EXT =

RANLIB = true
ARFLAGS =


MAKEDEP = $(CC) -M


LIBS = -lpthread
LDFLAGS = -shared
SO_INIT =
EXE_INIT =

include Makefile.inc
