#
# $Id$
#

#
# Makefile for Win32 with cygwin
#

CC = gcc
CFLAGS = -g -I. -Wall -pedantic -D_REENTRANT -DDCAP_NO_PREAD
CPP = cpp
LD = gcc

SO_EXT = .dll
EXE_EXT = .exe
A_EXT = .lib

RANLIB = ranlib
ARFLAGS = rv


MAKEDEP = $(CC) -M -I.
#MAP = --version-script=mapfile
LIBS = -lcygwin -lpthread -lc
LDFLAGS = -shared

include Makefile.inc

