#!/bin/sh

# we need to reset this because patrol.pl set it to ''
IFS="    
"
export IFS

# look for the patrol alarm file and see if it contains anything
pafile="`./enget_patrol_file`";

if [ -s $pafile ];
then
   exit 1
fi

exit 0
