#!/bin/sh

# we need to reset this because patrol.pl set it to ''
IFS="    
"
export IFS

# set up the local environment to we can find enstore
. /usr/local/etc/setups.sh

setup myen

# get the location of the enstore patrol file
pafile="`ecmd ala --patrol_file`";

echo $pafile;
