#!/bin/sh

PATH=$PATH:$HOME
export PATH

. /usr/local/etc/setups.sh
setup perl
setup enstore

PDIR=/usr/hppc_home/berman/work/patrol;export PDIR
POUT=/tmp/.enpatrol;export POUT

$PDIR/patrol3.6a/patrol.pl -l $POUT/patrol.`hostname |cut -f 1 -d .`.obs -c $PDIR/enpatrol.cf -w $POUT/patrol@`hostname |cut -f 1 -d .`.out -t $POUT

sleep 15

$PDIR/patrol3.6a/patrol.pl -i www -s $POUT -c $PDIR/enpatrol.cf -w $PDIR/patrol3.6a/www -t $POUT & 
