#!/bin/sh

# we need to reset this because patrol.pl set it to ''
IFS=" 	 
"
export IFS

# set up the local environment to we can find enstore
. /usr/local/etc/setups.sh

# allow the user to specify a different enstore rather than the current one
if [ "${ENSTORE_SETUP:-42}" = "42" ];
then
   ENSTORE_SETUP="enstore"
fi

setup $ENSTORE_SETUP

# check if the server is alive
alive=" --alive --alive_rcv_timeout=5 --alive_retries=2 ";export alive

# map the server name to the ecmd arg and check if the server is alive
case $1 in
	admin_clerk)
		ecmd acc $alive >/dev/null 2>&1;
		rtn=$?;;
	file_clerk)
		ecmd fcc $alive >/dev/null 2>&1;
		rtn=$?;;
	inquisitor)
		ecmd inq $alive >/dev/null 2>&1;
		rtn=$?;;
	*library_manager)
		ecmd lmc $alive $1 >/dev/null 2>&1;
		rtn=$?;;
	logserver)
		ecmd log $alive >/dev/null 2>&1;
		rtn=$?;;
	*media_changer)
		ecmd mcc $alive $1 >/dev/null 2>&1;
		rtn=$?;;
	*mover)
		ecmd mov $alive $1 >/dev/null 2>&1;
		rtn=$?;;
	volume_clerk)
		ecmd vcc $alive >/dev/null 2>&1;
		rtn=$?;;
	*)
		rtn=0;;
esac

if [ "$rtn" = "0" ]
then
	exit 0 
	 
else
	ecmd start --just $1 > /dev/null 2>&1
	rtn=$?
	if [ "$rtn" = "1" ]
	then
	    exit 2
	else
	    exit 1 
	fi

fi
