# This file contains library manager director policies
policydict = {'CD-LTO4F1.library_manager': {1: {'rule': {'storage_group': 'nova',
                                                    'file_family': 'rawdata_NDOS_unmerged',
                                                    'wrapper': 'cpio_odc',
                                                    },
                                           'minimal_file_size': 5000000000L,
                                           'resulting_library':'CD-DiskSF',
                                           'max_files_in_pack': 50, 
                                           'max_waiting_time': 24*3600,
                                           },
                                           2: {'rule': {'storage_group': 'nova',
                                                    'file_family': 'reco_NDOS',
                                                    'wrapper': 'cpio_odc',
                                                    },
                                           'minimal_file_size': 5000000000L,
                                           'resulting_library':'CD-DiskSF',
                                           'max_files_in_pack': 50, 
                                           'max_waiting_time': 24*3600,
                                           },
                                           3: {'rule': {'storage_group': 'lqcd',
                                                    'file_family': 'lqcd-nHYPBSM',
                                                    'wrapper': 'cpio_odc',
                                                    },
                                           'minimal_file_size': 4000000000L,
                                           'resulting_library':'CD-DiskSF',
                                           'max_files_in_pack': 1000, 
                                           'max_waiting_time': 12*3600,
                                           },
                                           4: {'rule': {'storage_group': 'lqcd',
                                                    'file_family': 'lqcd-pndme',
                                                    'wrapper': 'cpio_odc',
                                                    },
                                           'minimal_file_size': 8000000000L,
                                           'resulting_library':'CD-DiskSF',
                                           'max_files_in_pack': 8, 
                                           'max_waiting_time': 12*3600,
                                           },
                            },
              'CD-LTO4F1T.library_manager': {2: {'rule': {'storage_group': 'ssa_test',
                                                    'file_family': 'ssa_test',
                                                    'wrapper': 'cpio_odc',
                                                    },
                                           'minimal_file_size': 2000000000L,
                                           'max_files_in_pack': 100, 
                                           'max_waiting_time': 120,
                                           'resulting_library':'CD-DiskSF'
                                           }
                             
                             },
              'CD-LTO4GST.library_manager': {1: {'rule': {'storage_group': 'ssa_test',
                                                    'file_family': 'ssa_test',
                                                    'wrapper': 'cpio_odc',
                                                    },
                                           'minimal_file_size': 2000000000L,
                                           'max_files_in_pack': 100, 
                                           'max_waiting_time': 120,
                                           'resulting_library':'CD-DiskSF'
                                           }
                             
                             },
              }
