#!/bin/sh

#
# San the .py file in the directory above and generalte a picture
# of the inheritance.
#
rm -f [1-9].out
rm -f obj.dot
rm -f obj.ps

grep -h '^class.*\:' ${ENSTORE_DIR}/src/[a-z]*.py        > 1.out
sed -e  's/class//g'             < 1.out > 2.out
sed -e  's/://g'                 < 2.out > 3.out
sed -e  's/pass//g'              < 3.out > 4.out
sed -e  's/,/\->/g'              < 4.out > 5.out
sed -e  's/(/->/g'               < 5.out > 6.out
sed -e  's/)//g'                 < 6.out > 7.out


echo 'digraph objs { '           >  obj.dot
cat 7.out                        >> obj.dot

echo 'UDPServer -> TCPServer'    >> obj.dot
echo 'size="8,11"'               >> obj.dot
echo 'center=1'                  >> obj.dot
echo 'rotate=0'                  >> obj.dot
echo 'ordering=out'              >> obj.dot
echo 'rankdir=LR'                >> obj.dot
echo 'margin=0.5'                >> obj.dot
echo 'dir=back'                  >> obj.dot
echo '}'                         >> obj.dot

dot -Tps obj.dot > obj.ps

rm [1-9].out
rm obj.dot
