#include <stdio.h>
#include <ftt_private.h>

int ftt_trans_in[] = {
	/*    0 NOERROR	*/	FTT_SUCCESS,
	/*    1	EPERM	*/	FTT_EPERM,
	/*    2	ENOENT	*/	FTT_ENOENT,
	/*    3	ESRCH	*/	FTT_ENOENT,
	/*    4	EINTR	*/	FTT_EUNRECOVERED,
	/*    5	EIO	*/	FTT_EIO,
	/*    6	ENXIO	*/	FTT_ENXIO,
	/*    7	E2BIG	*/	FTT_EBLKSIZE,
	/*    8	ENOEXEC	*/	FTT_ENOEXEC,
	/*    9	EBADF	*/	FTT_ENOENT,
	/*   10	ECHILD	*/	FTT_ENOTSUPPORTED,
	/*   11	EAGAIN	*/	FTT_ENOTAPE,
	/*   12	ENOMEM	*/	FTT_ENOMEM,
	/*   13	EACCES	*/	FTT_EPERM,
	/*   14	EFAULT	*/	FTT_EFAULT,
	/*   15	ENOTBLK	*/	FTT_ENOTSUPPORTED,
	/*   16	EBUSY	*/	FTT_EBUSY,
	/*   17	EEXIST	*/	FTT_ENOTSUPPORTED,
	/*   18	EXDEV	*/	FTT_ENOTSUPPORTED,
	/*   19	ENODEV	*/	FTT_ENOENT,
	/*   20	ENOTDIR	*/	FTT_ENOENT,
	/*   21	EISDIR	*/	FTT_ENOENT,
	/*   22	EINVAL	*/	FTT_EBLKSIZE,
	/*   23	ENFILE	*/	FTT_ENFILE,
	/*   24	EMFILE	*/	FTT_ENFILE,
	/*   25	ENOTTY	*/	FTT_ENOTTAPE,
	/*   26	ETXTBSY	*/	FTT_ENOENT,
	/*   27	EFBIG	*/	FTT_EBLKSIZE,
	/*   28	ENOSPC	*/	FTT_EBLANK,
	/*   29	ESPIPE	*/	FTT_ENOTSUPPORTED,
	/*   30	EROFS	*/	FTT_EROFS,
	/*   31	EMLINK	*/	FTT_ENOTSUPPORTED,
	/*   32	EPIPE	*/	FTT_ENOTSUPPORTED,
	/*   33	EDOM	*/	FTT_ENOTSUPPORTED,
	/*   34	ERANGE	*/	FTT_ENOTSUPPORTED,
	/*   35	ENOMSG	*/	FTT_ENOTSUPPORTED,
	/*   36	EIDRM	*/	FTT_ENOTSUPPORTED,
	/*   37	ECHRNG	*/	FTT_ENOTSUPPORTED,
};

int ftt_trans_skiprec[] = {
	/*    0 NOERROR	*/	FTT_SUCCESS,
	/*    1	EPERM	*/	FTT_EPERM,
	/*    2	ENOENT	*/	FTT_ENOENT,
	/*    3	ESRCH	*/	FTT_ENOENT,
	/*    4	EINTR	*/	FTT_EUNRECOVERED,
	/*    5	EIO	*/	FTT_EFILEMARK,
	/*    6	ENXIO	*/	FTT_ENXIO,
	/*    7	E2BIG	*/	FTT_EBLKSIZE,
	/*    8	ENOEXEC	*/	FTT_ENOEXEC,
	/*    9	EBADF	*/	FTT_ENOENT,
	/*   10	ECHILD	*/	FTT_ENOTSUPPORTED,
	/*   11	EAGAIN	*/	FTT_ENOTAPE,
	/*   12	ENOMEM	*/	FTT_ENOMEM,
	/*   13	EACCES	*/	FTT_EPERM,
	/*   14	EFAULT	*/	FTT_EFAULT,
	/*   15	ENOTBLK	*/	FTT_ENOTSUPPORTED,
	/*   16	EBUSY	*/	FTT_EBUSY,
	/*   17	EEXIST	*/	FTT_ENOTSUPPORTED,
	/*   18	EXDEV	*/	FTT_ENOTSUPPORTED,
	/*   19	ENODEV	*/	FTT_ENOENT,
	/*   20	ENOTDIR	*/	FTT_ENOENT,
	/*   21	EISDIR	*/	FTT_ENOENT,
	/*   22	EINVAL	*/	FTT_EBLKSIZE,
	/*   23	ENFILE	*/	FTT_ENFILE,
	/*   24	EMFILE	*/	FTT_ENFILE,
	/*   25	ENOTTY	*/	FTT_ENOTTAPE,
	/*   26	ETXTBSY	*/	FTT_ENOENT,
	/*   27	EFBIG	*/	FTT_EFILEMARK,
	/*   28	ENOSPC	*/	FTT_EFILEMARK,
	/*   29	ESPIPE	*/	FTT_ENOTSUPPORTED,
	/*   30	EROFS	*/	FTT_EROFS,
	/*   31	EMLINK	*/	FTT_ENOTSUPPORTED,
	/*   32	EPIPE	*/	FTT_ENOTSUPPORTED,
	/*   33	EDOM	*/	FTT_ENOTSUPPORTED,
	/*   34	ERANGE	*/	FTT_ENOTSUPPORTED,
	/*   35	ENOMSG	*/	FTT_ENOTSUPPORTED,
	/*   36	EIDRM	*/	FTT_ENOTSUPPORTED,
	/*   37	ECHRNG	*/	FTT_ENOTSUPPORTED,
};
int ftt_trans_skipf[] = {
	/*    0 NOERROR	*/	FTT_SUCCESS,
	/*    1	EPERM	*/	FTT_EPERM,
	/*    2	ENOENT	*/	FTT_ENOENT,
	/*    3	ESRCH	*/	FTT_ENOENT,
	/*    4	EINTR	*/	FTT_EUNRECOVERED,
	/*    5	EIO	*/	FTT_EBLANK,
	/*    6	ENXIO	*/	FTT_ENXIO,
	/*    7	E2BIG	*/	FTT_EBLKSIZE,
	/*    8	ENOEXEC	*/	FTT_ENOEXEC,
	/*    9	EBADF	*/	FTT_ENOENT,
	/*   10	ECHILD	*/	FTT_ENOTSUPPORTED,
	/*   11	EAGAIN	*/	FTT_ENOTAPE,
	/*   12	ENOMEM	*/	FTT_ENOMEM,
	/*   13	EACCES	*/	FTT_EPERM,
	/*   14	EFAULT	*/	FTT_EFAULT,
	/*   15	ENOTBLK	*/	FTT_ENOTSUPPORTED,
	/*   16	EBUSY	*/	FTT_EBUSY,
	/*   17	EEXIST	*/	FTT_ENOTSUPPORTED,
	/*   18	EXDEV	*/	FTT_ENOTSUPPORTED,
	/*   19	ENODEV	*/	FTT_ENOENT,
	/*   20	ENOTDIR	*/	FTT_ENOENT,
	/*   21	EISDIR	*/	FTT_ENOENT,
	/*   22	EINVAL	*/	FTT_EBLKSIZE,
	/*   23	ENFILE	*/	FTT_ENFILE,
	/*   24	EMFILE	*/	FTT_ENFILE,
	/*   25	ENOTTY	*/	FTT_ENOTTAPE,
	/*   26	ETXTBSY	*/	FTT_ENOENT,
	/*   27	EFBIG	*/	FTT_EBLANK,
	/*   28	ENOSPC	*/	FTT_EBLANK,
	/*   29	ESPIPE	*/	FTT_ENOTSUPPORTED,
	/*   30	EROFS	*/	FTT_EROFS,
	/*   31	EMLINK	*/	FTT_ENOTSUPPORTED,
	/*   32	EPIPE	*/	FTT_ENOTSUPPORTED,
	/*   33	EDOM	*/	FTT_ENOTSUPPORTED,
	/*   34	ERANGE	*/	FTT_ENOTSUPPORTED,
	/*   35	ENOMSG	*/	FTT_ENOTSUPPORTED,
	/*   36	EIDRM	*/	FTT_ENOTSUPPORTED,
	/*   37	ECHRNG	*/	FTT_ENOTSUPPORTED,
};
int ftt_trans_skipr[] = {
	/*    0 NOERROR	*/	FTT_SUCCESS,
	/*    1	EPERM	*/	FTT_EPERM,
	/*    2	ENOENT	*/	FTT_ENOENT,
	/*    3	ESRCH	*/	FTT_ENOENT,
	/*    4	EINTR	*/	FTT_EUNRECOVERED,
	/*    5	EIO	*/	FTT_ELEADER,
	/*    6	ENXIO	*/	FTT_ENXIO,
	/*    7	E2BIG	*/	FTT_EBLKSIZE,
	/*    8	ENOEXEC	*/	FTT_ENOEXEC,
	/*    9	EBADF	*/	FTT_ENOENT,
	/*   10	ECHILD	*/	FTT_ENOTSUPPORTED,
	/*   11	EAGAIN	*/	FTT_ENOTAPE,
	/*   12	ENOMEM	*/	FTT_ENOMEM,
	/*   13	EACCES	*/	FTT_EPERM,
	/*   14	EFAULT	*/	FTT_EFAULT,
	/*   15	ENOTBLK	*/	FTT_ENOTSUPPORTED,
	/*   16	EBUSY	*/	FTT_EBUSY,
	/*   17	EEXIST	*/	FTT_ENOTSUPPORTED,
	/*   18	EXDEV	*/	FTT_ENOTSUPPORTED,
	/*   19	ENODEV	*/	FTT_ENOENT,
	/*   20	ENOTDIR	*/	FTT_ENOENT,
	/*   21	EISDIR	*/	FTT_ENOENT,
	/*   22	EINVAL	*/	FTT_EBLKSIZE,
	/*   23	ENFILE	*/	FTT_ENFILE,
	/*   24	EMFILE	*/	FTT_ENFILE,
	/*   25	ENOTTY	*/	FTT_ENOTTAPE,
	/*   26	ETXTBSY	*/	FTT_ENOENT,
	/*   27	EFBIG	*/	FTT_ELEADER,
	/*   28	ENOSPC	*/	FTT_ELEADER,
	/*   29	ESPIPE	*/	FTT_ENOTSUPPORTED,
	/*   30	EROFS	*/	FTT_EROFS,
	/*   31	EMLINK	*/	FTT_ENOTSUPPORTED,
	/*   32	EPIPE	*/	FTT_ENOTSUPPORTED,
	/*   33	EDOM	*/	FTT_ENOTSUPPORTED,
	/*   34	ERANGE	*/	FTT_ENOTSUPPORTED,
	/*   35	ENOMSG	*/	FTT_ENOTSUPPORTED,
	/*   36	EIDRM	*/	FTT_ENOTSUPPORTED,
	/*   37	ECHRNG	*/	FTT_ENOTSUPPORTED,
};

int ftt_trans_out[] = {
	/*    0 NOERROR	*/	FTT_SUCCESS,
	/*    1	EPERM	*/	FTT_EROFS,
	/*    2	ENOENT	*/	FTT_ENOENT,
	/*    3	ESRCH	*/	FTT_ENOENT,
	/*    4	EINTR	*/	FTT_EUNRECOVERED,
	/*    5	EIO	*/	FTT_EIO,
	/*    6	ENXIO	*/	FTT_ENXIO,
	/*    7	E2BIG	*/	FTT_EBLKSIZE,
	/*    8	ENOEXEC	*/	FTT_ENOEXEC,
	/*    9	EBADF	*/	FTT_EROFS,
	/*   10	ECHILD	*/	FTT_ENOTSUPPORTED,
	/*   11	EAGAIN	*/	FTT_ENOTAPE,
	/*   12	ENOMEM	*/	FTT_ENOMEM,
	/*   13	EACCES	*/	FTT_EPERM,
	/*   14	EFAULT	*/	FTT_EFAULT,
	/*   15	ENOTBLK	*/	FTT_ENOTSUPPORTED,
	/*   16	EBUSY	*/	FTT_EBUSY,
	/*   17	EEXIST	*/	FTT_ENOTSUPPORTED,
	/*   18	EXDEV	*/	FTT_ENOTSUPPORTED,
	/*   19	ENODEV	*/	FTT_ENOENT,
	/*   20	ENOTDIR	*/	FTT_ENOENT,
	/*   21	EISDIR	*/	FTT_ENOENT,
	/*   22	EINVAL	*/	FTT_EBLKSIZE,
	/*   23	ENFILE	*/	FTT_ENFILE,
	/*   24	EMFILE	*/	FTT_ENFILE,
	/*   25	ENOTTY	*/	FTT_ENOTTAPE,
	/*   26	ETXTBSY	*/	FTT_ENOENT,
	/*   27	EFBIG	*/	FTT_EBLKSIZE,
	/*   28	ENOSPC	*/	FTT_EBLKSIZE,
	/*   29	ESPIPE	*/	FTT_ENOTSUPPORTED,
	/*   30	EROFS	*/	FTT_EROFS,
	/*   31	EMLINK	*/	FTT_ENOTSUPPORTED,
	/*   32	EPIPE	*/	FTT_ENOTSUPPORTED,
	/*   33	EDOM	*/	FTT_ENOTSUPPORTED,
	/*   34	ERANGE	*/	FTT_ENOTSUPPORTED,
	/*   35	ENOMSG	*/	FTT_ENOTSUPPORTED,
	/*   36	EIDRM	*/	FTT_ENOTSUPPORTED,
	/*   37	ECHRNG	*/	FTT_ENOTSUPPORTED,
};

int *ftt_trans_table[] = {
    /* none...but just to be safe0 */ ftt_trans_in,
    /* FTT_OPN_READ		 1 */ ftt_trans_in,
    /* FTT_OPN_WRITE		 2 */ ftt_trans_out,
    /* FTT_OPN_WRITEFM		 3 */ ftt_trans_out,
    /* FTT_OPN_SKIPREC		 4 */ ftt_trans_skiprec,
    /* FTT_OPN_SKIPFM		 5 */ ftt_trans_skipf,
    /* FTT_OPN_REWIND		 6 */ ftt_trans_skipf,
    /* FTT_OPN_UNLOAD		 7 */ ftt_trans_skipf,
    /* FTT_OPN_RETENSION	 8 */ ftt_trans_skipf,
    /* FTT_OPN_ERASE		 9 */ ftt_trans_out,
    /* FTT_OPN_STATUS		10 */ ftt_trans_in,
    /* FTT_OPN_GET_STATUS	11 */ ftt_trans_in,
    /* FTT_OPN_ASYNC 		12 */ ftt_trans_in,
    /* FTT_OPN_PASSTHRU         13 */ ftt_trans_out,
    /* FTT_OPN_CHALL            14 */ ftt_trans_out,
    /* FTT_OPN_OPEN             15 */ ftt_trans_out,
    /* FTT_OPN_RSKIPREC		16 */ ftt_trans_skiprec,
    /* FTT_OPN_RSKIPFM		16 */ ftt_trans_skipr,
};

/*
** commands to popen to read device id-s
*/
static char AIXfind[] =
    "/usr/sbin/lscfg -v -l rmt%d | \
       grep 'Machine Type' |       \
       sed -e 's/.*\.//'";

static char IRIXfind[] =
    "/sbin/hinv | \
       grep 'Tape drive: unit %2$d on SCSI controller %1$d:' | \
       sed -e 's/.*: *//' -e 's/8mm(\\(.*\\).) cartridge */EXB-\\1/'";

static char IRIXfindVME[] =
    "/sbin/hinv | \
       grep 'Tape drive: unit %2$d on VME-SCSI controller %1$d:' | \
       sed -e 's/.*:  *//' -e 's/8mm(\\(.*\\).) cartridge */EXB-\\1/'";

/*
** device id's
*/

ftt_dev_entry devtable[] = {
    {"AIX", "EXB-8505", "SCSI", FTT_FLAG_HOLD_SIGNALS, 
	FTT_OP_UNLOAD|FTT_OP_STATUS|FTT_OP_GET_STATUS,ftt_trans_table,
	"/dev/rmt%d", 1, AIXfind, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
        { "/dev/rmt/%d.1",        0,  0,0x15, 0,  0,                 0, 1},
        { "/dev/rmt/%d.1",        0,  0,0x00, 0,  0,                 0, 1},
        { "/dev/rmt/%d.1",       -2,  0,   0, 1,  0, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d"  ,        0,  0,0x15, 0,  0, FTT_RWOC|       0, 1},
        { "/dev/rmt/%d.1",        0,  0,0x15, 0,  0,                 0, 0},
        { "/dev/rmt/%d.2",        0,  0,0x15, 0,  0, FTT_RWOC|FTT_RTOO, 1},
        { "/dev/rmt/%d.3",        0,  0,0x15, 0,  0,        0|FTT_RTOO, 0},
        { "/dev/rmt/%d"  ,        0,  1,0x8c, 0,  0, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.1",        0,  1,0x8c, 0,  0,                 0, 0},
        { "/dev/rmt/%d.2",        0,  1,0x8c, 0,  0, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.3",        0,  1,0x8c, 0,  0,        0|FTT_RTOO, 0},
        { "/dev/rmt/%d.4",        1,  0,0x14, 0,  0, FTT_RWOC|       0, 1},
        { "/dev/rmt/%d.5",        1,  0,0x14, 0,  0,                 0, 1},
        { "/dev/rmt/%d.6",        1,  0,0x14, 0,  0, FTT_RWOC|FTT_RTOO, 1},
        { "/dev/rmt/%d.7",        1,  0,0x14, 0,  0,        0|FTT_RTOO, 1},
        { "/dev/rmt/%d.4",        1,  1,0x90, 0,  0, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.5",        1,  1,0x90, 0,  0,                 0, 0},
        { "/dev/rmt/%d.6",        1,  1,0x90, 0,  0, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.7",        1,  1,0x90, 0,  0,        0|FTT_RTOO, 0},
        { "/dev/rmt/%d"  ,        0,  0,0x15, 0,  1, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.1",        0,  0,0x15, 0,  1,                 0, 0},
        { "/dev/rmt/%d.2",        0,  0,0x15, 0,  1, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.3",        0,  0,0x15, 0,  1,        0|FTT_RTOO, 0},
        { "/dev/rmt/%d"  ,        0,  1,0x8c, 0,  1, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.1",        0,  1,0x8c, 0,  1,                 0, 0},
        { "/dev/rmt/%d.2",        0,  1,0x8c, 0,  1, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.3",        0,  1,0x8c, 0,  1,        0|FTT_RTOO, 0},
        { "/dev/rmt/%d.4",        1,  0,0x14, 0,  1, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.5",        1,  0,0x14, 0,  1,                 0, 0},
        { "/dev/rmt/%d.6",        1,  0,0x14, 0,  1, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.7",        1,  0,0x14, 0,  1,        0|FTT_RTOO, 0},
        { "/dev/rmt/%d.4",        1,  1,0x90, 0,  1, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.5",        1,  1,0x90, 0,  1,                 0, 0},
        { "/dev/rmt/%d.6",        1,  1,0x90, 0,  1, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.7",        1,  1,0x90, 0,  1,        0|FTT_RTOO, 0},
        { 0, },
    }},
    {"AIX", "EXB-8500", "SCSI", FTT_FLAG_HOLD_SIGNALS, 
	FTT_OP_UNLOAD|FTT_OP_STATUS|FTT_OP_GET_STATUS,ftt_trans_table,
	"/dev/rmt%d", 1, AIXfind, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
        { "/dev/rmt/%d.1",        0,  0,0x15, 0,  0,                 0, 1},
        { "/dev/rmt/%d.1",        0,  0,0x00, 0,  0,                 0, 1},
        { "/dev/rmt/%d.1",       -2,  0,   0, 1,  0, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d"  ,        0,  0,0x15, 0,  0, FTT_RWOC|       0, 1},
        { "/dev/rmt/%d.1",        0,  0,0x15, 0,  0,                 0, 0},
        { "/dev/rmt/%d.2",        0,  0,0x15, 0,  0, FTT_RWOC|FTT_RTOO, 1},
        { "/dev/rmt/%d.3",        0,  0,0x15, 0,  0,        0|FTT_RTOO, 1},
        { "/dev/rmt/%d.4",        1,  0,0x14, 0,  0, FTT_RWOC|       0, 1},
        { "/dev/rmt/%d.5",        1,  0,0x14, 0,  0,                 0, 1},
        { "/dev/rmt/%d.6",        1,  0,0x14, 0,  0, FTT_RWOC|FTT_RTOO, 1},
        { "/dev/rmt/%d.7",        1,  0,0x14, 0,  0,        0|FTT_RTOO, 1},
        { "/dev/rmt/%d"  ,        0,  0,0x15, 0,  1, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.1",        0,  0,0x15, 0,  1,                 0, 0},
        { "/dev/rmt/%d.2",        0,  0,0x15, 0,  1, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.3",        0,  0,0x15, 0,  1,        0|FTT_RTOO, 0},
        { "/dev/rmt/%d.4",        1,  0,0x14, 0,  1, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.5",        1,  0,0x14, 0,  1,                 0, 0},
        { "/dev/rmt/%d.6",        1,  0,0x14, 0,  1, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.7",        1,  0,0x14, 0,  1,        0|FTT_RTOO, 0},
        { 0, },
    }},
    {"AIX", "EXB-8200", "", FTT_FLAG_HOLD_SIGNALS, 
	FTT_OP_UNLOAD|FTT_OP_STATUS|FTT_OP_GET_STATUS,ftt_trans_table,
	"/dev/rmt%d", 1, AIXfind, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
        { "/dev/rmt/%d.1",        0,  0,   0, 0,  0,                 0, 1},
        { "/dev/rmt/%d.1",       -2,  0,   0, 1,  0, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d"  ,        0,  0,   0, 0,  0, FTT_RWOC|       0, 1},
        { "/dev/rmt/%d.1",        0,  0,   0, 0,  0,                 0, 0},
        { "/dev/rmt/%d.2",        0,  0,   0, 0,  0, FTT_RWOC|FTT_RTOO, 1},
        { "/dev/rmt/%d.3",        0,  0,   0, 0,  0,        0|FTT_RTOO, 1},
        { "/dev/rmt/%d"  ,        0,  0,   0, 0,  1, FTT_RWOC|       0, 0},
        { "/dev/rmt/%d.1",        0,  0,   0, 0,  1,                 0, 0},
        { "/dev/rmt/%d.2",        0,  0,   0, 0,  1, FTT_RWOC|FTT_RTOO, 0},
        { "/dev/rmt/%d.3",        0,  0,   0, 0,  1,        0|FTT_RTOO, 0},
        { 0, },
    }},
    {"IRIX+5", "DLT", "SCSI", FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/tps%dd%d", 2, IRIXfind, {
    /*   string                  den mod hwd pas fxd rewind            ,1st */
    /*   ======                  === === === === === ======            === */
	{ "/dev/rmt/tps%dd%dnrv", 4,  0,0x1A, 0,  0,                 0, 1},
	{ "/dev/scsi/sc%dd%dl0", -2,  0,   0, 1,  0,                 0, 1},
	{ "/dev/rmt/tps%dd%d",    4,  0,0x1A, 0,  1,          FTT_RWOC, 1},
	{ "/dev/rmt/tps%dd%dnr",  4,  0,0x1A, 0,  1,                 0, 1},
	{ "/dev/rmt/tps%dd%dv",   4,  0,0x1A, 0,  0,          FTT_RWOC, 1},
	{ "/dev/rmt/tps%dd%dnrv", 4,  0,0x1A, 0,  0,                 0, 1},
        { 0,},
    }},
    {"IRIX+5", "EXB-85", "SCSI", FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/tps%dd%d",  2, IRIXfind, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/tps%dd%dnrv.8500",    1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/tps%dd%dnrv.8500",    1,  0,0x00, 0,  0,                 0, 1},
{ "/dev/scsi/sc%dd%dl0",         -2,  0,   0, 1,  0,                 0, 1},
{ "/dev/rmt/tps%dd%d",            1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnr",          1,  0,0x15, 0,  1,                 0, 1},
{ "/dev/rmt/tps%dd%dv",           1,  0,0x15, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrv",         1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/tps%dd%d.8200",       0,  0,0x14, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnr.8200",     0,  0,0x14, 0,  1,                 0, 1},
{ "/dev/rmt/tps%dd%dv.8200",      0,  0,0x14, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrv.8200",    0,  0,0x14, 0,  0,                 0, 1},
{ "/dev/rmt/tps%dd%d.8500",       1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnr.8500",     1,  0,0x15, 0,  1,                 0, 1},
{ "/dev/rmt/tps%dd%dnrv.8500",    1,  0,0x15, 0,  0,                 0, 0},
{ "/dev/rmt/tps%dd%dv.8500",      1,  0,0x15, 0,  0,          FTT_RWOC, 1},
        { 0,},
    }},
    {"IRIX+5", "EXB-82","SCSI",  FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/tps%dd%d", 2, IRIXfind, {
    /*   string                  den mod hwd pas fxd rewind            sf,1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/tps%dd%dnrv",         0,  0,   0, 0,  0,                 0, 1},
{ "/dev/scsi/sc%dd%dl0",         -2,  0,   0, 1,  0,                 0, 1},
{ "/dev/rmt/tps%dd%dnr",          0,  0,   0, 0,  1,                 0, 1},
{ "/dev/rmt/tps%dd%d",            0,  0,   0, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrv",         0,  0,   0, 0,  0,                 0, 0},
{ "/dev/rmt/tps%dd%dv",           0,  0,   0, 0,  0,          FTT_RWOC, 1},
{ 0,},
    }},
    {"IRIX+4", "EXB-85", "SCSI", FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/tps%dd%d", 2, IRIXfind, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/tps%dd%dnrnsv.8500",  1,  0,   0, 0,  0,                 0, 1},
{ "/dev/scsi/sc%dd%dl0",         -2,  0,   0, 1,  1,                 0, 1},
{ "/dev/rmt/tps%dd%d",            1,  0,0x15, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dns",          1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrns",        1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/tps%dd%dv",           1,  0,0x15, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnsv",         1,  0,0x15, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrnsv",       1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/tps%dd%d.8200",       0,  0,0x14, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dns.8200",     0,  0,0x14, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrns.8200",   0,  0,0x14, 0,  1,                 0, 1},
{ "/dev/rmt/tps%dd%dv.8200",      0,  0,0x14, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnsv.8200",    0,  0,0x14, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrnsv.8200",  0,  0,0x14, 0,  0,                 0, 1},
{ "/dev/rmt/tps%dd%d.8500",       1,  0,0x15, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dns.8500",     1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrns.8500",   1,  0,0x15, 0,  1,                 0, 1},
{ "/dev/rmt/tps%dd%dnrnsv.8500",  1,  0,0x15, 0,  0,                 0, 0},
{ "/dev/rmt/tps%dd%dv.8500",      1,  0,0x15, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnsv.8500",    1,  0,0x15, 0,  0,          FTT_RWOC, 1},
{ 0,},
    }},
    {"IRIX+4", "EXB-82", "SCSI",  FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/tps%dd%d", 2, IRIXfind, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/tps%dd%dnrnsv",       0,  0,   0, 0,  0,                 0, 1},
{ "/dev/scsi/sc%dd%dl0",         -2,  0,   0, 1,  1,                 0, 1},
{ "/dev/rmt/tps%dd%d",            0,  0,   0, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dns",          0,  0,   0, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrns",        0,  0,   0, 0,  0,                 0, 1},
{ "/dev/rmt/tps%dd%dv",           0,  0,   0, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnsv",         0,  0,   0, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/tps%dd%dnrnsv",       0,  0,   0, 0,  0,                 0, 0},
	{ 0,},
    }},
    {"IRIX+5", "DLT", "VME-SCSI", FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/jag%dd%d", 2, IRIXfindVME,{
    /*   string                  den mod hwd pas fxd rewind            ,1st */
    /*   ======                  === === === === === ======            === */
	{ "/dev/rmt/jag%dd%dnrv", 4,  0,0x1A, 0,  0,                 0, 1},
	{ "/dev/scsi/jag%dd%dl0",-2,  0,   0, 1,  0,                 0, 1},
	{ "/dev/rmt/jag%dd%d",    4,  0,0x1A, 0,  1,          FTT_RWOC, 1},
	{ "/dev/rmt/jag%dd%dnr",  4,  0,0x1A, 0,  1,                 0, 1},
	{ "/dev/rmt/jag%dd%dv",   4,  0,0x1A, 0,  0,          FTT_RWOC, 1},
	{ "/dev/rmt/jag%dd%dnrv", 4,  0,0x1A, 0,  0,                 0, 1},
        { 0,},
    }},
    {"IRIX+5", "EXB-85", "VME-SCSI", FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/jag%dd%d", 2, IRIXfindVME,{
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/jag%dd%dnrv.8500",    1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%dnrv.8500",    1,  0,0x00, 0,  0,                 0, 1},
{ "/dev/scsi/jag%dd%dl0",        -2,  0,   0, 1,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d",            1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnr",          1,  0,0x15, 0,  1,                 0, 1},
{ "/dev/rmt/jag%dd%dv",           1,  0,0x15, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrv",         1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d.8200",       0,  0,0x14, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnr.8200",     0,  0,0x14, 0,  1,                 0, 1},
{ "/dev/rmt/jag%dd%dv.8200",      0,  0,0x14, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrv.8200",    0,  0,0x14, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d.8500",       1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnr.8500",     1,  0,0x15, 0,  1,                 0, 1},
{ "/dev/rmt/jag%dd%dnrv.8500",    1,  0,0x15, 0,  0,                 0, 0},
{ "/dev/rmt/jag%dd%dv.8500",      1,  0,0x15, 0,  0,          FTT_RWOC, 1},
        { 0,},
    }},
    {"IRIX+5", "EXB-82","VME-SCSI",  FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/jag%dd%d", 2, IRIXfindVME, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/jag%dd%dnrv",         0,  0,   0, 0,  0,                 0, 1},
{ "/dev/scsi/jag%dd%dl0",        -2,  0,   0, 1,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d",            0,  0,   0, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnr",          0,  0,   0, 0,  1,                 0, 1},
{ "/dev/rmt/jag%dd%dv",           0,  0,   0, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrv",         0,  0,   0, 0,  0,                 0, 0},
{ 0,},
    }},
    {"IRIX+4", "EXB-85", "VME-SCSI", FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/jag%dd%d", 2, IRIXfindVME, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/jag%dd%dnrnsv.8500",  1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d",            1,  0,0x15, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dns",          1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrns",        1,  0,0x15, 0,  1,                 0, 1},
{ "/dev/rmt/jag%dd%dv",           1,  0,0x15, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnsv",         1,  0,0x15, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrnsv",       1,  0,0x15, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d.8200",       0,  0,0x14, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dns.8200",     0,  0,0x14, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrns.8200",   0,  0,0x14, 0,  1,                 0, 1},
{ "/dev/rmt/jag%dd%dv.8200",      0,  0,0x14, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnsv.8200",    0,  0,0x14, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrnsv.8200",  0,  0,0x14, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d.8500",       1,  0,0x15, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dns.8500",     1,  0,0x15, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrns.8500",   1,  0,0x15, 0,  1,                 0, 1},
{ "/dev/rmt/jag%dd%dnrnsv.8500",  1,  0,0x15, 0,  0,                 0, 0},
{ "/dev/rmt/jag%dd%dv.8500",      1,  0,0x15, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnsv.8500",    1,  0,0x15, 0,  0,          FTT_RWOC, 1},
{ 0,},
    }},
    {"IRIX+4", "EXB-82", "VME-SCSI",  FTT_FLAG_ASYNC_REWIND, 
	FTT_OP_GET_STATUS, ftt_trans_table,
	"/dev/rmt/jag%dd%d", 2, IRIXfindVME, {
    /*   string                  den mod hwd pas fxd rewind            1st */
    /*   ======                  === === === === === ======            === */
{ "/dev/rmt/jag%dd%dnrnsv",       0,  0,   0, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%d",            0,  0,   0, 0,  1, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dns",          0,  0,   0, 0,  1,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrns",        0,  0,   0, 0,  0,                 0, 1},
{ "/dev/rmt/jag%dd%dv",           0,  0,   0, 0,  0, FTT_BTSW|FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnsv",         0,  0,   0, 0,  0,          FTT_RWOC, 1},
{ "/dev/rmt/jag%dd%dnrnsv",       0,  0,   0, 0,  0,                 0, 0},
	{ 0,},
    }},
    {0, },
};


ftt_stat_entry ftt_stat_op_tab[] = {
    {"EXB-8200", 
	FTT_DO_TUR|FTT_DO_INQ|FTT_DO_MS|FTT_DO_RS|FTT_DO_EXBRS},

    {"EXB-8500", 
	FTT_DO_TUR|FTT_DO_INQ|FTT_DO_MS|FTT_DO_RS|FTT_DO_EXBRS|
	FTT_DO_SN|FTT_DO_RP},

    {"EXB-8505", 
	FTT_DO_TUR|FTT_DO_INQ|FTT_DO_MS|FTT_DO_RS|FTT_DO_EXBRS|
	FTT_DO_05RS|FTT_DO_SN|FTT_DO_LSRW|FTT_DO_RP},

    {"DLT",      
	FTT_DO_TUR|FTT_DO_INQ|FTT_DO_MS|FTT_DO_RS|FTT_DO_DLTRS|
	FTT_DO_SN|FTT_DO_LSRW|FTT_DO_LSC|FTT_DO_RP},

    {0,0}
};
