#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# $Id$

# try to determine which enstore system the user wants based on his node
# This script is called by the enstore/encp table files.

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

stken=stkensrv2.fnal.gov
d0en=d0ensrv2.fnal.gov
cdfen=cdfensrv2.fnal.gov
rip=rip7.fnal.gov
cachen=$stken
happy=happy.fnal.gov
fndapr=fndapr.fnal.gov
water=131.225.84.1
rain=rain.fnal.gov
woodlawn=woodlawn.fnal.gov
airedale=airedale.fnal.gov
#odyssey=odyssey,fnal,gov
#sirius=sirius
#lancs=192.9.200.103 # THE UK lancaster group on bulk1.ukwork
gccen=gccensrv1.fnal.gov
complain=1

# default for environment variables with a default
ENSTORE_MAIL=enstore-auto@fnal.gov
#if [ `/usr/bin/logname` = 'dcache' ]; then ENSTORE_MAIL=dcache-auto@fnal.gov;fi

case $node in

  stken*|cmspnfs1*|eagpnfs1*)
            ENSTORE_CONFIG_HOST=$stken
	    ENSTORE_CONFIG_FILE=stk.conf
            complain=0
            ;;
  rip*)
	    ENSTORE_MAIL=huangch@fnal.gov
	    ENSTORE_CONFIG_HOST=$rip
	    ENSTORE_CONFIG_FILE=rip.conf
            complain=0
            ;;
  cachen*)
            ENSTORE_CONFIG_HOST=$stken
            ENSTORE_CONFIG_FILE=stk.conf
            complain=0
            ;;
  d0en*)    ENSTORE_CONFIG_HOST=$d0en
	    ENSTORE_CONFIG_FILE=sam.conf
            complain=0
            ;;
  cdfen*)   ENSTORE_CONFIG_HOST=$cdfen
	    ENSTORE_CONFIG_FILE=cdf.conf
            complain=0
            ;;
  *minos*)  ENSTORE_CONFIG_HOST=$stken
	    ENSTORE_CONFIG_FILE=stk.conf
            complain=0
            ;;
  *sam*|*d0*)
            ENSTORE_CONFIG_HOST=$d0en
	    ENSTORE_CONFIG_FILE=sam.conf
            ;;
  *cdf*|*b0*)
	    ENSTORE_CONFIG_HOST=$cdfen
	    ENSTORE_CONFIG_FILE=cdf.conf
            ;;
  happy)    #Sasha Moibenko's Desktop
	    ENSTORE_MAIL=moibenko@fnal.gov
	    ENSTORE_CONFIG_HOST=$happy
	    ENSTORE_CONFIG_FILE=happy.conf
            complain=0
            ;;
  water|rain)
	    #Michael Zalokar's Desktop
	    ENSTORE_MAIL=zalokar@fnal.gov
	    ENSTORE_CONFIG_HOST=$water
	    ENSTORE_CONFIG_FILE=water.conf
            complain=0
            ;;
  fndapr)
	    ENSTORE_MAIL=berman@fnal.gov
	    ENSTORE_CONFIG_HOST=$fndapr
	    ENSTORE_CONFIG_FILE=berman.conf
            complain=0
            ;;
#  odyssey)  complain=0
#            ;;
  woodlawn) #Chih-Hao Huang's Desktop
	    ENSTORE_MAIL=huangch@fnal.gov
            ENSTORE_CONFIG_HOST=$woodlawn
            ENSTORE_CONFIG_FILE=woodlawn.conf
            complain=0
            ;;
  airedale) #Jon Bakken's Desktop
	    ENSTORE_MAIL=bakken@fnal.gov
	    ENSTORE_CONFIG_HOST=$airedale
	    ENSTORE_CONFIG_FILE=airedale.conf
            complain=0
            ;;
#  odyssey)  complain=0
#            ;;
#  sirius)   ENSTORE_CONFIG_HOST=$sirius
#	    ENSTORE_CONFIG_FILE=sirius.conf
#            complain=0
#            ;;
#  lancs)
#	    ENSTORE_CONFIG_HOST=$lancs
#	    ENSTORE_CONFIG_FILE=lancs.conf
#	    ENSTORE_MAIL=enstore
#	    complain=0
#	    ;;
  gccen*)
	    ENSTORE_CONFIG_HOST=$gccen
	    ENSTORE_CONFIG_FILE=gccen.conf
	    complain=0
	    ;;
	    
  *)        ENSTORE_CONFIG_HOST=$stken
	    ENSTORE_CONFIG_FILE=stk.conf
            ;;
  
esac

# ENSTORE_USER_DEFINED_CONFIG_FILE allows user to override default
# If ENSTORE_USER_DEFINED_CONFIG_FILE is set, ENSTORE_CONFIG_FILE will
# be assigned by $ENSTORE_USER_DEFINED_CONFIG_FILE
if [ "${ENSTORE_USER_DEFINED_CONFIG_FILE:-x}" != "x" ]
then
    ENSTORE_CONFIG_FILE=${ENSTORE_USER_DEFINED_CONFIG_FILE}
    # assuming the user who sets ENSTORE_USER_DEFINED_CONFIG_FILE knows
    # what he/she is doing
    complain=0
fi

# ENSTORE_USER_DEFINED_CONFIG_HOST allows user to override default
# If ENSTORE_USER_DEFINED_CONFIG_HOST is set, ENSTORE_CONFIG_HOST will
# be assigned by $ENSTORE_USER_DEFINED_CONFIG_HOST
if [ "${ENSTORE_USER_DEFINED_CONFIG_HOST:-x}" != "x" ]
then
    ENSTORE_CONFIG_HOST=${ENSTORE_USER_DEFINED_CONFIG_HOST}
    # if ENSTORE_USER_DEFINED_CONFIG_FILE is not set, the value for
    # ENSTORE_CONFIG_FILE will be guessed based on the value of
    # $ENSTORE_CONFIG_HOST (same as ${ENSTORE_USER_DEFINED_CONFIG_HOST}
    # for now)
    if [ "${ENSTORE_USER_DEFINED_CONFIG_FILE:-x}" = "x" ]
    then
        case $ENSTORE_CONFIG_HOST in
            stken*)
                ENSTORE_CONFIG_FILE=stk.conf
                ;;
            d0en*)
                ENSTORE_CONFIG_FILE=sam.conf
                ;;
            cdfen*)
                ENSTORE_CONFIG_FILE=cdf.conf
                ;;
            *)
                ENSTORE_CONFIG_FILE=stk.conf
                ;;
        esac
    fi
    complain=0
fi



if [ "${1:-x}" = "x" ]; then
  if [ $complain -eq 1 ]; then
    # note that these warnings go to stderr
    echo "WARNING: based on your node, `uname -n`, ENSTORE_CONFIG_HOST has been set to $ENSTORE_CONFIG_HOST" 1>&2
    echo "WARNING: If this is not correct, either set ENSTORE_CONFIG_HOST by hand or use a qualifier in your setup command!" 1>&2
  fi
  # need to feed this back up to the en*.table file on stdout to set it in the users's environment
  echo $ENSTORE_CONFIG_HOST
elif [ "${1:-x}" = "file" ]; then
  if [ $complain -eq 1 ]; then
    # note that these warnings go to stderr
    echo "WARNING: based on your node, `uname -n`, ENSTORE_CONFIG_FILE has been set to $ENSTORE_CONFIG_FILE" 1>&2
    echo "WARNING: If this is not correct, either set ENSTORE_CONFIG_FILE by hand or use a qualifier in your setup command!" 1>&2
  fi
  # need to feed this back up to the en*.table file on stdout to set it in the users's environment
  echo $ENSTORE_CONFIG_FILE
elif [ "${1:-x}" = "mail" ]; then
  if [ $complain -eq 1 ]; then
    # note that these warnings go to stderr
    echo "WARNING: based on your node, `uname -n`, ENSTORE_MAIL has been set to $ENSTORE_MAIL" 1>&2
    echo "WARNING: If this is not correct, either set ENSTORE_MAIL by hand or use a qualifier in your setup command!" 1>&2
  fi
  # need to feed this back up to the en*.table file on stdout to set it in the users's environment
  echo $ENSTORE_MAIL
fi

