#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# $Id$

# try to determine which enstore system the user wants based on his node
# This script is called by the enstore/encp table files.

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

stken=stkensrv2.fnal.gov
d0en=d0ensrv2.fnal.gov
rip=rip7.fnal.gov
buffalo=buffalo.fnal.gov
happy=happy.fnal.gov
water=water.fnal.gov
airedale=airedale.fnal.gov
sirius=sirius

complain=1

# default for environment variables with a default
ENSTORE_MAIL=enstore-auto@fnal.gov


case $node in

  stken*|rip9|rip10)
            ENSTORE_CONFIG_HOST=$stken
	    ENSTORE_CONFIG_FILE=stk.conf
            complain=0
            ;;
  rip*)
	    ENSTORE_MAIL=enstore@fnal.gov
	    ENSTORE_CONFIG_HOST=$rip
	    ENSTORE_CONFIG_FILE=rip.conf
            complain=0
            ;;
  d0en*)    ENSTORE_CONFIG_HOST=$d0en
	    ENSTORE_CONFIG_FILE=sam.conf
            complain=0
            ;;
  buffalo)  ENSTORE_CONFIG_HOST=$buffalo
	    ENSTORE_CONFIG_FILE=buffalo.conf
            complain=0
            ;;
  sirius)   ENSTORE_CONFIG_HOST=$sirius
	    ENSTORE_CONFIG_FILE=sirius.conf
            complain=0
            ;;
  happy)    ENSTORE_CONFIG_HOST=$happy
	    ENSTORE_CONFIG_FILE=happy.conf
            complain=0
            ;;
  water)    ENSTORE_CONFIG_HOST=$water
	    ENSTORE_CONFIG_FILE=water.conf
            complain=0
            ;;
  airedale) ENSTORE_CONFIG_HOST=$airedale
	    ENSTORE_CONFIG_FILE=airedale.conf
            complain=0
            ;;
  *sam*|*d0*)
            ENSTORE_CONFIG_HOST=$d0en
	    ENSTORE_CONFIG_FILE=sam.conf
            ;;
  *)        ENSTORE_CONFIG_HOST=$stken
	    ENSTORE_CONFIG_FILE=stk.conf
            ;;
esac

if [ "${1:-x}" = "x" ]; then
  if [ $complain -eq 1 ]; then
    # note that these warnings go to stderr
    echo "WARNING: based on your node, `uname -n`, ENSTORE_CONFIG_HOST has been set to $ENSTORE_CONFIG_HOST" 1>&2
    echo "WARNING: If this is not correct, either set ENSTORE_CONFIG_HOST by hand or use a qualifier in your setup command!" 1>&2
  fi
  # need to feed this back up to the en*.table file on stdout to set it in the users's environment
  echo $ENSTORE_CONFIG_HOST
elif [ "${1:-x}" = "file" ]; then
  if [ $complain -eq 1 ]; then
    # note that these warnings go to stderr
    echo "WARNING: based on your node, `uname -n`, ENSTORE_CONFIG_FILE has been set to $ENSTORE_CONFIG_FILE" 1>&2
    echo "WARNING: If this is not correct, either set ENSTORE_CONFIG_FILE by hand or use a qualifier in your setup command!" 1>&2
  fi
  # need to feed this back up to the en*.table file on stdout to set it in the users's environment
  echo $ENSTORE_CONFIG_FILE
elif [ "${1:-x}" = "mail" ]; then
  if [ $complain -eq 1 ]; then
    # note that these warnings go to stderr
    echo "WARNING: based on your node, `uname -n`, ENSTORE_MAIL has been set to $ENSTORE_MAIL" 1>&2
    echo "WARNING: If this is not correct, either set ENSTORE_MAIL by hand or use a qualifier in your setup command!" 1>&2
  fi
  # need to feed this back up to the en*.table file on stdout to set it in the users's environment
  echo $ENSTORE_MAIL
fi

