#!/bin/sh
# generic current script

# find $PROD_DIR
eval PROD_DIR=\$`echo $UPS_PROD_NAME | tr '[a-z]' '[A-Z]'`_DIR

. $PROD_DIR/ups/Version

# make sure we have a products link directory
if cd /usr/local/products/$PROD_NAME 2>/dev/null
then
	# if so, make a current link
	rm -f current
	ln -s $PROD_FLAVOR/$PROD_VERSION current
fi
