PATH="$PATH:${ENSTORE_DIR}/bin"
export PATH

if [ "${PYTHONPATH:-1}" = "1" ]; then
   PYTHONPATH=$ENSTORE_DIR/src:${ENSTORE_DIR}/modules:$LIBTPPY_DIR/lib
else
   PYTHONPATH=${PYTHONPATH}:$ENSTORE_DIR/src:${ENSTORE_DIR}/modules:$LIBTPPY_DIR/lib
fi
export PYTHONPATH

ver=`/bin/ls -d $PYTHON_DIR/lib/python*`
PVER=`basename $ver`
PYTHONINC=$PYTHON_DIR/include/$PVER
export PYTHONINC
PYTHONLIB=$PYTHON_DIR/lib/$PVER
export PYTHONLIB

ENSTORE_CONFIG_FILE=$ENSTORE_DIR/etc/willow.conf
export ENSTORE_CONFIG_FILE

ENSTORE_CONFIG_PORT=7510
export ENSTORE_CONFIG_PORT

ENSTORE_CONFIG_HOST=pcfarm9.fnal.gov
export ENSTORE_CONFIG_HOST

. $ENSTORE_DIR/etc/defaults

. $ENSTORE_DIR/etc/pnfs.sh
