#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# $Id$

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`

if [ "${1:-x}" = "local" ]; then gang=$node; fi

rgang -nn $gang "ls -ld /root/CRON/*ACTIVE         2>&1 |egrep -v 'No such|Permission denied'
                 ls -ld /home/enstore/CRON/*ACTIVE 2>&1 |egrep -v 'No such|Permission denied'
                 ls -ld /home/enstore/MISC/*ACTIVE 2>&1 |egrep -v 'No such|Permission denied'
                 echo
                "

