#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

busy=/home/enstore/ADIC_DRIVE_UTILIZATION

command=${1:-plot}
getnode=d0ensrv4
plotnode=d0ensrv2

now=`date +"%Y-%m-%d:%H:%M:%S"`
Quarter_ago=`date --date "90 days ago" +"%Y-%m-%d:%H:%M:%S"`

case $command in

    get)
        if [ $node = $getnode ] ; then
         dinfo=/tmp/dinfo
         rm -f $dinfo
         dasadmin listd2  >$dinfo
         nM1=`grep "type: M"  $dinfo | grep -vc "volser:   c"`
         nM2=`grep "type: I"  $dinfo | grep -vc "volser:   c"`
         nLTO=`grep "type: 3"  $dinfo | grep -vc "volser:   c"`
         nDLT=`grep "type: E"  $dinfo | grep -vc "volser:   c"`
         aM1=`grep "type: M"  $dinfo | grep -c " UP "`
         aM2=`grep "type: I"  $dinfo | grep -c " UP "`
         aLTO=`grep "type: 3"  $dinfo | grep -c  " UP "`
         aDLT=`grep "type: E"  $dinfo | grep -c  " UP "`
         echo "$now $nM1 $aM1 $nM2 $aM2 $nLTO $aLTO $nDLT $aDLT">>$busy

        else
         echo \"$0 $command\" can only be run on $getnode because that is the where it is setup
        fi
        ;;


    plot)
        if [ $node = $plotnode ] ; then
         enrcp $getnode:$busy $busy
         plotM1=/fnal/ups/prd/www_pages/enstore/M1_Utilization
         plotM2=/fnal/ups/prd/www_pages/enstore/M2_Utilization
         plotLTO=/fnal/ups/prd/www_pages/enstore/LTO_Utilization
         plotDLT=/fnal/ups/prd/www_pages/enstore/DLT_Utilization
         pltcmd=/tmp/adicdu.gnu

         rm -f $pltcmd
         echo "set output \"$plotM1.ps\"
set terminal postscript color solid
set title \"ADIC M1 Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in Use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:2 t \"M1 in use\" w impulses" >$pltcmd
         gnuplot $pltcmd
         convert -rotate 90 $plotM1.ps $plotM1.jpg
	 convert -geometry 120x120 -modulate 80 $plotM1.jpg ${plotM1}_stamp.jpg

         rm -f $pltcmd
         echo "set output \"$plotM2.ps\"
set terminal postscript color solid
set title \"ADIC M2 Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in Use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:4 t \"M2 in use\" w impulses" >$pltcmd
         gnuplot $pltcmd
         convert -rotate 90 $plotM2.ps $plotM2.jpg
	 convert -geometry 120x120 -modulate 80 $plotM2.jpg ${plotM2}_stamp.jpg

         rm -f $pltcmd
         echo "set output \"$plotLTO.ps\"
set terminal postscript color solid
set title \"ADIC LTO Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in Use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:6 t \"LTO in use\" w impulses" >$pltcmd
         gnuplot $pltcmd
         convert -rotate 90 $plotLTO.ps $plotLTO.jpg
	 convert -geometry 120x120  -modulate 80 $plotLTO.jpg ${plotLTO}_stamp.jpg

if /bin/false; then
         rm -f $pltcmd
         echo "set output \"$plotDLT.ps\"
set terminal postscript color solid
set title \"ADIC DLT Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in Use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:8 t \"DLT in use\" w impulses" >$pltcmd
         gnuplot $pltcmd
         convert -rotate 90 $plotDLT.ps $plotDLT.jpg
	 convert -geometry 120x120  -modulate 80 $plotDLT.jpg ${plotDLT}_stamp.jpg
fi


        else
         echo \"$0 $command\" can only be run on $plotnode because that is the only one that has a web server
        fi
        ;;
esac
