#!/bin/sh

BASEPATH=/fnal/ups/prd/www_pages/enstore

if [ `uname -n | grep -c d0ensrv2` -ne 0 ]; then
  BASE=/diska/aml2Shadow/AMU/LOGS-TRC
  DECODED=/diska/aml2-log
  REPORTED=/diska/aml2-report
fi

#set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# if called with no arguments, then assume that we have get the logs first
# and then pass them along for decoding
if [ -z "${1-}" ]; then

   if [ -z "${BASE-}" ]; then
      BASE=/rip8a/enstore/aml2Shadow/AMU/LOGS-TRC
   fi

  #mirror $ENSTORE_DIR/sbin/aml2.mirror
   mirror $ENSTORE_DIR/sbin/aml2.log.mirror
   find $BASE -type f -name "log*" -maxdepth 1 -exec $0 {} \;

# otherwise we need to create a version people can read
# then gzip it to save space - note that most browsers can decode gzip formats
else

    if [ -z "${DECODED-}" ]; then
       DECODED=$BASEPATH/aml2log
    fi
    if [ -z "${REPORTED-}" ]; then
       REPORTED=$BASEPATH/aml2rpt
    fi

    asc=$DECODED/`basename $1`.ascii
    arpt=$REPORTED/`basename $1`.rpt
    thisYear=`date +%Y`
    year=$thisYear  # THIS IS A PROBLEM WHEN THE YEAR ROLLS OVER!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    month=`basename $1 | cut -b6-7`
    HISTORY=history
    zipped=$DECODED/$HISTORY/$year/$month/`basename $1`.ascii.gz
    stash=0
    if [ ! -r $zipped ]; then
      if [ ! -r $asc -o $asc -ot $1 ]; then
         echo $asc
         nice -n 20 $ENSTORE_DIR/sbin/dump_aml2_log.py $1 > $asc
	 nice -n 20 $ENSTORE_DIR/sbin/stataml2log.py $asc $arpt
      fi
    fi
fi
