#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`
case $gang in
  stken) robot="ISD AML/J"
         ;;
   d0en) robot="D0 AML/2"
         ;;
      *) robot="UNKNOWN"
          ;;
esac

set +u
. /usr/local/etc/setups.sh
setup das >/dev/null 2>&1
set -u

volfile=/tmp/ROBOT-VOLUMES-$gang

output=${1:-/dev/tty}
shift
if [ `echo $output | grep -c /dev/` -eq 0 ] ; then 
  rm -f $output
fi

cat << EOF >>$output
<html> <head> <title>$robot Volume Status Page</title> </head>
<body>
<body bgcolor="#ffffff" text=#a0a0ff">
<meta http-equiv="Refresh" content="900">
<h1><center>$robot Volume Fetch Begin: `date`</center><h1>
<hr>
EOF

rm -f $volfile

more=1
nomore="no more data"
while [ $more -ne 0 ]; do
  if [ $more -eq 1 ]; then
     dasadmin qvolsrange "" "" 1000 >$volfile
  else
     dasadmin qvolsrange $first "" 1000 >>$volfile
  fi
  if [ `grep -c "$nomore" $volfile` -ne 0 ]; then break; fi
  more=`expr $more + 1`
  if [ $more -gt 30 ]; then break; fi
  first=`tail -n1 $volfile | awk '{print $2}'` 
done

cat << EOF >>$output
<h1><center>$robot Volume Fetch Done : `date`</center><h1>
<hr>
EOF

#cmd="egrep 'PRF|PRE' $volfile  | egrep -v 'Ejected|DECDLT'"
cmd="egrep volser $volfile"

cat << EOF >>$output
<h1> Tapes in the $robot satisfying: $cmd
<pre>
EOF

eval $cmd >>$output

cat << EOF >>$output
</pre>
<hr>
<h1><center>$robot Volume Status Page Done : `date`</center><h1>
<hr>
</body>
EOF

for remote_copy in $*
do
  if [ `echo $output | grep -c /dev/` -eq 0 -a `echo $remote_copy | grep -c /dev/` -eq 0 ] ; then 
    echo enrcp $output $remote_copy
         enrcp $output $remote_copy
  fi
done
