#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile$  $Revision$

ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`echo $node | cut -c1-4`
if [ "$gang" = "stke" ]; then gang=stken; fi

cd /diskc/enstore/$gang
today=`date +"%Y-%m-%d-%H"`
BACKUP=/pnfs/eagle/${gang}-sys-backups/$today
mkdir $BACKUP
if [ $? -ne 0 ]; then echo "`date` can not mkdir $BACKUP on $node "; exit 1; fi

rc=0
rcf=/tmp/rcf
rm -f $rcf
find . -type f | grep -v old| while read f; do
 file=`echo $f | cut -c3-`;
 echo encp $file $BACKUP/`echo $file | sed -e s%/%-%g`
      encp $file $BACKUP/`echo $file | sed -e s%/%-%g`
 e=$?
 rc=`expr $rc + $e`
 rm -f $rcf
 echo $rc >$rcf
 done
rc=`cat $rcf`
rm -f $rcf
echo "`date` return code is $rc"
exit $rc

