#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# $Id$

# these files and directories need to be deleted when a node boots.

rmdir /root/CRON/*ACTIVE /home/enstore/CRON/*ACTIVE /home/enstore/MISC/*ACTIVE

rm -f /tmp/enstore/*/*pids
rm -f /tmp/enstore/*/*pid
rm -f /tmp/enstore/*/db_checkpoint
rm -f /tmp/enstore/*/db_deadlock
