#!/bin/bash 
##############################################################################
#
# $Id$ 
#
# script that monitors qpidd and starts it if broker is not alive
# must be run as root to have qpidd -c to work
#
##############################################################################
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bail out if environment is not set correctly. 
# Calling 'setup enstore' does not fix it.
if [ "${ENSTORE_DIR:-}" = "" -o "${QPID_DIR:-}" = "" ];
then
   echo "ENSTORE_DIR or QPID_DIR not defined, exiting"
   exit 1
fi

EXE=$QPID_DIR/sbin/qpidd

# run qpidd check command from proper location to see if broker running
out=`${EXE} -c 2>/dev/null`
RC=$?

if [ ${RC} -ne 0 ]
then
    enstore alarm  --raise \
        --client-name CHECK_QPIDD --severity W --root-error "QPIDD GONE" \
        --message "qpidd broker not running, restarting"
    $ENSTORE_DIR/sbin/qpid_broker restart
    exit 1
fi

exit 0
