#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

case `uname` in
        IRIX*) loc=/usr/etc
                ;;
        Linux*) loc=/usr/sbin
                ;;
        *)      loc=/usr/sbin
                echo "UNKNOWN OS - FIX ME"
                exit 1
esac

bang=`echo -e "\041"`
node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`
case $gang in
  stken) pnfson=stkensrv1
          ;;
   d0en) pnfson=d0ensrv1
          ;;
  cdfen) pnfson=cdfensrv1
          ;;
   rip) pnfson=rip6
          ;;
     *) pnfson=UNKNOWN
          ;;
esac


correct_MR="program 100005 version 1 ready and waiting"
correct_NR="program 100003 version 2 ready and waiting"
complain=6
CF=/tmp/pnfs_down
CF_current() { if [ ! -r $CF ]; then CF_set 0 ; fi;  cat $CF; }
CF_set() { rm -fr $CF; echo $1 > $CF ; }
current=`CF_current`

D=`date "+%Y-%m-%d-%H:%M:%S"`
MR=`$loc/rpcinfo -u $pnfson 100005 1 2>&1`
NR=`$loc/rpcinfo -u $pnfson 100003 2 2>&1`

msg1="$D $pnfson  MOUNTD: $MR    NFSD: $NR"

if [ "$correct_MR" != "$MR" -o "$correct_NR" != "$NR" ]; then
        current=`expr $current + 1`
        if [ $current -gt $complain ]; then 
          rc=1
          msg2="PROBLEM WITH PNFS ON $pnfson"
          enstore alarm --raise --severity "A" --root-error "$msg1  $msg2"
          enstore sched --override enstore --saagStatus red
          /usr/bin/Mail -s "$msg1 $msg2" $ENSTORE_MAIL
          current=0
       fi
       rc=0
else
        echo $msg1   # where ever it is running
	current=0
        rc=0
fi

CF_set $current
exit $rc
