#!/bin/sh

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
case $node in
  stken*) gang=stken
          ;;
   d0en*) gang=d0en
          ;;
       *) gang=UNKNOWN
          ;;
esac

farmlet=/usr/local/etc/farmlets/$gang-alla
filebase=/tmp/chip2-

output=${1:-/dev/tty}
if [ `echo $output | grep -c /dev/` -eq 0 ] ; then 
  rm -f $output
fi

cat << EOF >>$output
<html> <head> <title>$gang Cluster Chip2 Status Page</title> </head>
<body>
<body bgcolor="#ffffff" text=#a0a0ff">
<meta http-equiv="Refresh" content="900">
<h1><center>$gang Cluster Chip2 Fetch Begin: `date`</center><h1>
<hr>
EOF

if [ -z "${2-}" ] ; then
  for i in `cat $farmlet`; do
   date > $filebase$i
   rsh $i 'killall -9 /opt/chip2/chip2; /opt/chip2/chip2 ' >> $filebase$i &
  done
  #wait
  sleep 30 # wait doesn't work if rsh fails ???
fi

cat << EOF >>$output
<h1><center>$gang Cluster Chip2 Fetch Done : `date`</center><h1>
<hr>
EOF

cat << EOF >>$output
<table bgcolor="#dfdff0" nosave >
<tr><td align=center><b>Item</b></td>
EOF

for i in `cat $farmlet`; do
  cat << EOF >>$output
<h2><center>Chip2 Log for node $i</center><h2>
<pre>
EOF
  cat $filebase$i >> $output
cat << EOF >>$output
</pre>
<hr>
EOF
done

######################################################################################Q

cat <<EOF >>$output
<h1><center>$gang Cluster Chip2 Write Done : `date`</center><h1>
<hr>
</body>
EOF

