#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# the first parameter is the base.  if not entered, use the default
if [ $# -ge 1 ] ; 
then
    base=$1;
    shift;
else
    base=/tmp/doesnot/exist
fi

convert=/usr/bin/X11/convert

if [ `uname -n | grep -c d0ensrv2` -ne 0 ]; then
  base=/diska/CRONS
fi

if [ ! -d $base ]; then
  echo $base does not exist
  exit 1
fi

cd $base

lastweek=`date -d '1 week ago' +'%Y-%m-%d:00:01'`
tomorrow=`date -d '1 day' +'%Y-%m-%d:00:01'`

for i in *; do
  echo $i ..............................................
  cd $base/$i
  rm -f *HISTOGRAM  >/dev/null 2>&1
  rm -f *.pbm  >/dev/null 2>&1
  rcp $i:/root/CRON/*HISTOGRAM . >/dev/null 2>&1
  rcp $i:/home/enstore/CRON/*HISTOGRAM .  >/dev/null 2>&1
  for j in *HISTOGRAM; do
     if [ "$j" = "*HISTOGRAM" ]; then break; fi
     f=`basename $j |sed -e 's/HISTOGRAM//'`
     echo generating plot for $i/$f
     file=`mktemp /tmp/cronplot.XXXXXXXX`
     title=$i/$f
     echo "
set term pbm medium color
set output '$f.pbm'
set xlabel 'Date'
set timefmt '%Y-%m-%d:%H:%M:'
set xdata time
set xrange ['$lastweek' :'$tomorrow']
set yrange [-5:15]
set grid
#set format x '%m-%d'
plot '$j' using 1:2 t '$title' with points
" >> $file
     gnuplot $file
     rm $file
     $convert $f.pbm $f.jpg
     $convert -geometry 120x120 -modulate -20 $f.pbm $f_stamp.jpg
     $convert $f.pbm $f.ps
     rm $f.pbm
  done
  rm -f *HISTOGRAM  >/dev/null 2>&1
done
