#!/bin/sh

#Dump the cleaning tape information to a cleaning report.

inventory_dir=`enstore conf --show crons html_dir`/tape_inventory
if [ ! -d $inventory_dir ]; then
    echo Inventory directory $inventory_dir not found.
    exit 1
fi
output_file=$inventory_dir/CLEANING
temp_file=$output_file.tmp

#If we write to a temp file, and swap in it when we are done, there will
# not any time when the page is empty becuase the scipt is still writing
# the file.
rm -f $temp_file

#Make sure we know how up-to-date this is.
echo -e Cleaning Report: `date` "\n" | tee $temp_file

#Loop over all the media changers (remember to delete the header line).
enstore conf --list-media-changers | sed '1d' |
while read line; do
    mc=`echo $line | awk '{print $1}'`

    #Skip Manual and RDD (aka null) media changers.
    echo $line | egrep "Manual|RDD" > /dev/null 2> /dev/null
    if [ $? -eq 0 ]; then
        continue
    fi

    #Get the name of the tape library.
    tape_library=`enstore conf --show $mc tape_library 2> /dev/null`
    if [ $? -ne 0 ]; then
        #Use the entire line from the --list-media-changers command if
	# the tape_library was not found in the media_changer configuration.
        tape_library=$line
    fi

    #Write out the cleaning information.
    echo -e "Tape Library:" $tape_library "\n" | tee -a $temp_file
    enstore media --list-clean $mc | tee -a $temp_file
    echo -e "\n" | tee -a $temp_file
done

mv $temp_file $output_file
