#!/bin/bash

if [ "`whoami`" != 'root' ]
then
    echo You need to run this script as user "root"
    exit 1
fi

PATH=/usr/sbin:$PATH

export PYTHON_DIR=`rpm -ql Python-enstore | head -1`
export ENSTORE_DIR=`rpm -ql enstore_sa | head -1`
export PYTHONINC=`ls -d ${PYTHON_DIR}/include/python*`
export PYTHONLIB=`ls -d ${PYTHON_DIR}/lib/python*`
export PATH=${PYTHON_DIR}/bin:${PATH}
set PYTHONPATH="./"
for p in ${ENSTORE_DIR}/src \
	 ${ENSTORE_DIR}/modules \
	 ${ENSTORE_DIR}/HTMLgen 	
do	
	PYTHONPATH=${PYTHONPATH}:${p}
done

export PYTHONPATH

chmod +x web_server.py 
chmod +x make_enstore_system.py 

./web_server.py --install

if [ $? != 0 ];
then
	exit 1 
fi



./make_enstore_system.py 

if [ $? != 0 ];
then
	exit 1 
fi

/sbin/chkconfig httpd on
/sbin/service httpd start 

exit 0 
