#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

. /fnal/ups/etc/setups.sh
setup ipmi
$IPMI_DIR/selread>>/SEL
$IPMI_DIR/selclear
