#!/usr/bin/env python

# $Id$

import sys
import emass_log
import time


if __name__=="__main__":
    robot = "adic2.fnal.gov"
    argc=len(sys.argv)
    if argc==1:
        year, month, day = time.localtime(time.time())[:3]
    elif argc in (2,3):
        month, day = map(int, sys.argv[:2])
        if argc==3:
            robot = sys.argv[2]
    else:
        print "Usage: %s [month day [robot]]"
        print "  fetches and dumps log file for robot (default adic2) on"
        print "  specified day (default today)"
        sys.exit(-1)
    emass_log.dump_log_file(robot, month, day)
        
        
        

