#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
# this is cheap argument processing. Must be in this order when checking. I want it cheap!
if [ "${1:-}" = "-c" ] ; then CHECK=1; shift; else CHECK=0; fi
if [ "${1:-}" = "-9" ] ; then SIG='-9';shift; else SIG=' '; fi

if [ -z "${1:-}" ]; then echo 'USUAGE: $0 [-c -9] \"egrep search string for kill\"'; exit 2; fi
lookfor="${1}"

PS="/bin/ps"
ECHO="/bin/echo"
EGREP="/bin/egrep"
KILL="/bin/kill"
SLEEP="/bin/sleep"
SLEEPTIME=3

$PS axwww | $EGREP "$lookfor"|$EGREP -v "grep|ekill"| while read pid line; do
    $ECHO killing $SIG $pid $line
    if [ $CHECK -eq 0 ]; then echo -n $KILL $SIG $pid; $KILL $SIG $pid;
        if [ $? -ne 0 ]; then echo ' FAILURE'; else echo ' OK'; fi
    fi
done;

if [ $CHECK -eq 0 ]; then
    $SLEEP $SLEEPTIME

    x="`$PS axwww | $EGREP "$lookfor"|$EGREP -v 'grep|ekill'`"
    if [ `echo "$x" | wc -w` -eq 0 ]; then
        x=1
        #$ECHO "None survived after kill"
    else
        $ECHO
        $ECHO "These survived after the kill:"
        $ECHO "$x"
   fi
fi
