#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# process inputs
if [ $# -lt 2 ]; then
   # we need at least the node name and the rsh string
   set +xv
   exit 1
fi

# constants
krbdir="/usr/krb5/bin"
defaultDomain=".fnal.gov"

# if we are a kerberized system, we need to do some pre rsh stuff.
# if not, just do a normal rsh

if [ -d $krbdir ]; then
   # we are kerberized

   # get some values
   user=`whoami`
   host=`uname -n`

   # we need the full domain name, if no domain is there, add default one on
   if expr $host : '.*\.' >/dev/null;then 
      thisHost=$host;
   else 
      thisHost=${host}${defaultDomain};
   fi

   if [ "$user" = "root" ]; then
      # the user is root
      ${krbdir}/kinit -k host/${thisHost}
      ${krbdir}/rsh -f "$@"
      # if got an error, maybe the remote node is not kerberized and does not
      # accept the -f flag. try rsh without it.
      if [ $? -eq 1 ]; then ${krbdir}/rsh "$@"; fi
      ${krbdir}/kdestroy

   elif [ "$user" = "enstore" ]; then
      # the user is enstore
      ${krbdir}/kinit -k -t /local/ups/kt/enstorekt enstore/cd/${thisHost}
      ${krbdir}/rsh "$@"

   else
      # this is someone else
      KRB5CCNAME=/tmp/krb5cc_myjob_$$;export KRB5CCNAME
      ${krbdir}/kcron
      ${krbdir}/rsh -f "$@"
      # if got an error, maybe the remote node is not kerberized and does not
      # accept the -f flag. try rsh without it.
      if [ $? -eq 1 ]; then ${krbdir}/rsh "$@"; fi
      ${krbdir}/kdestroy
   fi

else
   # we are not kerberized
   rsh "$@"
fi

set +xv