#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile$  $Revision$
# a file to do a ps on different OS's and check for Enstore-like programs

if [ $# = 0 ]; 
then 
   p=" ";
else
   p=$@;
fi

case `uname` in
  Linux*)
        x=`ps axuww   $p`
        ;;
  OSF1*)
        x=`ps  axguww $p`
        ;;
  SunOS*)
        x=`ps -ef     $p`
        ;;
  IRIX*)
        x=`ps -ef     $p`
        ;;
      *)
        x=`ps -ef     $p`
        ;;
esac

echo "$x" | sort | egrep -v 'EPS| egrep | sort | ps |bash| tail | xnetload | tee '| egrep 'python|enstore|encp|reader|writer|dasadmin|mt |db_|dbserver'
