#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# bin/$RCSfile$  $Revision$
# a file to do a ps on different OS's and check for Enstore-like programs

if [ $# = 0 ]; 
then 
   p=" "
   returnpid=0
else
   if [ "$1" != "returnpid" ]; then
     p="$@"
     returnpid=0
   else
     p=" "
     returnpid=1
     lookfor=${2-:enstore}
   fi    
fi

case `uname` in
  Linux*)
        x=`ps axuww   $p`
        ;;
  OSF1*)
        x=`ps  axguww $p`
        ;;
  SunOS*)
        x=`ps -ef     $p`
        ;;
  IRIX*)
        x=`ps -ef     $p`
        ;;
      *)
        x=`ps -ef     $p`
        ;;
esac

if [ $returnpid -eq 0 ]; then
  echo "$x" | sort | egrep -v 'EPS| egrep | sort | ps |bash| tail | xnetload | tee '| egrep 'python|enstore|encp|reader|writer|dasadmin|mt |db_|dbserver'
else
  psline=`echo "$x" | grep $lookfor | grep -v grep | grep -v returnpid | grep \`whoami\``
  # is the pid always the 2nd field???????
  # what if there is more than one process, this only returns the 1st!
  pid=`echo $psline | cut -f2 -d' '` # no quotes arounds $psline removes spaces
  if [ "$pid" != ""  ]; then 
    echo $pid
  else 
    echo -1
  fi
fi

