#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# check/fix the eth0 and eth1 lines


eth-info() { interface=${1-0}
             f=/tmp/eth$interface
             rm -f $f $f.err
             ifconfig eth$interface 2>${f}.err >$f
           }

eth-present() { interface=${1-0}
                if [ `grep -c 'Device not found' /tmp/eth${interface}.err` -eq 0 ]; then
                   /bin/true
                else
                   /bin/false
                fi }

eth-running() { interface=${1-0}
                if [ `grep -c RUNNING /tmp/eth$interface` -ne 0 ]; then
                   /bin/true
                else
                   /bin/false
                fi }

eth-check()   { interface=${1-0}
                eth-info $interface
                if eth-present $interface; then
                   #echo Interface eth$interface present
                   if eth-running $interface; then
                      echo Interface eth$interface running
                      ok=1
                   else
                      (cd /etc/sysconfig/network-scripts; ./ifdown eth$interface; sleep 1; ./ifup eth$interface)
                      echo Interface eth$interface restarted
                      ok=0
                   fi
                 else
                   echo 'Interface eth$interface not found'
                   ok=1
                 fi
                 if [ $ok -eq 1 ]; then
                    /bin/true
                 else
                    /bin/false
                 fi }
estat=0

case "$1" in

  stop) echo
        ;;

  start|*)
        for interface in 0 1; do
          if ! eth-check $interface; then
             eth-check $interface
             rc=$?
             estat=`expr $estat \| $rc`
          fi
        done
        ;;

esac

exit $estat
