#!/bin/sh
set -u  # force better programming and ability to use check for not set

if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# this is cheap argument processing. Must be in this order when checking.
if [ "${1:-}" = "-a" ] ; then ALARM=1;       shift; else ALARM=0;        fi
if [ "${1:-}" = "-f" ] ; then FIX=/bin/true; shift; else FIX=/bin/false; fi

set +u
. /usr/local/etc/setups.sh
setup enstore
set -u

FIXIT="/usr/bin/rsync -e /home/enstore/enstore/sbin/enrsh -I -clpogtx --blocking-io"
CHECK="/usr/bin/rsync -e /home/enstore/enstore/sbin/enrsh -I -clpogtx --blocking-io --dry-run --stats"

# $Id$

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`
if [ "$gang" = "ripe" ]; then  basenode=rip2; else basenode=${gang}srv1; fi

if $FIX; then
    $FIXIT    d0ensrv1:/usr/local/etc/farmlets/d0en*	/usr/local/etc/farmlets/
    $FIXIT   stkensrv1:/usr/local/etc/farmlets/stken*	/usr/local/etc/farmlets/
    $FIXIT   cdfensrv1:/usr/local/etc/farmlets/cdfen*	/usr/local/etc/farmlets/
    $FIXIT ${basenode}:/usr/local/etc/farmlets/enstore* /usr/local/etc/farmlets/
fi

NSAM=9999
NSTK=9999
NCDF=9999
NENS=9999

SAM="`$CHECK    d0ensrv1:/usr/local/etc/farmlets/d0en*    /usr/local/etc/farmlets/ 2>/dev/null`"
STK="`$CHECK   stkensrv1:/usr/local/etc/farmlets/stken*   /usr/local/etc/farmlets/ 2>/dev/null`"
CDF="`$CHECK   cdfensrv1:/usr/local/etc/farmlets/cdfen*   /usr/local/etc/farmlets/ 2>/dev/null`"
ENS="`$CHECK ${basenode}:/usr/local/etc/farmlets/enstore* /usr/local/etc/farmlets/ 2>/dev/null`"

NSAM=`echo "$SAM"|awk '/Number of files transferred:/ {print $NF}'`
NSTK=`echo "$STK"|awk '/Number of files transferred:/ {print $NF}'`
NCDF=`echo "$CDF"|awk '/Number of files transferred:/ {print $NF}'`
NENS=`echo "$ENS"|awk '/Number of files transferred:/ {print $NF}'`

#if [ -z "$NSAM" -o -z "$NSTK" -o -z "$NCDF" -o -z "$NENS" ]; then
#    enstore alarm --raise --severity "A" --root-error "farmlet kerberos trouble"
#    /usr/bin/Mail -s "$node farmlet kerberos trouble" bakken berman < /dev/null
#fi

if [ $NSAM != 0 ]; then echo "$SAM"; fi
if [ $NSTK != 0 ]; then echo "$STK"; fi
if [ $NCDF != 0 ]; then echo "$CDF"; fi
if [ $NENS != 0 ]; then echo "$ENS"; fi

rc=0

if [ $NSAM != 0 -o  $NSTK != 0 -o $NCDF != 0 -o $NENS != 0 ]; then
    msg="`date` BAD CONFIGURATION: Farmlet mismatch NSAM=$NSAM NSTK=$NSTK NCDF=$NCDF NENS=$NENS"
    echo $msg
    if [ $ALARM -eq 1 ]; then
       enstore alarm --raise --severity "A" --root-error "$msg"
    fi
    rc=1
else
    echo "Farmlets match, ok"
fi

# commented out for now because of Linux version incompatibilities (dmb 11/18/03)

## now check the cron.x jobs and make sure they match, too
#for f in /etc/cron.*; do
#  CHK="`$CHECK ${basenode}:$f/ $f/ 2>/dev/null`"
#  NCHK=`echo "$CHK"|awk '/Number of files transferred:/ {print $NF}'`
#  if [ $NCHK != 0 ]; then echo $f "$CHK"
#    msg="`date` BAD CONFIGURATION: Directory $f NCHK=$NCHK"
#    echo $msg
#    if [ $ALARM -eq 1 ]; then
#       enstore alarm --raise --severity "A" --root-error "$msg"
#    fi
#    rc=1
#  else
#    echo "Directory $f, ok"
#  fi
#done

exit $rc
