#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# $Id$

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

case $node in

  stken*|rip9|rip10*|d0enmvr4a|d0enmvr7a|cdfenmvr1a|cdfenmvr2a|cdfenmvr3a|cdfenmvr4a|cdfenmvr5a|cdfenmvr6a)
	gang=stken
        ;;
  rip*|cachen*)
        gang=rip
        ;;
  d0en*)
        gang=d0en
        ;;
  cdfen*)
	gang=cdfen
        ;;
  *)
	gang=UNKNOWN
        ;;
esac

echo $gang
