#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

. /usr/local/etc/setups.sh
setup remedy_api
if [ "$?" = "1" ];
then
	# no product found
	setup enstore
	echo "enstore alarm --raise --root_error 'remedy_api product missing or not current' --severity E"|at now+1min
else
	# make sure we have enough inputs, either 4 or 10
	if [ "$#" = "4" ];
	then
		$REMEDY_API_DIR/bin/create_entry $1 $2 $3 $4
	elif [ "$#" = "10" ];
	then
		$REMEDY_API_DIR/bin/create_entry "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
	else
		setup enstore
		enstore alarm --raise --root_error "generate_ticket invalid parameters" --message "expected 4 or 10 parameters and found $#" --severity E&
	fi
fi
