#!/bin/sh
set -u
if [ "${1:-}" = "-x" ]; then set -xv; shift; fi

# assume we are talking to the remedy server specified in the following line
remedy_server="csdserver"

# the number of arguments (in addition to the remedy server)
nargs=9

# make sure we have the right number of arguments to this script
if [ "$#" = "$nargs" ]
then
	~enstore/enstore/helpDesk/fliptabTicket $remedy_server "$@"
else
	echo "expected $nargs arguments and found $#"
fi
