#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`

F=/fnal/ups/prd/www_pages/enstore/CONSOLES.html
output=/tmp/CONSOLES.html
if [ `echo $output | grep -c /dev/` -eq 0 ] ; then 
  rm -f $output
fi

cat << EOF >>$output

<html> <head> <title>$gang Cluster Console Log Page</title> </head>
<body>
<meta http-equiv="Refresh" content="900">
<body bgcolor="#ffffff" text=#a0a0ff">
<h1><center>$gang Cluster Console LOG  Fetch Begin: `date`</center><h1>
EOF

for i in 3 5; do 
  enrsh ${gang}srv$i "find /var/log/conserver -type f |egrep -v 'bios|tbd|tdb'  | sort | xargs tail -n 25" >>$output
done

cat <<EOF >>$output
<p>
<hr>
<h1><center>$gang Cluster Console Log Write Done : `date`</center><h1>
</body>
EOF

rm -f $F
sed -e "s@==>@</pre><p><hr><h2>@g" -e "s@<==@</h2><pre>@g" -e "s@@@g" $output > $F
