#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# sbin/$RCSfile$  $Revision$

# Usage: log-stash [log_directory] [aml2_log_directory] [aml2_log_reports] \
#	[ratekeeper_log_directory]

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`

here=`pwd`
thisYear=`date +%Y`
thisMonth=`date +%m`
thisDay=`date +%d`


# let's start with the logs that enstore creates
if [ -z "${1-}" ] ; then
  if [ `uname -n | grep -c ${gang}srv2` -ne 0 ]; then
    LOGS=/diska/enstore-log
  else
    LOGS=/fnal/ups/prd/www_pages/enstore/log
  fi
else
  LOGS=$1
fi

cd $LOGS

HISTORY=history
if ! [ -d $HISTORY ]; then
   mkdir $HISTORY
fi

logfiles=`ls -1 LOG-*`
for log in $logfiles; do
  year=` echo $log | cut -f2 -d-`
  month=`echo $log | cut -f3 -d-`
  day=`  echo $log | cut -f4 -d-`
  stash=0
  if [ $year  -lt $thisYear  ]; then stash=1;fi
  if [ $month -lt $thisMonth ]; then stash=1;fi
  if [ $stash -eq 0 ]; then continue; fi
  mkdir -p $HISTORY/$year/$month
  mv $log $HISTORY/$year/$month
done

# also get rid of the extra log files.  these are copies
# of lines in the LOG files, so just delete them.
for prefix in ALARM ENCPS EVRLY LMQADDS MOUNTS; do
    files=`ls -1 $prefix-* 2>/dev/null`
    for log in $files; do
      year=` echo $log | cut -f2 -d-`
      month=`echo $log | cut -f3 -d-`
      smash=0
      if [ $year  -lt $thisYear  ]; then smash=1;fi
      if [ $month -lt $thisMonth ]; then smash=1;fi
      if [ $smash -eq 1 ]; then rm $log; fi
    done
done

cd $HISTORY
find . -type f -name "LOG*" -exec gzip {} \; 2>/dev/null


# now do it again, but this time for the aml2 robot logs
if [ -z "${2-}" ] ; then
  if [ `uname -n | grep -c ${gang}srv2` -ne 0 ]; then
    LOGS=/diska/aml2-log
    RPTS=/diska/aml2-report
  else
    LOGS=/fnal/ups/prd/www_pages/enstore/aml2log
    RPTS=/fnal/ups/prd/www_pages/enstore/aml2rpt
  fi
else
  LOGS=$2
  if [ -z "${3-}" ] ; then
    RPTS=/junk/doesnot/exist
  else
    RPTS=$3
  fi
fi

cd $LOGS

HISTORY=history
if ! [ -d $HISTORY ]; then
   mkdir $HISTORY
fi

logfiles=`ls -1 log*.ascii 2>/dev/null`
for log in $logfiles; do
  last_line="`tail -n 1 $log`"
  year=` echo $last_line | cut -f1 -d-`
  month=`echo $last_line | cut -f2 -d-`
  day=`  echo $last_line | cut -f3 -d-|cut -f1 -d\ `
  stash=0
  if [ $year  -lt $thisYear  ]; then stash=1;fi
  if [ $month -lt $thisMonth ]; then stash=1;fi
  if [ $stash -eq 0 ]; then continue; fi
  mkdir -p $HISTORY/$year/$month
  # cp the file, don't mv it since another cron job will just go get it again.
  cp $log $HISTORY/$year/$month
done

cd $HISTORY
find . -type f -name "log*.ascii" -exec gzip {} \; 2>/dev/null
# if the .gz file already exists, we end up with a ascii file laying around 
#    just delete these files.
find . -type f -name "log*.ascii" -exec rm {} \; 2>/dev/null

if [ -d $RPTS ]; then
  cd $RPTS
  find . -name "*.rpt" -daystart -mtime +14 -exec rm -fr {} \;
fi

cd $here



# now do it again, but this time for the ratekeeper logs
if [ -z "${4-}" ] ; then
  if [ `uname -n | grep -c ${gang}srv2` -ne 0 ]; then
    LOGS=/diska/ratekeeper
  else
    LOGS=/fnal/ups/prd/www_pages/enstore/ratekeeper
  fi
else
  LOGS=$4
fi

cd $LOGS

HISTORY=history
if ! [ -d $HISTORY ]; then
   mkdir $HISTORY
fi

logfiles=`ls -1 *RATES* 2>/dev/null`
for log in $logfiles; do
  last_line="`tail -n 1 $log`"
  year=` echo $last_line | cut -f3 -d-|cut -f1 -d\ `
  month=`echo $last_line | cut -f1 -d-`
  day=`  echo $last_line | cut -f2 -d-`
  stash=0
  if [ $year  -lt $thisYear  ]; then stash=1;fi
  if [ $month -lt $thisMonth ]; then stash=1;fi
  if [ $stash -eq 0 ]; then continue; fi
  mkdir -p $HISTORY/$year/$month
  mv $log $HISTORY/$year/$month
done

cd $HISTORY
find . -type f -not -name "*.gz" -and -name "*RATES*" -exec gzip -f {} \; 2>/dev/null
# if the .gz file already exists, we end up with a ascii file laying around 
#    just delete these files.
find . -type f -not -name "*.gz" -and -name "*RATES*" -exec rm {} \; 2>/dev/null

cd $here
