#!/bin/sh

if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

lastNhours=`date --date "48 hours ago" +"%Y-%m-%d:%H"`
now=`date +"%Y-%m-%d:%H:%M:%S"`

python /home/enstore/enstore/src/plotter.py --sg --output_dir=/local/ups/prd/www_pages/enstore --start_time $lastNhours

cp /local/ups/prd/www_pages/enstore/enplot_sg.ps /diska/enstore-log/enplot_sg/enplot_sg-$now.ps
