#! /bin/sh

#Note: $$ is the current pid.  This should help with uniquenes.
file=/tmp/all_mount_points_$$

mount | grep "/pnfs" | grep -v "/pnfs/fs" | awk '{print $3}' | sort | uniq > $file

if [ ! -s $file ]; then
	#In case we didn't find any /pnfs/xyz mount look for a /pnfs/fs/usr/
	# mount point.
	admin_mounts=`mount | grep "/pnfs/fs" | awk '{print $3}' | sort | uniq`
	pnfs_fs_usr_dir=`echo $admin_mounts | sed 's:$:/usr/:'`
	possible_entries=`ls $pnfs_fs_usr_dir | sed "s:^:$pnfs_fs_usr_dir:"`
	for item in $possible_entries; do
		if [ `basename $item` == "dcache_trash_bin" ]; then
			continue  #Skip the dcache_trash_bin directory.
		fi
		if [ -d $item ]; then
			echo $item  #Skip non-directories.
		fi
	done > $file
fi

cat $file
rm $file
