#!/bin/sh

# $Id $

#Make the VOLUMES and NOACCESS tape inventory pages.

set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

#First obtain the directory to write the output.
inventory_dir=`enstore conf --show crons html_dir`/tape_inventory
if [ ! -d $inventory_dir ]; then
    echo Inventory directory $inventory_dir not found.
    exit 1
fi


#Get our variables for VOLUMES filenames.
outfile_volumes=$inventory_dir/VOLUMES
outfile_volumes_temp=${outfile_volumes}.tmp
#rm -f $outfile_volumes

#Output the data to the VOLUMES temp file.
echo `date` > $outfile_volumes_temp 2>&1
echo >> $outfile_volumes_temp 2>&1
enstore info --vols >> $outfile_volumes_temp 2>&1
echo >> $outfile_volumes_temp 2>&1
echo `date` >> $outfile_volumes_temp 2>&1

#Make the temp file the real VOLUMES file.
mv $outfile_volumes_temp $outfile_volumes



#Get our variables for NOACCESS filenames.
outfile_noaccess=$inventory_dir/NOACCESS
outfile_noaccess_temp=${outfile_noaccess}.temp
#rm -f $outfile_noaccess

#Output the data to the NOACCESS temp file.
echo `date` > $outfile_noaccess_temp 2>&1
echo >> $outfile_noaccess_temp 2>&1
egrep "NOACCESS|NOTALLOWED" $outfile_volumes | grep -v 'migrated' >> $outfile_noaccess_temp 2>&1
echo >> $outfile_noaccess_temp 2>&1
echo `date` >> $outfile_noaccess_temp 2>&1

#Make the temp file the real NOACCESS file.
mv $outfile_noaccess_temp $outfile_noaccess
