#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

out=/fnal/ups/prd/www_pages/enstore/tape_inventory/VOLUMES
rm -f $out

echo `date` >$out 2>&1
echo >> $out 2>&1
enstore info --vols >> $out 2>&1
echo >> $out 2>&1
echo `date` >>$out 2>&1

out2=/fnal/ups/prd/www_pages/enstore/tape_inventory/NOACCESS
rm -f $out2

echo `date` >$out2 2>&1
echo >> $out2 2>&1
grep \(NO $out | grep -v 'migrated' >> $out2 2>&1
echo >> $out2 2>&1
echo `date` >>$out2 2>&1

