#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

n=`uname -n`
r=`uname -r`
v=`uname -v`

#b=bogo		We could flag this if the count is 1 or 3
b=`awk '/bogo/ {printf "%.0f ", $NF}' /proc/cpuinfo`

#fm=free memory
#tm=total memory
tm=`awk '/^MemTotal:/ {printf "%.0f", $2/1024}' /proc/meminfo`
fm=`awk '/^MemFree:/  {printf "%.0f", $2/1024}' /proc/meminfo`
if [ -z "$tm" -a -z "$fm" ]; then
    # Linux 2.4 and earlier kernels did this differently
    tm=`awk '/^Mem:/ {printf "%.0f", $2/1024/1024}' /proc/meminfo`
    fm=`awk '/^Mem:/ {printf "%.0f", $4/1024/1024}' /proc/meminfo`
fi

#fs=free swap
#ts=total swap
ts=`awk '/^SwapTotal:/ {printf "%.0f", $2/1024}' /proc/meminfo`
fs=`awk '/^SwapFree:/  {printf "%.0f", $2/1024}' /proc/meminfo`
if [ -z "$ts" -a -z "$fs" ]; then
    # Linux 2.4 and earlier kernels did this differently
    ts=`awk '/^Swap:/ {printf "%.0f", $2/1024/1024}' /proc/meminfo`
    fs=`awk '/^Swap:/ {printf "%.0f", $4/1024/1024}' /proc/meminfo`
fi

upt=`uptime`
#echo $upt

tod=`echo $upt | sed -e 's/ up.*//'`
#echo $tod

up=`echo $upt | sed -e 's/.*up //' -e 's/, [0-9]* user.*//'`
#echo $up

nu=`echo $upt | sed -e 's/.* \([0-9]*\) user.*/\1/'`
#echo $nu

ldav=`echo $upt | sed -e 's/.*load average://'`
#echo $ldav

black=#000000
white=#FFFFFF

red=#FF0000
blue=#0000FF
green=#00FF00

magenta=#FF00FF
cyan=#00FFFF
yellow=#FFFF00

silver=#C0C0C0
coral=#FF7F50
teal=#008080
turquoise=#40E0D0
navy=#000080

if [ -r /PRODUCTION ]; then
   color=$blue
   P="YES"
else
   color=$teal
   P="no"
fi

echo "<td align=center><font color=\"$color\">$n</font></td>"
echo "<td align=center><font color=\"$color\">$P</font></td>"
echo "<td align=center><font color=\"$color\">$b</font></td>"
echo "<td align=center><font color=\"$color\">$fm/$tm</font></td>"
echo "<td align=center><font color=\"$color\">$fs/$ts</font></td>"
echo "<td align=center><font color=\"$color\">$tod</font></td>"
echo "<td align=center><font color=\"$color\">$up</font></td>"
echo "<td align=center><font color=\"$color\">$nu</font></td>"
echo "<td align=center><font color=\"$color\">$ldav</font></td>"
echo "<td align=center><font color=\"$color\">$r</font></td>"
echo "<td align=center><font color=\"$color\">$v</font></td>"
