#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

n=`uname -n`
r=`uname -r`
v=`uname -v`

#b="bogo:"
b=`awk '/bogo/ {printf "%.0f ", $NF}' /proc/cpuinfo`

#f=free memory
#t=total memory
t=`awk '/^MemTotal:/ {printf "%.0f", $2/1024}' /proc/meminfo`
f=`awk '/^MemFree:/  {printf "%.0f", $2/1024}' /proc/meminfo`
if [ -z "$t" -a -z "$f" ]; then
    # Linux 2.4 kernels did this differently
    t=`awk '/^Mem:/ {printf "%.0f", $2/1024/1024}' /proc/meminfo`
    f=`awk '/^Mem:/ {printf "%.0f", $4/1024/1024}' /proc/meminfo`
fi

upt=`uptime`
#echo $upt

tim=`echo $upt | sed -e 's/ up.*//'`
#echo $tim

up=`echo $upt | sed -e 's/.*up //' -e 's/, [0-9]* user.*//'`
#echo $up

nu=`echo $upt | sed -e 's/.* \([0-9]*\) user.*/\1/'`
#echo $nu

ldav=`echo $upt | sed -e 's/.*load average://'`
#echo $ldav


black=#000000
white=#FFFFFF

red=#FF0000
blue=#0000FF
green=#00FF00

magenta=#FF00FF
cyan=#00FFFF
yellow=#FFFF00

silver=#C0C0C0
coral=#FF7F50
teal=#008080
turquoise=#40E0D0
navy=#000080

if [ -r /PRODUCTION ]; then
   color=$blue
   P="YES"
else
   color=$teal
   P="no"
fi

echo "<td align=center><font color=\"$color\">$n</font></td>"
echo "<td align=center><font color=\"$color\">$P</font></td>"
echo "<td align=center><font color=\"$color\">$b</font></td>"
echo "<td align=center><font color=\"$color\">$f/$t</font></td>"
echo "<td align=center><font color=\"$color\">$tim</font></td>"
echo "<td align=center><font color=\"$color\">$up</font></td>"
echo "<td align=center><font color=\"$color\">$nu</font></td>"
echo "<td align=center><font color=\"$color\">$ldav</font></td>"
echo "<td align=center><font color=\"$color\">$r</font></td>"
echo "<td align=center><font color=\"$color\">$v</font></td>"
