#!/bin/sh
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
if [ "${1:-}" = "-a" ] ; then ALARM=1; shift; else ALARM=0; fi
if [ "${1:-}" = "-c" ] ; then CHKONLY=1;shift; else CHKONLY=0; fi
if [ "${1:-}" = "-q" ] ; then QUIET=1; shift; else QUIET=0; fi

BADCNT=25 

UNAME="/bin/uname"
CMP="/usr/bin/cmp"
ECHO="/bin/echo"
XNTPDC="/usr/sbin/xntpdc"
if [ ! -r $XNTPDC ]; then XNTPDC="/usr/sbin/ntpdc"; fi #only other choice.
NTPDATE="/usr/sbin/ntpdate"
XNTP="/etc/rc.d/init.d/xntpd restart"
HWCLOCK="/sbin/hwclock"
EGREP="/bin/egrep"
HEAD="/usr/bin/head"
TAIL="/usr/bin/tail"
if [ -r /usr/bin/cut ]; then 
  CUT="/usr/bin/cut"
elif [ -r /bin/cut ]; then
  CUT="/bin/cut"
else
  echo "Can not find cut"
  exit 1
fi
AWK="/bin/awk"
WC="/usr/bin/wc"
DATE="/bin/date"
CAT="/bin/cat"
SED="/bin/sed"
MKDIR="/bin/mkdir"

node=`$UNAME -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`/home/enstore/enstore/sbin/gang`

EKILL=/home/enstore/enstore/sbin/ekill


LOG=/tmp/ntpset.log
HIST=/root/CRON/ntpsetH
if [ ! -d `dirname $HIST` ]; then $MKDIR -p `dirname $HIST`;fi
TIME_SYNC_COUNTER=/tmp/time_sync_counter

# function to log messages, optionally print the ps state
logit() { $ECHO `$DATE` "$1" >>$LOG 2>&1
          if [ "${2:-}"x = "psx" ]; then
             $ECHO "${PSfirst:-}"  >>$LOG 2>&1
          fi
          $ECHO "$1"
        }
# if these processes are hanging around, kill them...
$EKILL -v -9 "$XNTPDC|$NTPDATE" >>$LOG 2>&1
$EKILL    -9 "$XNTPDC|$NTPDATE" >>$LOG 2>&1

# check that ntp is working, fix if not, complain if down more 6 times in a row (hour)
if [ ! -r $TIME_SYNC_COUNTER ]; then
  echo '0'>$TIME_SYNC_COUNTER
fi
COUNT=`cat $TIME_SYNC_COUNTER`
# don't set every time - give it time to settle down
RELAX=`expr $COUNT - $COUNT / 2 \* 2`

x=`$XNTPDC -p`
x1=`$ECHO "$x"|$EGREP '^\*|^~'`
if [ `$ECHO "$x1"|$WC|$AWK '{print $1}'` -lt 1 ]; then
    logit "NO TIME SYNC"
    logit "$x"
    COUNT=`expr $COUNT + 1`
    if [ $ALARM -eq 1 ]; then
      if [ $COUNT -gt $BADCNT ]; then
        enstore alarm --raise --severity "A" --root-error "NO TIME SYNC $x"
      fi
    fi
    if [ $CHKONLY -eq 0 ]; then
      # if within 5 seconds of syncing, don't reset time - let it settle
      disp=`$ECHO "$x"|$EGREP '^='|$HEAD -n2|$TAIL -n1|$AWK '{print $NF}'|$CUT -f1 -d.`
      if [ $disp -lt 5 ];then RELAX=1; fi

      if [ $RELAX -eq 0 ]; then
        $XNTP stop >>$LOG 2>&1
	COUNT='0' # clear the counter
        # set the time, but use more than just fermilab to sync it
        $NTPDATE -b -p 8 -u -v `$CAT /etc/ntp/step-tickers` ntp-1.cso.uiuc.edu ntp-1.mcs.anl.gov ntp.cmr.gov >>$LOG 2>&1
        # start up ntp again - this just syncs to fermilab, according to policy.
        $XNTP start >>$LOG 2>&1
      else
        logit "Clock not in sync, waiting till next time to set. disp=$disp"
      fi
    fi
    $ECHO `$DATE +"%Y-%m-%d:%H:%M:%S"` 1 >>$HIST
else
  $HWCLOCK --systohc
  hw=`$HWCLOCK --show`
  COUNT='0'
  if [ $QUIET -ne 1 ]; then
    logit  "TIME SYNCD, sync= $x1     hwclock = $hw, ok"
  fi
  $ECHO `$DATE +"%Y-%m-%d:%H:%M:%S"` 0 >>$HIST
fi
rm -f $TIME_SYNC_COUNTER
$ECHO $COUNT > $TIME_SYNC_COUNTER

