#!/bin/bash

. /usr/local/etc/setups.sh
setup remedy_soap

if [ $? -ne 0 ];
then
    echo "Failed to setup remedy_soap " >&2
    exit 1
fi

export PYTHONPATH=$SETUPS_DIR:$PYTHONPATH

$ENSTORE_DIR/src/operation.py $*

exit 0
