#!/bin/sh 
set -u  
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
# figure out which test to do
testToDo=""
if [ "${1:-q}" != "q" ] ; then testToDo=${1}; shift; fi

# if we are on stken, then we could be testing one many dcaches
dcacheToTest=""
if [ "${1:-q}" != "q" ] ; then dcacheToTest=${1}; fi

# bin/$RCSfile$  $Revision$

get_ticket() {
# Use Eileen's enrsh method to get a ticket
    krbdir="/usr/krb5/bin"
    defaultDomain=".fnal.gov"
    host=`uname -n`
    if expr $host : '.*\.' >/dev/null;then
	thisHost=$host;
    else
	thisHost=${host}${defaultDomain};
    fi
    KRB5CCNAME=/tmp/krb5cc_enstore_$$
    export KRB5CCNAME
    ${krbdir}/kinit -k -t /local/ups/kt/enstorekt enstore/cd/${thisHost}
# ${krbdir}/klist -fea
}

rm_tmp_files() {
    rm -f $output_dccp
    rm -f $exit_code_dccp
    rm -f $output_kftp
    rm -f $exit_code_kftp
    rm -f $output_kftpCert
    rm -f $exit_code_kftpCert
    rm -f $output_ftp
    rm -f $exit_code_ftp
    rm -f $output_gridftp
    rm -f $exit_code_gridftp
    rm -f ${output_gridftp}_3
    rm -f ${exit_code_gridftp}_3
    rm -f ${output_gridftp}_1
    rm -f ${exit_code_gridftp}_1
    rm -f $output_srm
    rm -f $exit_code_srm
}

echo_output() {
    if [ -e $1 ];
    then
	echo "=================== output from $1 ======================="
	cat $1
    fi
}

check_exit_code() {
    if [ $ec = 0 -a -e $1 ];
    then
	ec=`cat $1`
    fi
}

get_ports() {
    # get the ftp/kftp ports
    tmp_file=/tmp/dCacheSetup
    enrcp $dcache:~enstore/dcache-deploy/config/dCacheSetup $tmp_file
    set +u;. $tmp_file;set -u
    rm $tmp_file
    strong_port=$kerberosFtpPort
    weak_port=$ftpPort
    cert_port=2811
    srm_port=$srmPort1
}

# assume success exit code
ec=0

# N will have a leading 0 (if < 100) unless we pipe it to sed.
N=`date +"%j"|sed -e 's%^0%%'` #day of year
N1=`expr $N - 1`

test_file=/tmp/dcache_page_file_$$
rm -f $test_file
cp /var/log/messages $test_file
if [ $? != 0 ]; then echo `date` ERROR: can not cp /var/log/messages; exit 2; fi

for tp in dccp kftp kftpCert ftp gridftp srm;
do
  eval output_${tp}=/tmp/dcache_page_output_${tp}${dcacheToTest}_$$
  eval exit_code_${tp}=/tmp/dcache_page_exit_code_${tp}${dcacheToTest}_$$
done
rm_tmp_files

# do the tests. spawn off the dccp test.  however the ftp test depends on the kftp
# test finishing and writing a file to dcache.  so let them go in series.
gang=`gang`
case $gang in
  stken) case $dcacheToTest in
##JonOFF##      cms) strip_dir="/pnfs/eagle"
##JonOFF##           w=$strip_dir/dcache-tests/$N.dcache_page_cms_$$
##JonOFF##	   wp=$strip_dir/dcache-tests/$N.dcache_page_p_cms_$$
##JonOFF##	   wa=$strip_dir/dcache-tests/$N.dcache_page_a_cms_$$
##JonOFF##	   wpc=$strip_dir/dcache-tests/$N.dcache_page_pc_cms_$$
##JonOFF##	   wac=$strip_dir/dcache-tests/$N.dcache_page_ac_cms_$$
##JonOFF##	   wg=dcache-tests/$N.dcache_page_g_$$
##JonOFF##	   ws=/pnfs/fnal.gov/usr/eagle/dcache-tests/$N.dcache_page_s_$$
##JonOFF##	   dcache=cmsdca
##JonOFF##	   dcache_saag="dcache_cms"
##JonOFF##	   get_ports
##JonOFF##	   get_ticket
##JonOFF##	   case $testToDo in
##JonOFF##		dccp) `pageDcache_tests $- dccp $test_file $dcache $dcache_saag $w "" "" > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
##JonOFF##		      ;;
##JonOFF##		gridftp) `pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
##JonOFF##		         ;;
##JonOFF##		srm) `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws $srm_port > $output_srm 2>&1; echo $? > $exit_code_srm`&
##JonOFF##		     ;;
##JonOFF##		kftp) pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa kerb > $output_kftp 2>&1; echo $? > $exit_code_kftp
##JonOFF##		      # now test kftp with certificates
##JonOFF##		      pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $cert_port $wpc $wac cert > $output_kftpCert 2>&1; echo $? > $exit_code_kftpCert
##JonOFF##		      pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
##JonOFF##		      ;;
##JonOFF##	   esac
##JonOFF##	   ;;
	      cms|cmstest) strip_dir="/pnfs/cms"
	           w=$strip_dir/WAX/5/pageDcache/$N.dcache_page_cmstest_$$
		   wp=$strip_dir/WAX/5/pageDcache/$N.dcache_page_p_cmstest_$$
		   wa=$strip_dir/WAX/5/pageDcache/$N.dcache_page_a_cmstest_$$
		   wg=WAX/5/pageDcache/$N.dcache_page_g_$$
		   ws=/pageDcache/$N.dcache_page_s_$$
		   dcache=cmsdca
		   dcache_saag="dcache_cmstest"
		   get_ports
		   get_ticket
		   case $testToDo in
			dccp) `pageDcache_tests $- dccp $test_file $dcache $dcache_saag "unsecured" $w "" "" > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
			      ;;
			gridftp) dcache=cmsdcdr3 
				# there appears to no longer be a gridftp door on this node
				#dcache_saag_g=${dcache_saag}_3
				#wg_g=${wg}_3
				#`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag_g $wg_g > ${output_gridftp}_3 2>&1; echo $? > ${exit_code_gridftp}_3`&
				dcache=cmsdcdr1
				dcache_saag_g=${dcache_saag}_1
				wg_g=${wg}_1
				`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag_g $wg_g > ${output_gridftp}_1 2>&1; echo $? > ${exit_code_gridftp}_1`&
			         ;;
			srm) `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws $srm_port > $output_srm 2>&1; echo $? > $exit_code_srm`&
			     ;;
		   esac
		   ;;
	     lqcd) strip_dir="/pnfs/eagle"
	           w=$strip_dir/dcache-tests/$N.dcache_page_lqcd_$$
		   wp=$strip_dir/dcache-tests/$N.dcache_page_p_lqcd_$$
		   wa=$strip_dir/dcache-tests/$N.dcache_page_a_lqcd_$$
		   wpc=$strip_dir/dcache-tests/$N.dcache_page_pc_lqcd_$$
		   wac=$strip_dir/dcache-tests/$N.dcache_page_ac_lqcd_$$
		   ws=/pnfs/fnal.gov/usr/eagle/dcache-tests/$N.dcache_page_s_$$
		   dcache=lqcd-cache
		   dcache_saag="dcache_lqcd"
		   get_ports
		   get_ticket
		   case $testToDo in
			dccp) `pageDcache_tests $- dccp $test_file $dcache $dcache_saag "" $w "" "" > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
			      ;;
			gridftp) `pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
			         ;;
			srm) `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws $srm_port > $output_srm 2>&1; echo $? > $exit_code_srm`&
			     ;;
			kftp) pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa kerb > $output_kftp 2>&1; echo $? > $exit_code_kftp
			      # now test kftp with certificates
			      pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $cert_port $wpc $wac cert > $output_kftpCert 2>&1; echo $? > $exit_code_kftpCert
			      pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
			      ;;
		   esac
		   ;;
	  fndca|*) strip_dir="/pnfs/eagle"
	           w=$strip_dir/dcache-tests/$N.dcache_page_$$
		   wp=$strip_dir/dcache-tests/$N.dcache_page_p_$$
		   wa=$strip_dir/dcache-tests/$N.dcache_page_a_$$
		   wpc=$strip_dir/dcache-tests/$N.dcache_page_pc_$$
		   wac=$strip_dir/dcache-tests/$N.dcache_page_ac_$$
		   ws=/pnfs/fnal.gov/usr/eagle/dcache-tests/$N.dcache_page_s_$$
		   wg=dcache-tests/$N.dcache_page_g_$$
		   dcache=fndca1
		   dcache_saag="dcache_stk"
		   get_ports
		   get_ticket
		   case $testToDo in
			dccp) `pageDcache_tests $- dccp $test_file $dcache $dcache_saag "unsecured" $w "" "" > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
			      ;;
			gridftp) `pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
			         ;;
			srm) `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws $srm_port > $output_srm 2>&1; echo $? > $exit_code_srm`&
			     ;;
			kftp) pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa kerb > $output_kftp 2>&1; echo $? > $exit_code_kftp
			      # now test kftp with certificates
			      pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $cert_port $wpc $wac cert > $output_kftpCert 2>&1; echo $? > $exit_code_kftpCert
			      pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
			      ;;
		   esac
		   ;;
	 esac
	 ;;
  cdfen) case $dcacheToTest in
	    cdfen|*) strip_dir="/pnfs/cdfen"
	             door_list="/pnfs/cdfen/.(config)(dCache)(dcache.conf)"
	             w=$strip_dir/jon/fcdfsgi2/$N.dcache_page_$$
		     wd=/pnfs/fnal.gov/usr/cdfen/jon/fcdfsgi2/$N.dcache_page_$$
		     wp=$strip_dir/jon/fcdfsgi2/$N.dcache_page_p_$$
		     wa=$strip_dir/jon/fcdfsgi2/$N.dcache_page_a_$$
		     wpc=$strip_dir/jon/fcdfsgi2/$N.dcache_page_pc_$$
		     wac=$strip_dir/jon/fcdfsgi2/$N.dcache_page_ac_$$
		     wg=jon/fcdfsgi2/$N.dcache_page_g_$$
		     ws=/pnfs/fnal.gov/usr/cdfen/jon/fcdfsgi2/$N.dcache_page_s_$$
		     dcache=cdfdca
		     dcache_saag="dcache_cdf"
		     get_ports
		     get_ticket
		     case $testToDo in
			dccp) `pageDcache_tests $- dccp $test_file $dcache $dcache_saag "" $w $door_list $wd > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
			      ;;
			gridftp|gridftp1) 
                                  dcache=cdfdca-ftp1;`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
			      ;;
			gridftp2) dcache=cdfdca-ftp2;`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
			         ;;
			gridftp3) dcache=cdfdca-ftp3;`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
			         ;;
			srm) dcache=cdfdca-srm11; `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws $srm_port > $output_srm 2>&1; echo $? > $exit_code_srm`&
			     ;;
			kftp) dcache=cdfdca-ftp1; pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa kerb > $output_kftp 2>&1; echo $? > $exit_code_kftp
			      # now test kftp with certificates
			      pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $cert_port $wpc $wac cert > $output_kftpCert 2>&1; echo $? > $exit_code_kftpCert
			      pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
			      ;;
		     esac
		     ;;
	 esac
	 ;;
  d0en)  case $dcacheToTest in
	    d0en|*) strip_dir="/pnfs"
	            w=$strip_dir/archive/dcache-tests/$N.dcache_page_$$
		    wp=$strip_dir/archive/dcache-tests/$N.dcache_page_p_$$
		    wa=$strip_dir/archive/dcache-tests/$N.dcache_page_a_$$
		    wpc=$strip_dir/archive/dcache-tests/$N.dcache_page_pc_$$
		    wac=$strip_dir/archive/dcache-tests/$N.dcache_page_ac_$$
		    wg=archive/dcache-tests/$N.dcache_page_g_$$
		    ws=/pnfs/fnal.gov/usr/archive/dcache-tests/$N.dcache_page_s_$$
		    dcache=d0dca
		    dcache_saag="dcache_d0"
		    get_ports
		    get_ticket
		    case $testToDo in
			dccp) `pageDcache_tests $- dccp $test_file $dcache $dcache_saag "" $w "" "" > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
			      ;;
			gridftp) `pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
			         ;;
			srm) `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws $srm_port > $output_srm 2>&1; echo $? > $exit_code_srm`&
			     ;;
			kftp) pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa kerb > $output_kftp 2>&1; echo $? > $exit_code_kftp
			      # now test kftp with certificates
			      pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $cert_port $wpc $wac cert > $output_kftpCert 2>&1; echo $? > $exit_code_kftpCert
			      pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp	
			      ;;
		    esac
		    ;;
	 esac
         ;;
     *) namespace="UNKNOWN"
        echo `date` UNKNOWN gang
	exit 1
        ;;
esac

# we have spawned off all tests we could to run in parallel,
# wait for all of our children to completed.
# jobs -p returns a space separated list of pids
wait `jobs -p`

# all the children have finished, echo anything they said, 
#                                 check the exit codes
#                                 remove any tmp files
echo_output $output_dccp
check_exit_code $exit_code_dccp
echo_output $output_kftp
check_exit_code $exit_code_kftp
echo_output $output_kftpCert
check_exit_code $exit_code_kftpCert
echo_output $output_ftp
check_exit_code $exit_code_ftp
echo_output $output_gridftp
check_exit_code $exit_code_gridftp
echo_output ${output_gridftp}_1
check_exit_code ${exit_code_gridftp}_1
echo_output ${output_gridftp}_3
check_exit_code ${exit_code_gridftp}_3
echo_output $output_srm
check_exit_code $exit_code_srm

rm_tmp_files

# we are done, do any cleanup
rm -f $test_file

case $gang in
    cdfen)
	   # make sure the ball is ok
	   enstore sched --nooverride $dcache_saag
	   ;;
esac
		     
echo `date` Finished.
exit $ec
