#!/bin/sh 
set -u  
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
# if we are on stken, then we could be testing one of the following dcaches -
# fndca, lqcd, cms
dcacheToTest=""
if [ "${1:-q}" != "q" ] ; then dcacheToTest=${1}; fi

# bin/$RCSfile$  $Revision$

get_ticket() {
# Use Eileen's enrsh method to get a ticket
    krbdir="/usr/krb5/bin"
    defaultDomain=".fnal.gov"
    host=`uname -n`
    if expr $host : '.*\.' >/dev/null;then
	thisHost=$host;
    else
	thisHost=${host}${defaultDomain};
    fi
    KRB5CCNAME=/tmp/krb5cc_enstore_$$
    export KRB5CCNAME
    ${krbdir}/kinit -k -t /local/ups/kt/enstorekt enstore/cd/${thisHost}
# ${krbdir}/klist -fea
}

rm_tmp_files() {
    rm -f $output_dccp
    rm -f exit_code_dccp
    rm -f $output_kftp
    rm -f exit_code_kftp
    rm -f $output_ftp
    rm -f $exit_code_ftp
}

echo_output() {
    echo "=================== output from $1 ======================="
    if [ -e $1 ];
    then
	cat $1
    fi
}

check_exit_code() {
    if [ $ec = 0 -a -e $1 ];
    then
	ec=`cat $1`
    fi
}

# assume success exit code
ec=0

# N will have a leading 0 (if < 100) unless we pipe it to sed.
N=`date +"%j"|sed -e 's%^0%%'` #day of year
N1=`expr $N - 1`

# get the ftp/kftp ports
tmp_file=/tmp/dCacheSetup
enrcp $dcache:~enstore/dcache-deploy/config/dCacheSetup $tmp_file
set +u;. $tmp_file;set -u
rm $tmp_file
strong_port=$kerberosFtpPort
weak_port=$ftpPort

test_file=/tmp/dcache_page_file_$$
rm -f $test_file
cp /var/log/messages $test_file
if [ $? != 0 ]; then echo `date` ERROR: can not cp /var/log/messages; exit 2; fi

output_dccp=/tmp/dcache_page_output_dccp_$$
exit_code_dccp=/tmp/dcache_page_exit_code_dccp_$$
output_kftp=/tmp/dcache_page_output_kftp_$$
exit_code_kftp=/tmp/dcache_page_exit_code_kftp_$$
output_ftp=/tmp/dcache_page_output_ftp_$$
exit_code_ftp=/tmp/dcache_page_exit_code_ftp_$$
rm_tmp_files

gang=`gang`
case $gang in
  stken) case $dcacheToTest in
	      cms) w=/pnfs/eagle/dcache-tests/$N.dcache_page_$$
		   wp=/pnfs/eagle/dcache-tests/$N.dcache_page_p_$$
		   wa=/pnfs/eagle/dcache-tests/$N.dcache_page_a_$$
		   strip_dir="/pnfs/eagle"
		   dcache=cmsdca
		   dcache_saag="dcache_cms"
		   get_ticket
		   `page_dcache_tests dccp $test_file $dcache $dcache_saag $w > $output_dccp; echo $? > $exit_code_dccp`&
		   `page_dcache_tests kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp; echo $? > $exit_code_kftp`&
		   `page_dcache_tests ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp; echo $? > $exit_code_ftp`&
		   ;;
	     lqcd) w=/pnfs/eagle/dcache-tests/$N.dcache_page_$$
		   wp=/pnfs/eagle/dcache-tests/$N.dcache_page_p_$$
		   wa=/pnfs/eagle/dcache-tests/$N.dcache_page_a_$$
		   strip_dir="/pnfs/eagle"
		   dcache=lqcd-cache
		   dcache_saag="dcache_lqcd"
		   get_ticket
		   `page_dcache_tests dccp $test_file $dcache $dcache_saag $w > $output_dccp; echo $? > $exit_code_dccp`&
		   `page_dcache_tests kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp; echo $? > $exit_code_kftp`&
		   `page_dcache_tests ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp; echo $? > $exit_code_ftp`&
		   ;;
	    fndca) 
	        *) w=/pnfs/eagle/dcache-tests/$N.dcache_page_$$
		   wp=/pnfs/eagle/dcache-tests/$N.dcache_page_p_$$
		   wa=/pnfs/eagle/dcache-tests/$N.dcache_page_a_$$
		   strip_dir="/pnfs/eagle"
		   dcache=fndca
		   dcache_saag="dcache_stk"
		   get_ticket
		   `page_dcache_tests dccp $test_file $dcache $dcache_saag $w > $output_dccp; echo $? > $exit_code_dccp`&
		   `page_dcache_tests kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp; echo $? > $exit_code_kftp`&
		   `page_dcache_tests ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp; echo $? > $exit_code_ftp`&
		   ;;
	 esac
	 ;;
  cdfen) case $dcacheToTest in
	      cdfen)
	          *) w=/pnfs/cdfen/jon/fcdfsgi2/$N.dcache_page_$$
		     wp=/pnfs/cdfen/jon/fcdfsgi2/$N.dcache_page_p_$$
		     wa=/pnfs/cdfen/jon/fcdfsgi2/$N.dcache_page_a_$$
		     strip_dir="/pnfs/cdfen"
		     dcache=cdfdca
		     dcache_saag="dcache_cdf"
		     get_ticket
		     `page_dcache_tests dccp $test_file $dcache $dcache_saag $w > $output_dccp; echo $? > $exit_code_dccp`&
		     `page_dcache_tests kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp; echo $? > $exit_code_kftp`&
		     `page_dcache_tests ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp; echo $? > $exit_code_ftp`&
		     ;;
	 esac
	 ;;
  d0en)  case $dcacheToTest in
	      d0en)
		 *) w=/pnfs/archive/dcache-tests/$N.dcache_page_$$
		    wp=/pnfs/archive/dcache-tests/$N.dcache_page_p_$$
		    wa=/pnfs/archive/dcache-tests/$N.dcache_page_a_$$
		    strip_dir="/pnfs"
		    dcache=d0dca
		    dcache_saag="dcache_d0"
		    get_ticket
		    `page_dcache_tests dccp $test_file $dcache $dcache_saag $w > $output_dccp; echo $? > $exit_code_dccp`&
		    `page_dcache_tests kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp; echo $? > $exit_code_kftp`&
		    `page_dcache_tests ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp; echo $? > $exit_code_ftp`&
		    ;;
	 esac
         ;;
     *) namespace="UNKNOWN"
        echo `date` UNKNOWN gang
	exit 1
        ;;
esac

# we have spawned off all tests to run in parallel,
# wait for all of our children to completed.
# jobs -p returns a list of pids that are space separated
wait `jobs -p`

# all the children have finished, echo anything they said.
echo_output $output_dccp
echo_output $output_kftp
echo_output $output_ftp

# and check their exit codes
check_exit_code $exit_code_dccp
check_exit_code $exit_code_kftp
check_exit_code $exit_code_ftp

# we are done, do any cleanup
rm_tmp_files

case $gang in
    cdfen)
	   # make sure the ball is ok
	   enstore sched --nooverride $dcache_saag
	   ;;
esac
		     
echo `date` Finished.
exit $ec
