#!/bin/sh -xv

# $Id$

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`
case $gang in
  stken) mountpoint="/pnfs/cms"
	  ndb="5"
	  lssizecmd="cmspnfs /diska/pnfs/db"
	  outputpage="/fnal/ups/prd/www_pages/enstore/CMSpnfsRate.html"
	  errorpage="/fnal/ups/prd/www_pages/enstore/CMSpnfsRate.errors"
          
	  python $ENSTORE_DIR/sbin/pnfsRate.py --mountpoint $mountpoint --database $ndb --sleeptime=5  --genhtml --all --lssizecmd="$lssizecmd" > $outputpage 2> $errorpage

	  mountpoint="/pnfs/eagle"
	  ndb="45"
	  lssizecmd="stkensrv1 /diska/pnfs/db"
	  outputpage="/fnal/ups/prd/www_pages/enstore/pnfsRate.html"
	  errorpage="/fnal/ups/prd/www_pages/enstore/pnfsRate.errors"
	  ;;
   d0en) mountpoint="/pnfs/sam/dzero"
          ndb=16
	  lssizecmd="d0ensrv1 /diska/pnfs/db"
	  outputpage="/fnal/ups/prd/www_pages/enstore/pnfsRate.html"
	  errorpage="/fnal/ups/prd/www_pages/enstore/pnfsRate.errors"
          ;;
  cdfen) mountpoint="/pnfs/cdfen"
          ndb=12 
	  lssizecmd="cdfensrv1 /diska/pnfs/db"
	  outputpage="/fnal/ups/prd/www_pages/enstore/pnfsRate.html"
	  errorpage="/fnal/ups/prd/www_pages/enstore/pnfsRate.errors"
          ;;
       *) echo BUSTED
          exit 1
          ;;
esac

python $ENSTORE_DIR/sbin/pnfsRate.py --mountpoint $mountpoint --database $ndb --sleeptime=5  --genhtml --all --lssizecmd="$lssizecmd" > $outputpage 2> $errorpage

