#!/bin/sh

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`

f=/tmp/pnfsExports.html

python $ENSTORE_DIR/sbin/pnfsExports.py --all >$f 2>$f.errors

enrcp $f ${gang}srv2:/fnal/ups/prd/www_pages/enstore/


