#!/bin/sh
#
# -q  Enables ignoring of warnings from files under standard library.
# -k
# -b  Enables ignoring of warnings from the list of modules [Tkinter, etc.].
# -l  (el not one)  Enables warning of all unused local variables,
#      excluding tuples.
# -L <value>  Specifies maximum lines in a function.
# -B <value>  Specifies maximum branches in a function.
# -R <value>  Specifies maximum returns in a function.
# -J <value>  Specifies maximum # of arguments to a function.
# -K <value>  Specifies maximum # of locals in a function.
options="-q -k -b -l -L 100000 -B 100000 -R 100000 -J 25 -K 60"

#Important note:  The checker.py function must be called
#                 with its full path in order for it to work.
#           See checker.py setupNamespace definition
#
python $ENSTORE_DIR/tools/pychecker/checker.py $options $@
