#!/bin/sh

###############################################################################
#
# $Id$
#
###############################################################################

# chkconfig: 345 96 04
# description: qpid_broker is wrapper script to start/stop qpidd broker for enstore
#
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n`

# only resetup everything if not currently set up
if [ "${ENSTORE_DIR:-}" = "" -o "${QPID_DIR:-}" = "" ];
then
   . /usr/local/etc/setups.sh
   setup enstore
fi

EXE=$QPID_DIR/sbin/qpidd
RUN_DIR=/var/run/qpidd
LOG_DIR=/var/log/qpidd

mkdir -p $RUN_DIR
mkdir -p $LOG_DIR

command=${1:-status}

# startup options are set in qpidd.conf
# use "qpidd --help" to see file location

case $command in

stop)
	CMD="$EXE -q"
	echo $CMD
	$CMD
	;;
start)
	CMD="$EXE -d"
        echo $CMD
        $CMD
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	PID_FILE_ASCII=/tmp/qpidd.5672.ascii.pid
        rm -f ${PID_FILE_ASCII}
	$EXE -c 1>${PID_FILE_ASCII} 2>/dev/null 
	RC=$?
	case "$RC" in 
          0)
            echo "qpidd (pid `cat ${PID_FILE_ASCII}`) is running...";
            exit 0
          ;;
          1)
            echo "qpidd stopped";
            exit 1
          ;;
        esac;
	;;
*)
	echo "Error: Invalid option $command"
	echo "USAGE: $0 [stop|start|restart|status]"
	exit 1
	;;
esac
