#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# information specific to Fermilab
node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
case $node in
  stken*) gang=stken
          ;;
   d0en*) gang=d0en
          ;;
       *) gang=UNKNOWN
          ;;
esac
thisNode=${gang}srv2
rdistNode=${gang}srv3.fnal.gov
filePath='/diska'

# bin/$RCSfile$  $Revision$

# script to backup enstore log files to the backup node

#function to list command, execute it and list status
doit() { echo "$1"
         eval "nice -n 20 $1"
         status=$?
	 echo "Status= $status"
	 if [ $status -ne 0 ]; then exit $status; fi
         echo "" 
       }

if [ `uname -n | grep -c ${thisNode}` -ne 0 ]; then

 cmd="/usr/bin/rsync   -l -p -o -g -D -t -x --delete --force ${filePath}/enstore-log/LOG-* enstore@${rdistNode}:${filePath}/enstore-log-backup"
 doit "$cmd"

else
  echo "Do not know about node `uname -n`... fix $ENSTORE/sbin/rdist-log script"
  exit 1
fi

exit 0
