#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# information specific to Fermilab
gang=`gang`
thisNode=${gang}srv2
rdistNode=${gang}srv3.fnal.gov
filePath='/diska'
ENSTORE=/home/enstore/enstore

# bin/$RCSfile$  $Revision$

# script to backup enstore log files to the backup node

# function to list command, execute it and list status
doit() { echo "$1"
	 eval "nice -n 10 $1"
	 status=$?
	 echo "Status= $status"
	 if [ $status -ne 0 ]; then exit $status; fi
	 echo
       }

if uname -n | grep ${thisNode} > /dev/null; then

# cron is scheduled every 15 minutes, so time out after 10

 cmd="/usr/bin/rsync -e $ENSTORE/sbin/enrsh -rlpgtx --delete --timeout=600 --blocking-io \
      ${filePath}/enstore-log/LOG-* enstore@${rdistNode}:${filePath}/enstore-log-backup"
 doit "$cmd"

else
  echo "Do not know about node `uname -n`... fix $ENSTORE/sbin/rdist-log script"
  exit 1
fi

exit 0
