#!/bin/bash 
#############################################################
#
#  $Id$
#
#############################################################
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
vol=$1; shift
out="${1:-/dev/null}"
echo out $out
enstore fil --list $vol | grep active | awk '{print $6}'|while read i;do encp $i $out;echo $i;done
