#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# list the cvs logs for updates from the working file (on your disk) to
# the one in the repository

cvs -n -q update  | egrep -v '^\?' | while read flag file; do
  status=`cvs status $file`
  echo "$status"
  rev=`echo "$status"| awk '/Working revision:/ {print $3}'`
  major=`echo $rev |cut -f1 -d.`
  minor=`echo $rev |cut -f2 -d.`
  next=`expr $minor + 1`
  cvs log -N -r$major.$next: $file
  echo
done

