#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi


file=$1

  rev1=`cvs status -v $file 2>/dev/null|grep 'v2_17_encp' | head -n 1| sed -e "s/.*revision://" -e 's/)//'`
  if [ -z $rev1 ]; then exit 1;fi
  rev1=`echo $rev1`
  major1=`echo $rev1 |cut -f1 -d.`
  minor1=`echo $rev1 |cut -f2 -d.`
  next1=`expr $minor1 + 1`
  rev2=`cvs status -v $file 2>/dev/null|grep 'v2_18_encp' | tail -n 1| sed -e "s/.*revision://" -e 's/)//'`
  rev2=`echo $rev2`
  major2=`echo $rev2 |cut -f1 -d.`
  minor2=`echo $rev2 |cut -f2 -d.`
  prev2=`expr $minor2 - 1`

  if [ "$rev1" = "$rev2" ];then exit;fi
  echo
  /bin/echo -n "========== $file ===================================================================================="
  changes=`cvs log -N -r$major1.$next1:$major2.$minor2 $file|egrep -v '^revision |^date:|^RCS file:|^Working file:|^head:|^branch:|^locks:|^access list:|^keyword substitution:|^total revisions:|^selected revisions:|^description:'`
  echo $changes|sed -e 's/---------------------------- /\
\
/g'| sed -e 's/=============================================================================//'
