#!/bin/sh

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`

farmlet=/usr/local/etc/farmlets/$gang-alla
filebase=/tmp/sdr-

output=${1:-/dev/tty}
if [ `echo $output | grep -c /dev/` -eq 0 ] ; then 
  rm -f $output
fi

cat << EOF >>$output
<html> <head> <title>$gang Cluster SDR Status Page</title> </head>
<body>
<meta http-equiv="Refresh" content="900">
<body bgcolor="#ffffff" text=#a0a0ff">
<h1><center>$gang Cluster SDR Fetch Begin: `date`</center><h1>
<hr>
EOF

if [ -z "${2-}" ] ; then
  for i in `cat $farmlet`; do
   date > $filebase$i
   enrsh $i '. /fnal/ups/etc/setups.sh;setup ipmi; $IPMI_DIR/sdrread  | egrep "^sdr [0-9][0-9]?:"' >> $filebase$i &
  done
  #wait
  sleep 30 # wait doesn't work if rsh fails ???
fi

cat << EOF >>$output
<h1><center>$gang Cluster SDR Fetch Done : `date`</center><h1>
<hr>
EOF

cat << EOF >>$output
<table bgcolor="#dfdff0" nosave >
<tr><td align=center><b>Item</b></td>
EOF

for i in `cat $farmlet`; do
  cat <<EOF >>$output
<td align=center><b>$i</b></td>
EOF
done
  cat << EOF >>$output
</tr>
EOF

getval() { grep "$1" $2 | cut -d: -f3 | cut -f2 -d\ ; }
getdes() { grep "$1" $2 | cut -d: -f2 ; }

alarm_sent=0
for des in \
        "Baseboard Temp 1" \
        "Baseboard Temp 2" \
        "Processor 1 Temp" \
        "Processor 2 Temp" \
        "Processor 1 Fan" \
        "Processor 2 Fan" \
        "Baseboard -12V" \
        "Baseboard 1.5V" \
        "Baseboard 2.5V" \
        "Baseboard 3.3V" \
        "Baseboard 5V" \
        "Baseboard 12V" \
        "Processor 1 Volt" \
        "Processor 2 Volt" ; do
  cat <<EOF >>$output
<tr><td align=center>$des</td>
EOF
  for i in `cat $farmlet`; do
    val="`getval "$des" $filebase$i`"
    if [ "$val" = "" ]; then
	# try the values for the new ipmi
	if [ "$des" = "Baseboard Temp 1" ]; then
	    val="`getval 'Baseboard Temp' $filebase$i`"
	elif [ "$des" = "Baseboard Temp 2" ]; then
	    val="`getval 'Baseboard Temp' $filebase$i`"
        elif [ "$des" = "Processor 1 Fan" ]; then
	    val="`getval 'Processor Fan 1' $filebase$i`"
	elif [ "$des" = "Processor 2 Fan" ]; then
	    val="`getval 'Processor Fan 2' $filebase$i`"
	elif [ "$des" = "Processor 1 Volt" ]; then
	    val="`getval 'Processor 1 VCCP' $filebase$i`"
	elif [ "$des" = "Processor 2 Volt" ]; then
	    val="`getval 'Processor 2 VCCP' $filebase$i`"
	elif [ "$des" = "Baseboard 5V" ]; then
	    val="`getval 'Baseboard 5.0V' $filebase$i`"
	fi
	if [ "$val" = "" ]; then
	    data_item="<td align=center bgcolor=\"RED\">&nbsp;</td>"
#      remove the following comments if an alarm should be sent.
#      if [ "$alarm_sent" = "0" ]; then
#        `enstore alarm --raise --root-error="DOESNOTEXIST - $des, $i (check all values)"`
#	alarm_sent=1
#      fi
	else
	    data_item="<td align=center>$val</td>"
	fi
    else
	data_item="<td align=center>$val</td>"
    fi
    cat <<EOF >>$output
$data_item
EOF
  done
  cat << EOF >>$output
</tr>
EOF
done

cat << EOF >>$output
</table>
<hr>
EOF

######################################################################################Q
cat <<EOF >>$output
<h1><center>$gang Cluster SDR Write Done : `date`</center><h1>
<hr>
</body>
EOF

