#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

case $node in
  stken*) gang=stken
          ;;
   d0en*) gang=d0en
          ;;
       *) echo "Unknown node $node, please modify $0"
          exit 1
          ;;
esac

rgang $gang "echo 'DATE \`date\`'>>/SEL; /usr/local/bin/selread>>/SEL; /usr/local/bin/selclear"

rgang $gang "echo 'DATE \`date\`'>>/BITERROR; /opt/biterror/biterror_reset>>/BITERROR"
