#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`

date

OLDIFS="$IFS"
IFS="${IFS},"


if [ $gang = "stken" ]; then

# tapes in Public silo are acs 0 & lsm 0.
echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in the stken silo (acs 0, lsm 0) that are not fully declared to enstore"
egrep -v "^$|^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |grep "         0, 0,"| while read tape place acs lsm panel drive type; do
  x=`grep $tape /diska/tape-inventory/VOLUMES_DEFINED|grep -iv deleted|wc|awk '{print $1}'`
  if [ $x -eq  0 ]; then
      echo Tape $tape is in public silo, but not defined to enstore: $tape $place $acs $lsm $panel $drive $type
  fi
done

#tapes in mezzanine  silo are acs 1 & lsm 0
if [ "`whoami`" != "enstore" ]; then
  # root copies file if we are enstore (kerberos protections)
 /home/enstore/enstore/sbin/enrcp d0ensrv2:/diska/tape-inventory/VOLUMES_DEFINED /tmp/d0-VOLUMES_DEFINED
fi
echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in the d0 mezsilo (acs 1, lsm 0) that are not fully declared to enstore"
egrep -v "^$|^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |grep "         1, 0,"| while read tape place acs lsm panel drive type; do
  x=`grep $tape /tmp/d0-VOLUMES_DEFINED |grep -iv deleted|wc|awk '{print $1}'`
  if [ $x -eq  0 ]; then
      echo Tape $tape is in Mezzanine silo, but not defined to enstore: $tape $place $acs $lsm $panel $drive $type
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes not in any category"
egrep -v "^$|^<|CLN|in transit" /diska/tape-inventory/STK-VOLUMES.html  |egrep -v "         1, 0,|         0, 0,|         1, 1"

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in Enstore, but not in silo"
egrep -v "^$|^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  if [ `echo $lib | egrep -ic 'null|disk'` -ne 0 ]; then continue; fi
  if [ `echo $line | grep -c transit` -ne 0 ]; then continue; fi
  if [ `echo $vol | grep -c ^IA` -ne 0 ]; then continue; fi
  n=`grep $vol /diska/tape-inventory/STK-VOLUMES.html /tmp/d0-VOLUMES_DEFINED| wc | awk '{print $1}'`
  if [ $n -eq 0 ]; then
    echo 'Not in any silo' $line
  elif [ $n -gt 1 ]; then
    echo 'In more than 1 silo' $line
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in NOACCESS or NOT_ALLOWED state"
egrep 'NOACCESS|NOTALLOWED' /diska/tape-inventory/VOLUMES_DEFINED | egrep -v 'migrated' | egrep -v ^IA

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in invalid library"
egrep -v "^$|^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  vf=`echo $line|awk '{print $NF}'`
  sg=`echo $vf | cut -f1 -d.`
  if [ $sg = 'test' ]; then continue;fi
  if [ $lib = '9940' -o $lib = '9940B' -o $lib = 'eagle' -o $lib = 'cdf' -o $lib = 'CMS-9940B' -o $lib = 'test' ];then continue; fi
  if [ $lib = 'blank-d0-9940' -o $lib = 'blank-9940' -o $lib = 'blank-9840' ];then continue; fi
  if [ `echo $lib | egrep -ic 'null|disk|shelf'` -ne 0 ]; then continue; fi
  if [ `echo $lib | egrep -ic '9940b'` -ne 0 ]; then 
      if [ `echo $lib | egrep -ic 'cdf|d0|blank|public'` -ne 0 ]; then continue; fi
  fi
  echo $line
done
echo
echo "--------------------------------------------------------------------------------------------------------------------"


elif [ $gang = "cdfen" ]; then

# tapes in cdf silo are acs 0 & lsm 0&1.
echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in the cdfen silo (acs 0, lsm 0) that are not fully declared to enstore"
egrep -v "^$|^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |grep "         0, 0,"| while read tape place acs lsm panel drive type; do
  x=`grep $tape /diska/tape-inventory/VOLUMES_DEFINED|grep -iv deleted|wc|awk '{print $1}'`
  if [ $x -eq  0 ]; then
      echo Tape $tape is in cdf silo, but not defined to enstore: $tape $place $acs $lsm $panel $drive $type
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes not in any category"
egrep -v "^$|^<|CLN|in transit" /diska/tape-inventory/STK-VOLUMES.html  |egrep -v "         0, 0|         0, 1,"

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in Enstore, but not in silo"
egrep -v "^$|^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  if [ `echo $lib | egrep -ic 'null|disk'` -ne 0 ]; then continue; fi
  if [ `echo $lib | egrep -ic '9940b'` -ne 0 ]; then 
      if [ `echo $lib | egrep -ic 'cdf|d0|blank|public'` -ne 0 ]; then continue; fi
  fi
  if [ `echo $line | grep -c transit` -ne 0 ]; then continue; fi
  if [ `echo $vol | grep -c ^IA` -ne 0 ]; then continue; fi
  n=`grep $vol /diska/tape-inventory/STK-VOLUMES.html| wc | awk '{print $1}'`
  if [ $n -eq 0 ]; then
    echo 'Not in any silo' $line
  elif [ $n -gt 1 ]; then
    echo 'In more than 1 silo' $line
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in NO_ACCESS or NOT_ALLOWED state"
egrep 'NOACCESS|NOTALLOWED' /diska/tape-inventory/VOLUMES_DEFINED | egrep -v 'migrated'

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in invalid library"
egrep -v "^$|^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  vf=`echo $line|awk '{print $NF}'`
  sg=`echo $vf | cut -f1 -d.`
  if [ $sg = 'test' ]; then continue;fi
  if [ $lib = 'cdf' -o $lib = 'CDF-9940B' -o $lib = 'test'  -o $lib = 'CDF-Migration' -o $lib = 'A-Loan' -o $lib = 'CD-9940B' ];then continue; fi
  if [ `echo $lib | egrep -ic 'null|disk|shelf'` -ne 0 ]; then continue; fi
  echo $line
done
echo
echo "--------------------------------------------------------------------------------------------------------------------"


elif [ $gang = "d0en" ]; then

# tapes in quadrotowers, but not in enstore.
echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes that are not fully declared to enstore"
egrep -v "^<|next volser|Empty$" /diska/tape-inventory/AML2-VOLUMES.html | egrep -v 'volser 0[0-9][0-9][0-9][0-9][0-9] media 8MM attrib Occupied'| while read dum1 tape dum2 media dum3 attrib; do
  x=`grep $tape /diska/tape-inventory/VOLUMES_DEFINED|grep -iv deleted|wc|awk '{print $1}'`
  if [ $x -eq  0 ]; then
      echo Tape $tape is in tower, but not defined to enstore: $tape $media  $attrib
  fi
done

echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in Enstore, but not in the towers"
egrep -v "^$|^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  if [ `echo $lib | egrep -ic 'null|disk|shelf'` -ne 0 ]; then continue; fi
  if [ `echo $lib | egrep -ic 'D0-9940B'` -ne 0 ]; then 
      if [ `echo $lib | egrep -ic 'cdf|d0|blank|public'` -ne 0 ]; then continue; fi
  fi
  if [ `echo $lib | grep -ic mezsilo` -ne 0 ]; then continue; fi
  n=`grep $vol /diska/tape-inventory/AML2-VOLUMES.html | wc | awk '{print $1}'`
  if [ $n -eq 0 ]; then
    echo 'Not in tower' $line
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in NOACCESS or NOT_ALLOWED state"
egrep 'NOACCESS|NOTALLOWED' /diska/tape-inventory/VOLUMES_DEFINED | egrep -v "migrated" | egrep -v ^IA

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in invalid library"
egrep -v "^$|^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  vf=`echo $line|awk '{print $NF}'`
  sg=`echo $vf | cut -f1 -d.`
  if [ $sg = 'test' ]; then continue;fi
  if [ $lib = 'sammam' -o $lib = 'samm2' -o $lib = 'samlto' -o $lib = 'mezsilo' -o $lib = 'D0-9940B' ];then continue; fi
  if [ $lib = 'test' -o $lib = 'testm2' -o $lib = 'testlto' ];then continue; fi
  if [ $lib = 'blank-d0-9940' -o $lib = 'blank-9940' -o $lib = 'blank-9840' ];then continue; fi
  if [ `echo $lib | egrep -ic 'null|disk|shelf'` -ne 0 ]; then continue; fi
  echo $line
done
echo
echo "--------------------------------------------------------------------------------------------------------------------"

fi

IFS="$OLDIFS"
date
