#!/bin/sh
set -u
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`

date

OLDIFS="$IFS"
IFS="${IFS},"


if [ $gang = "stken" ]; then

# tapes in Public silo are acs 0 & lsm 0.
echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in the stken silo (acs 0, lsm 0) that are not fully declared to enstore"
egrep -v "^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |grep "         0, 0,"| while read tape place acs lsm panel drive type; do
  x=`grep $tape /diska/tape-inventory/VOLUMES_DEFINED|grep -iv deleted|wc|awk '{print $1}'`
  if [ $x -eq  0 ]; then 
      echo Tape $tape is in public silo, but not defined to enstore: $tape $place $acs $lsm $panel $drive $type 
  fi
done

#tapes in mezzanine  silo are acs 1 & lsm 0
if [ `id` -ne enstore ]; then 
  # root copies file if we are enstore (kerberos protections)
 /home/enstore/enstore/sbin/enrcp d0ensrv2:/diska/tape-inventory/VOLUMES_DEFINED /tmp/d0-VOLUMES_DEFINED
fi
echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in the d0 mezsilo (acs 1, lsm 0) that are not fully declared to enstore"
egrep -v "^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |grep "         1, 0,"| while read tape place acs lsm panel drive type; do
  x=`grep $tape /tmp/d0-VOLUMES_DEFINED |grep -iv deleted|wc|awk '{print $1}'`
  if [ $x -eq  0 ]; then 
      echo Tape $tape is in Mezzanine silo, but not defined to enstore: $tape $place $acs $lsm $panel $drive $type 
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes not in any category"
egrep -v "^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |egrep -v "         1, 0,|         0, 0,"

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in Enstore, but not in silo"
egrep -v "^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  if [ `echo $lib | grep -ic null` -ne 0 ]; then continue; fi
  if [ `echo $line | grep -c transit` -ne 0 ]; then continue; fi
  if [ `echo $vol | grep -c ^IA` -ne 0 ]; then continue; fi
  n=`grep $vol /diska/tape-inventory/STK-VOLUMES.html /tmp/d0-VOLUMES_DEFINED| wc | awk '{print $1}'`
  if [ $n -eq 0 ]; then
    echo 'Not in any silo' $line
  elif [ $n -gt 1 ]; then
    echo 'In more than 1 silo' $line
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in NO_ACCESS or NOT_ALLOWED state"
egrep 'NOACCESS|NOTALLOWED' /diska/tape-inventory/STK-VOLUMES.html | egrep -v ^IA

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes not in 9940, eagle library"
egrep -v "^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  if [ $lib = '9940' -o $lib = 'eagle' -o $lib = 'cdf' -o $lib = 'test' ];then continue; fi
  if [ $lib = 'blank-d0-9940' -o $lib = 'blank-9940' -o $lib = 'blank-9840' ];then continue; fi
  if [ `echo $lib | grep -ic null` -ne 0 ]; then continue; fi
  echo $line
done
echo
echo "--------------------------------------------------------------------------------------------------------------------"


elif [ $gang = "cdfen" ]; then

# tapes in cdf silo are acs 0 & lsm 0.
echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in the cdfen silo (acs 0, lsm 0) that are not fully declared to enstore"
egrep -v "^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |grep "         0, 0,"| while read tape place acs lsm panel drive type; do
  x=`grep $tape /diska/tape-inventory/VOLUMES_DEFINED|grep -iv deleted|wc|awk '{print $1}'`
  if [ $x -eq  0 ]; then 
      echo Tape $tape is in cdf silo, but not defined to enstore: $tape $place $acs $lsm $panel $drive $type 
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes not in any category"
egrep -v "^<|CLN" /diska/tape-inventory/STK-VOLUMES.html  |egrep -v "         0, 0,"

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in Enstore, but not in silo"
egrep -v "^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  if [ `echo $lib | grep -ic null` -ne 0 ]; then continue; fi
  if [ `echo $line | grep -c transit` -ne 0 ]; then continue; fi
  if [ `echo $vol | grep -c ^IA` -ne 0 ]; then continue; fi
  n=`grep $vol /diska/tape-inventory/STK-VOLUMES.html| wc | awk '{print $1}'`
  if [ $n -eq 0 ]; then
    echo 'Not in any silo' $line
  elif [ $n -gt 1 ]; then
    echo 'In more than 1 silo' $line
  fi
done

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes in NO_ACCESS or NOT_ALLOWED state"
egrep 'NOACCESS|NOTALLOWED' /diska/tape-inventory/STK-VOLUMES.html | egrep -v ^IA

echo
echo "--------------------------------------------------------------------------------------------------------------------"
echo "Tapes not in cdf library"
egrep -v "^<|CLN|^Date|^label" /diska/tape-inventory/VOLUMES_DEFINED| while read line; do
  vol=`echo $line| awk '{print $1}'`
  lib=`echo $line| sed -e 's/.*)//'|awk '{print $1}'`
  if [ $lib = 'cdf' -o $lib = 'test' ];then continue; fi
  if [ `echo $lib | grep -ic null` -ne 0 ]; then continue; fi
  echo $line
done
echo
echo "--------------------------------------------------------------------------------------------------------------------"

fi

IFS="$OLDIFS"
date
