#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`
case $gang in
  stken) robot="StreamLine 8500"
         place=stkensrv4
	 silo_node=fntt-gcc
          ;;
  cdfen) robot="StreamLine 8500"
         place=cdfensrv4
	 silo_node=fntt-gcc
          ;;
   d0en*) robot="UNKNOWN"
          ;;
       *) robot="UNKNOWN"
          ;;
esac


output=${1:-/dev/tty}
if [ `echo $output | grep -c /dev/` -eq 0 ] ; then 
  rm -f $output
fi

if [ $node = "stkensrv4" -o $node = "cdfensrv4" ] ; then

logfile=/tmp/SL8500log
rm -f $logfile
cat << EOF >>$output
<html> <head> <title>$robot Recent Log Messages</title> </head>
<body>
<!-- <body bgcolor="#ffffff" text=#a0a0ff"> -->
<meta http-equiv="Refresh" content="900">
<h1><center>$robot Log Message Fetch Begin: `date`</center><h1>
<hr>
<--<font size="-1"> -->
<pre>
EOF

/usr/bin/rsh $silo_node -l acsss 'tail -1000 log/acsss_event.log' | awk '/20[0-9][0-9]/ { printf("%s",$0) ; getline ;  getline; printf("\t%s\n",$0)}' >>$logfile
tac $logfile >>$output

cat << EOF >>$output
</pre>
</font>
<h1><center>$robot Log MEssage Fetch Done : `date`</center><h1>
<hr>
EOF

else
  f=SL8500-LOG.html
  rm /tmp/$f
  enrcp $place:$f /tmp/$f
  cat /tmp/$f >>$output
fi
