#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

# both parts of this script run as user enstore

node=`hostname -s`
gang=`gang`

# rails are StreamLine 8500 robots
rail_robot="StreamLine 8500"
case $gang in
  stken) rail_acs_list="0 1"
	 rail_node_0=fntt-gcc
	 rail_node_1=fntt2
	 ;;
      *) echo \"$0\" not supported on $gang
	 exit 1
	 ;;
esac

copy_node=${gang}srv4
plot_node=${gang}srv2

Quarter_ago=`date --date "91 days ago" +"%Y-%m-%d:%H:%M:%S"`

if [ $node = $copy_node ]; then

  output=${1:-/dev/tty}
  shift
  [ -f $output ] && rm -f $output

  volfile=/tmp/SL8500-VOLUMES-$gang
  rm -f $volfile

  filter="awk '\$8~/home|move|mount|dismount|in_drive/'"

  cat << EOF >>$output
<html> <head> <title>$rail_robot Volume Status Page</title> </head>
<body>
<body bgcolor="#ffffff" text=#a0a0ff">
<meta http-equiv="Refresh" content="900">
<h1><center>$rail_robot Volume Fetch Begin: `date`</center><h1>
<hr>
EOF

  for rail_acs in $rail_acs_list
  do
    eval rail_node="\$rail_node_$rail_acs"
    select="display volume \* -home $rail_acs,*,*,*,*"
    /usr/bin/rsh $rail_node -l acsss "echo $select '\r' logoff | bin/cmd_proc -l -q 2>/dev/null" >>$volfile
  done

  cat << EOF >>$output
<h1><center>$rail_robot Volume Fetch Done : `date`</center><h1>
<hr>
<h1>Tapes in the $rail_robot satisfying: "$filter"
<pre>
EOF

  eval $filter <$volfile >>$output

  cat << EOF >>$output
</pre>
<hr>
<h1><center>$rail_robot Volume Status Page Done : `date`</center><h1>
<hr>
</body>
EOF

  for rail_acs in $rail_acs_list
  do
    eval rail_node="\$rail_node_$rail_acs"
    now=`date +"%Y-%m-%d:%H:%M:%S"`
    /usr/bin/rsh $rail_node -l acsss "echo query lsm all '\r' logoff | bin/cmd_proc -l -q 2>/dev/null" | grep online | sed 's/, /,/' | while read rail state free junk; do
      if [ `expr $rail : "$rail_acs,"` -gt 0 ]; then
	used=`eval $filter <$volfile | awk -v Rail="$rail" 'NF==10 {if (sprintf("%s,%s",$2,$3)==Rail) k++}; END {print k}'`
	tot=`expr ${free:-0} + ${used:-0}`
	echo "$now $rail $tot ${used:-0} ${free:-0}" >>$HOME/SL8500_USED_SLOTS.$rail
      fi
    done
  done

  for remote_copy
  do
    if [ ! \( -c $output -o -c $remote_copy \) ] ; then
      enrcp $output $remote_copy
    fi
  done

elif [ $node = $plot_node ]; then

  pltcmd=/tmp/sl8500.us.gnu
  enrcp $copy_node:SL8500_USED_SLOTS* $HOME/
  now=`date +"%Y-%m-%d:%H:%M:%S"`
  for i in $HOME/SL8500_USED_SLOTS*; do
    rail=`basename $i | cut -f2 -d.`
    rm -f $pltcmd
    free=`tail -n1 $i | awk '{print $5}'`
    echo "set output \"/tmp/rail.$rail.ps\"
set terminal postscript color solid
set title \"Used Slots in StreamLine 8500 rail $rail $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number Used\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
set label \"Plotted `date` \" at graph .99,0 rotate font \"Helvetica,10\"
set label \"$free Free\" at graph .2,.9 font \"Helvetica,80\"
plot \"$i\" using 1:3 w impulses linetype 2, \"$i\" using 1:4 t \"Used Slots\" w impulses linetype 1" >$pltcmd
    gnuplot $pltcmd
    convert -flatten -background lightgray -rotate 90 /tmp/rail.$rail.ps /tmp/rail.$rail.jpg
    convert -flatten -background lightgray -geometry 120x120 -modulate 80 /tmp/rail.$rail.jpg /tmp/rail.${rail}_stamp.jpg
  done
  cp /tmp/rail*.ps /tmp/rail*.jpg /fnal/ups/prd/www_pages/enstore/

else
  echo \"$0\" runs only on $copy_node or $plot_node
  exit 1

fi
