#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`
case $gang in
  stken) robot="PowderHorn 9310"
	 copy_node=stkensrv4
	 silo_node=fntt
	  ;;
  cdfen) robot="PowderHorn 9310"
	 copy_node=cdfensrv4
	 silo_node=fntt2
	  ;;
      *) robot="UNKNOWN"
	  ;;
esac

busy=/home/enstore/STK_DRIVE_UTILIZATION
busy_d0=/home/enstore/STK_DRIVE_UTILIZATION_D0
busy_cdf=/home/enstore/STK_DRIVE_UTILIZATION

command=${1:-plot}
getnode=stkensrv4
getnode_cdf=cdfensrv4
plotnode=stkensrv2
plotnode_d0=d0ensrv2
plotnode_cdf=cdfensrv2

now=`date +"%Y-%m-%d:%H:%M:%S"`
Quarter_ago=`date --date "90 days ago" +"%Y-%m-%d:%H:%M:%S"`

case $command in

    get)
	if [ $node = $getnode ] ; then
	 dinfo=/tmp/dinfo
	 rm -f $dinfo
	 /usr/bin/rsh $silo_node -l acsss "echo query drive all|/export/home/ACSSS/bin/cmd_proc 2>> /tmp/garb" </dev/null >$dinfo
	 n9840=`grep " 9840" $dinfo | grep -c "in use"`
	 a9840=`grep " 9840" $dinfo | grep -c "online"`
	 n9940a=`grep "T9940A" $dinfo | grep "   0, 0," | grep -c "in use"`
	 a9940a=`grep "T9940A" $dinfo | grep "   0, 0," | grep -c "online"`
	 n9940b=`grep "T9940B" $dinfo | grep "   0, 0," | grep -c "in use"`
	 a9940b=`grep "T9940B" $dinfo | grep "   0, 0," | grep -c "online"`
	 echo "$now $n9840 $a9840 $n9940a $a9940a $n9940b $a9940b" >>$busy
	 n9940a=`grep "T9940A" $dinfo | grep "   1, 0," | grep -c "in use"`
	 a9940a=`grep "T9940A" $dinfo | grep "   1, 0," | grep -c "online"`
	 n9940b=`grep "T9940B" $dinfo | grep "   1, 0," | grep -c "in use"`
	 a9940b=`grep "T9940B" $dinfo | grep "   1, 0," | grep -c "online"`
	 echo "$now $n9940a $a9940a $n9940b $a9940b" >>$busy_d0

	elif [ $node = $getnode_cdf ] ; then
	 dinfo=/tmp/dinfo
	 rm -f $dinfo
	 /usr/bin/rsh $silo_node -l acsss "echo query drive all|/export/home/ACSSS/bin/cmd_proc 2>> /tmp/garb" </dev/null >$dinfo
	 n9940a=`grep "T9940A" $dinfo | grep "   0, [01]," | grep -c "in use"`
	 a9940a=`grep "T9940A" $dinfo | grep "   0, [01]," | grep -c "online"`
	 n9940b=`grep "T9940B" $dinfo | grep "   0, [01]," | grep -c "in use"`
	 a9940b=`grep "T9940B" $dinfo | grep "   0, [01]," | grep -c "online"`
	 echo "$now 0 0 $n9940a $a9940a $n9940b $a9940b" >>$busy_cdf

	else
	 echo \"$0 $command\" can only be run on $getnode or $getnode_cdf
	 echo because they are the only ones that can talk to fntt or fntt2
	fi
	;;


    plot)
	if [ $node = $plotnode ] ; then
	 enrcp $getnode:$busy $busy
	 plot9840=/fnal/ups/prd/www_pages/enstore/9840_Utilization
	 plot9940a=/fnal/ups/prd/www_pages/enstore/T9940A_Utilization
	 plot9940b=/fnal/ups/prd/www_pages/enstore/T9940B_Utilization
	 pltcmd=/tmp/stkdu.gnu

	 rm -f $pltcmd
	 echo "set output \"$plot9840.ps\"
set terminal postscript color solid
set title \"STK 9840 Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in Use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:2 t \"9840 in use\" w impulses" >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9840.ps $plot9840.jpg
	 convert -geometry 120x120 -modulate 80 $plot9840.jpg ${plot9840}_stamp.jpg

	 rm -f $pltcmd
	 echo "set output \"$plot9940a.ps\"
set terminal postscript color solid
set title \"STK T9940A Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:4 t \"T9940A in use\" w impulses" >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940a.ps $plot9940a.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940a.jpg ${plot9940a}_stamp.jpg

	 rm -f $pltcmd
	 echo "set output \"$plot9940b.ps\"
set terminal postscript color solid
set title \"STK T9940B Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:(valid(6)?\$6:1/0) t \"T9940B in use\" w impulses" >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940b.ps $plot9940b.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940b.jpg ${plot9940b}_stamp.jpg


	elif [ $node = $plotnode_d0 ] ; then
	 enrcp $getnode:$busy_d0 $busy_d0
	 plot9940a=/fnal/ups/prd/www_pages/enstore/T9940A_Utilization
	 plot9940b=/fnal/ups/prd/www_pages/enstore/T9940B_Utilization
	 pltcmd=/tmp/stkdu.gnu

	 rm -f $pltcmd
	 echo "set output \"$plot9940a.ps\"
set terminal postscript color solid
set title \"STK T9940A Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy_d0\" using 1:2 t \"T9940A in use\" w impulses" >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940a.ps $plot9940a.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940a.jpg ${plot9940a}_stamp.jpg

	 rm -f $pltcmd
	 echo "set output \"$plot9940b.ps\"
set terminal postscript color solid
set title \"STK T9940B Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy_d0\" using 1:(valid(4)?\$4:1/0) t \"T9940B in use\" w impulses" >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940b.ps $plot9940b.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940b.jpg ${plot9940b}_stamp.jpg


	elif [ $node = $plotnode_cdf ] ; then
	 enrcp $getnode_cdf:$busy_cdf $busy_cdf
	 plot9940a=/fnal/ups/prd/www_pages/enstore/T9940A_Utilization
	 plot9940b=/fnal/ups/prd/www_pages/enstore/T9940B_Utilization
	 pltcmd=/tmp/stkdu.gnu

	 rm -f $pltcmd
	 echo "set output \"$plot9940a.ps\"
set terminal postscript color solid
set title \"STK T9940A Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy_cdf\" using 1:4 t \"T9940A in use\" w impulses" >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940a.ps $plot9940a.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940a.jpg ${plot9940a}_stamp.jpg

	 rm -f $pltcmd
	 echo "set output \"$plot9940b.ps\"
set terminal postscript color solid
set title \"STK T9940B Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy_cdf\" using 1:(valid(6)?\$6:1/0) t \"T9940B in use\" w impulses" >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940b.ps $plot9940b.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940b.jpg ${plot9940b}_stamp.jpg

	 # dimitri wants dots instead of lines...
	 plot9940a=/fnal/ups/prd/www_pages/enstore/T9940A_Utilization_dl
	 plot9940b=/fnal/ups/prd/www_pages/enstore/T9940B_Utilization_dl

	 rm -f $pltcmd
	 echo "set output \"$plot9940a.ps\"
set terminal postscript color solid
set title \"STK T9940A DL Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy_cdf\" using 1:4 t \"T9940A DL in use\" " >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940a.ps $plot9940a.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940a.jpg ${plot9940a}_stamp.jpg

	 rm -f $pltcmd
	 echo "set output \"$plot9940b.ps\"
set terminal postscript color solid
set title \"STK T9940B DL Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [\"$Quarter_ago\" : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy_cdf\" using 1:(valid(6)?\$6:1/0) t \"T9940B DL in use\" " >$pltcmd
	 gnuplot $pltcmd
	 convert -rotate 90 $plot9940b.ps $plot9940b.jpg
	 convert -geometry 120x120 -modulate 80 $plot9940b.jpg ${plot9940b}_stamp.jpg


	else
	 echo \"$0 $command\" can only be run on $plotnode, $plotnode_d0, or $plotnode_cdf
	 echo because they are the only ones that have a web server
	fi
	;;
esac
