#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

busy=/home/enstore/STK_DRIVE_UTILIZATION
busy_d0=/home/enstore/STK_DRIVE_UTILIZATION_D0

command=${1:-plot}
getnode=stkensrv4
plotnode=stkensrv2
plotnode_d0=d0ensrv2

now=`date +"%Y-%m-%d:%H:%M:%S"`

case $command in

    get)
        if [ $node = $getnode ] ; then
         dinfo=/tmp/dinfo
         rm -f $dinfo
         /usr/bin/rsh fntt -l acsss "echo query drive  all|/export/home/ACSSS/bin/cmd_proc 2>> /tmp/garb" </dev/null >$dinfo
         n9840=`grep " 9840"  $dinfo | grep -c "in use"`
         a9840=`grep " 9840"  $dinfo | grep -c "online"`
         n9940_stk=`grep "T9940"  $dinfo | grep "   0, 0," | grep -c "in use"`
         n9940_d0e=`grep "T9940"  $dinfo | grep "   1, 0," | grep -c "in use"`
         a9940_stk=`grep "T9940"  $dinfo | grep "   0, 0," | grep -c "online"`
         a9940_d0e=`grep "T9940"  $dinfo | grep "   1, 0," | grep -c "online"`
         echo "$now $n9840 $a9840 $n9940_stk $a9940_stk">>$busy
         echo "$now $n9940_d0e $a9940_d0e">>$busy_d0

        else
         echo \"$0 $command\" can only be run on $getnode because that is the only one that can talk to fntt
        fi
        ;;


    plot)
        if [ $node = $plotnode ] ; then
         enrcp $getnode:$busy $busy
         plot9840=/fnal/ups/prd/www_pages/enstore/9840_Utilization
         plot9940=/fnal/ups/prd/www_pages/enstore/9940_Utilization
         pltcmd=/tmp/stkdu.gnu

         rm -f $pltcmd
         echo "set output \"$plot9840.ps\"
set terminal postscript color solid
set title \"STK 9840 Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [ : ]
set ylabel \"Number in Use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:2 t \"9840 in use\" w impulses" >$pltcmd
         gnuplot $pltcmd
         convert -rotate 90 $plot9840.ps $plot9840.jpg
	 convert -geometry 120x120 -modulate -20 $plot9840.jpg ${plot9840}_stamp.jpg

         rm -f $pltcmd
         echo "set output \"$plot9940.ps\"
set terminal postscript color solid
set title \"STK 9940 Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [ : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy\" using 1:4 t \"9940 in use\" w impulses" >$pltcmd
         gnuplot $pltcmd
         convert -rotate 90 $plot9940.ps $plot9940.jpg
	 convert -geometry 120x120 -modulate -20 $plot9940.jpg ${plot9940}_stamp.jpg


        elif [ $node = $plotnode_d0 ] ; then
         enrcp $getnode:$busy_d0 $busy_d0
         plot9940=/fnal/ups/prd/www_pages/enstore/9940_Utilization
         pltcmd=/tmp/stkdu.gnu

         rm -f $pltcmd
         echo "set output \"$plot9940.ps\"
set terminal postscript color solid
set title \"STK 9940 Drive Utilization $now\"
set xlabel \"Date\"
set timefmt \"%Y-%m-%d:%H:%M:%S\"
set xdata time
set xrange [ : ]
set ylabel \"Number in use\"
set grid
set yrange [0: ]
set format x \"%m-%d\"
set nokey
plot \"$busy_d0\" using 1:2 t \"9940 in use\" w impulses" >$pltcmd
         gnuplot $pltcmd
         convert -rotate 90 $plot9940.ps $plot9940.jpg
	 convert -geometry 120x120 -modulate -20 $plot9940.jpg ${plot9940}_stamp.jpg


        else
         echo \"$0 $command\" can only be run on $plotnode or $plotnode_d0 because that is the only one that has a web server
        fi
        ;;
esac
