#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
gang=`gang`
case $gang in
  stken) robot="PowderHorn 9310"
	 silo_node=fntt
	 copy_node=stkensrv4
          ;;
  cdfen) robot="PowderHorn 9310"
	 silo_node=fntt2
	 copy_node=cdfensrv4
          ;;
   d0en*) robot="UNKNOWN"
          ;;
       *) robot="UNKNOWN"
          ;;
esac

volfile=/tmp/STKROBOT-VOLUMES-$gang

output=${1:-/dev/tty}
if [ `echo $output | grep -c /dev/` -eq 0 ] ; then 
  rm -f $output
fi

if [ $node = "stkensrv4" -o $node = "cdfensrv4" ] ; then

cat << EOF >>$output
<html> <head> <title>$robot Volume Status Page</title> </head>
<body>
<body bgcolor="#ffffff" text=#a0a0ff">
<meta http-equiv="Refresh" content="900">
<h1><center>$robot Volume Fetch Begin: `date`</center><h1>
<hr>
EOF

rm -f $volfile

/usr/bin/rsh $silo_node -l acsss "echo query vol all |/export/home/ACSSS/bin/cmd_proc 2>> /tmp/garbx" < /dev/null >>$volfile

cat << EOF >>$output
<h1><center>$robot Volume Fetch Done : `date`</center><h1>
<hr>
EOF

cmd="egrep '0,' $volfile"

cat << EOF >>$output
<h1> Tapes in the $robot satisfying: $cmd
<pre>
EOF

eval $cmd >>$output

cat << EOF >>$output
</pre>
<hr>
<h1><center>$robot Volume Status Page Done : `date`</center><h1>
<hr>
</body>
EOF

silos="`egrep ' STK' $volfile | cut -c30-36|sort | uniq`"
IFSave="$IFS"
IFS="
"
for silo in $silos; do 
  s=`echo $silo| sed -e 's/ //g' -e 's/,$//'`
  n="`egrep ' STK' $volfile | grep "$silo"|wc|awk '{print $1}'`"
  echo `date` $s $n >>/tmp/STK_USED_SLOTS."$s" 
done
IFS="$IFSave"


else
  f=STK-VOLUMES.html
  rm /tmp/$f
  enrcp $copy_node:$f /tmp/$f
  cat /tmp/$f >>$output
fi
