#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
case $node in
  stken*) gang=stken
          othergang=d0en
          basenode=stkenmvr5a
	  othernode=d0enmvr18a
          movers="1 2 3 4"
          servers="1 2 3 4"
          ;;
   d0en*) gang=d0en
	  othergang=stken
          basenode=d0enmvr18a
	  othernode=stkenmvr5a
          movers="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 19 20"
          servers="1 2 3 4 5"
          ;;
       *) gang=UNKNOWN
          ;;
esac

for i in $movers; do
  ./syncit -node ${gang}mvr${i}a
  enrsh ${gang}mvr${i}a "./syncit -node $basenode"
done

for i in $servers; do
  ./syncit -node ${gang}srv$i
   enrsh ${gang}srv${i} "./syncit -node $basenode"
done


./syncit -node $othernode
#enrsh $othernode "./syncit -node $basenode"

for i in $servers; do
   #enrsh ${othergang}srv${i} "./syncit -node ${gang}srv$i"
   enrsh ${gang}srv${i}  "./syncit -node ${othergang}srv$i"
done


if [ $node = "d0enmv18a" ]; then
  enrsh d0ensrv3 "./syncit -node d0ensrv5"
  enrsh d0ensrv5 "./syncit -node d0ensrv3"

elif [ $node = "stkenmvr5a" ]; then
  echo ""

fi

