#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
. /usr/local/etc/setups.sh
setup enstore
${ENSTORE_DIR}/sbin/check_drive.py $1 $2 $3
#restart mover
enstore restart --just $1 > /dev/null 2>&1
exit 0
