#! /bin/sh
#  This file (tracePrint) was created by Ron Rechenmacher <ron@fnal.gov> on
#  Mar 31, 1999. "TERMS AND CONDITIONS" governing this file are in the README
#  or COPYING file. If you do not have such a file, one can be obtained by
#  contacting Ron or Fermi Lab in Batavia IL, 60510, phone: 630-840-3000.
#  $RCSfile$
#  $Revision$
#  $Date$
if [ "$1" = '-x' ];then set -x; shift; fi
set -u

USAGE="\
   usage: `basename $0` [options] \"<name [name...]>\" on|of
examples: `basename $0` FLIBM on
          `basename $0` FLIBM of
          `basename $0` \"FLIBM FMOV\" off
    Note: 'of' is short for 'off' ('off' is also recognized)
 options: -?      print this \"usage\" information
          -h      print this \"usage\" information
          --help  print this \"usage\" information
          -v      verbose; prints trace commands executed
          -x      set -x (for debugging)
"

while opt=`expr "${1-}" : '-\(.*\)'`;do
    case $opt in
    \?|h|-help)  echo "$USAGE"; exit;;
    v)           opt_v=1;;
    esac
    shift
done

if [ $# != 2 ];then echo "$USAGE"; exit; fi

if   [ "$2" = 'of' -o "$2" = 'off' ];then cmd=traceOff
elif [ "$2" = 'on'                 ];then cmd=traceOn
else echo "invalid parameter '$2'"; echo "$USAGE"; exit; fi

mode=`traceInfo 0 | grep 'mode:' | sed -e 's/.*mode: //' -e 's/ .*//'`
if [ $cmd = traceOn -a $mode -lt 8 ];then
    if [ "${opt_v-}" ];then echo traceMode `expr $mode + 8`; fi
    traceMode `expr $mode + 8` >/dev/null
fi
for name in $1;do
    if [ "${opt_v-}" ];then echo $cmd -modes 8 $name 0 31; fi
    $cmd -modes 8 $name 0 31 >/dev/null
done
