#!/bin/sh
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi

output=${1:-/dev/tty}

node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`

case $node in
  stken*) gang=stken
          ;;
   d0en*) gang=d0en
          ;;
       *) gang=UNKNOWN
          ;;
esac

cat << EOF >$output
<html> <head> <title>$gang Cluster UDP Clogup Status Page</title> </head>
<body>
<body bgcolor="#ffffff" text=#a0a0ff">
<meta http-equiv="Refresh" content="900">
<h1><center>$gang Cluster UDP Clogup Fetch Begin: `date`</center><h1>
<hr>
<pre>
EOF

rgang -nn $gang "netstat -au | egrep -v  'Active Internet|Proto Recv'|grep -vw '0      0'; echo " >>$output 2>&1
echo "<hr>" >>$output
rgang      $gang "netstat -au | egrep -v  'Active Internet|Proto Recv'|egrep ':7[05][0-9][0-9]'" >>$output 2>&1

cat <<EOF >>$output
</pre>
<h1><center>$gang Cluster UDP Clogup Fetch Done : `date`</center><h1>
<hr>
</body>
EOF
