#! /bin/sh
#
# chkconfig: - 92 9
# description: chimera startup script
#
#  $Id$
#
if [ -r /etc/rc.d/init.d/functions ] ; then
    . /etc/rc.d/init.d/functions
fi

RETVAL=0
prog="chimera_wrapper"

POSTGRES_CHECK=/opt/enstore/tools/postgres_check

start() {
    echo -n $"$prog: checking postgresql:"
    $POSTGRES_CHECK
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success || failure
    echo
    [ $RETVAL -eq 0 ]
    if [ ! $RETVAL -eq 0 ]; then
	return $RETVAL
    fi
    /sbin/service chimera-nfs-run.sh start
    RETVAL=$?
    return $RETVAL
}

stop() {
    echo -n $"Shutting down $prog: "
    /sbin/service chimera-nfs-run.sh stop
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ]
    return $RETVAL
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
	*)
	/sbin/service chimera-nfs-run.sh $1
        RETVAL=$?
	;;
esac

exit $RETVAL
