#!/bin/sh
# $Id$
# this script mounts a volume in a drive in STK robot

set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi 
if [ "${1:-}" = "" ] ; then d=DRIVE;
else d=$1;shift;fi
if [ "${1:-}" = "" ] ; then v=VOLUME;
else v=$1;shift;fi

/usr/bin/rsh fntt -l acsss "echo dismount $v $d force '\r' logoff | bin/cmd_proc -l -q 2> /dev/null" < /dev/null;
