#! /bin/bash

#Create test files for encp_test_script.

if [ ! -d "$LOCAL_DIR" ]; then
    echo "\$LOCAL_DIR not set.  Stopping initialization."
    exit 1
fi

RD=/dev/urandom
O_DIR=/$LOCAL_DIR/test_files
SYNC_DIR=$O_DIR/ensync_test

mkdir -p $O_DIR

((
if [ ! -f $O_DIR/0B_001 ];  then
    touch $O_DIR/0B_001
    dd if=$RD bs=1 count=1 > $O_DIR/1B_001
fi

if [ ! -f $O_DIR/1KB_001 ];  then
    dd if=$RD bs=1024 count=1 | tee $O_DIR/1KB_001 > $O_DIR/1KB_002
    dd if=$RD bs=1 count=1 >> $O_DIR/1KB_002
fi

if [ ! -f $O_DIR/10KB_001 ];  then
    dd if=$RD bs=1024 count=10 | tee $O_DIR/10KB_001 > $O_DIR/10KB_002
    dd if=$RD bs=1 count=1 >> $O_DIR/10KB_002
fi

if [ ! -f $O_DIR/100KB_001 ];  then
    dd if=$RD bs=1024 count=100 | tee $O_DIR/100KB_001 > $O_DIR/100KB_002
    dd if=$RD bs=1 count=1 >> $O_DIR/100KB_002
fi

if [ ! -f $O_DIR/1MB_001 ];  then
    dd if=$RD bs=1048576 count=1 | tee $O_DIR/1MB_001 > $O_DIR/1MB_002
    dd if=$RD bs=1 count=1 >> $O_DIR/1MB_002
fi

if [ ! -f $O_DIR/10MB_001 ];  then
    dd if=$RD bs=1048576 count=10 | tee $O_DIR/10MB_001 > $O_DIR/10MB_002
    dd if=$RD bs=1 count=1 >> $O_DIR/10MB_002
fi

if [ ! -f $O_DIR/100MB_001 ];  then
    dd if=$RD bs=1048576 count=100 | tee $O_DIR/100MB_001 > $O_DIR/100MB_002
    dd if=$RD bs=1 count=1 >> $O_DIR/100MB_002
fi
) 2>&1 ) >> /dev/null


mkdir -p $SYNC_DIR/
mkdir -p $SYNC_DIR/dir_test

if [ ! -f $SYNC_DIR/1KB_003 ]; then
    cp $O_DIR/1KB_001 $SYNC_DIR/1KB_003
    cp $O_DIR/1KB_001 $SYNC_DIR/1KB_004
fi

if [ ! -L $SYNC_DIR/1KB_005 ]; then
    ln -s $SYNC_DIR/1KB_003 $SYNC_DIR/1KB_005
    ln -s $SYNC_DIR/1KB_004 $SYNC_DIR/1KB_006
fi

if [ ! -L $SYNC_DIR/1KB_007 ]; then
    ln -s $SYNC_DIR/1KB_999 $SYNC_DIR/1KB_007
    ln -s /blah/blah/1KB_999 $SYNC_DIR/1KB_008
fi

if [ ! -L $SYNC_DIR/1KB_008 ]; then
    ln -s /tmp $SYNC_DIR/1KB_009
fi
