#!/bin/sh
# $Id$
# take the drive from a file and query it
set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi 

# make an array of values
f=( $(cat /home/enstore/enstore/etc/d_l ) )
/home/enstore/enstore/tools/stk_drive q ${f[0]}

