#!/bin/sh
# $Id$
# this script queries a drive in STK robot

set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi 
if [ "${1:-}" = "" ] ; then d=all;
else d=$1;fi

/usr/bin/rsh fntt -l acsss "echo query drive   $d '\r' logoff | bin/cmd_proc -l -q 2> /dev/null" < /dev/null;
