#!/bin/sh
# $Id$
# this script allows basic STK robot operations from any node
# the corresponding scripts must be available on the server node

set -u  # force better programming and ability to use check for not set
if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi 
c=$0
node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
case $node in
  stken*) srv=stkensrv4
          ;;
  cdfen*) srv=cdfensrv4
          ;;
   d0en*) srv=d0ensrv4
        ;;
   *) srv=d0ensrv4
esac
cmd=$1;shift
case $cmd in
        query|q)
                ksu enstore -a -c ". /usr/local/etc/setups.sh;setup enstore; enrsh $srv /home/enstore/enstore/tools/qd ${1:-all} < /dev/null;"
                ;;
        mount|m)
               ksu enstore -a -c ". /usr/local/etc/setups.sh;setup enstore; enrsh $srv /home/enstore/enstore/tools/mount_v ${1:-VOLUME} ${2:-DRIVE} < /dev/null;"
               ;;
        dismount|d)
               ksu enstore -a -c ". /usr/local/etc/setups.sh;setup enstore; enrsh $srv /home/enstore/enstore/tools/dismount_v ${1:-DRIVE} ${2:-VOLUME} < /dev/null;"
               ;;
        *)
                echo "Usage:$c {(query|q drive_name)|(mount|m volume drive)|(dismount|d drive)}"
                ;;
esac

