universe = grid
GridResource = gt2 fermigridosg1.fnal.gov/jobmanager-condor
#type = gt2
#globusscheduler = fnpcosg1.fnal.gov/jobmanager-condor
Executable = /grid/app/moibenko/bin/read_test.sh 
Arguments = -b /grid/app/moibenko/bin/bfid_list -c 60 -w 10
transfer_output = true
transfer_error = true
transfer_executable = true
log = log/read_test.log.$(Cluster).$(Process)
notification = NEVER
output = log/read_test.out.$(Cluster).$(Process)
error = log/read_test.err.$(Cluster).$(Process)
stream_output = false
stream_error = false
Requirements = (OpSys == "LINUX")
#globusrsl = (jobtype=single)(maxwalltime=999)
queue 350

