universe = grid
GridResource = gt2 fermigridosg1.fnal.gov/jobmanager-condor
#type = gt2
#globusscheduler = fnpcosg1.fnal.gov/jobmanager-condor
Executable = /grid/app/moibenko/bin/write_test.sh 
Arguments = -p /pnfs/data1/test/moibenko/NULL/load_test/A -d /tmp/moibenko/data -g TST1 -f FAM1 -w 10 -n
transfer_output = true
transfer_error = true
transfer_executable = true
log = log/write_test.log.$(Cluster).$(Process)
notification = NEVER
output = log/write_test.out.$(Cluster).$(Process)
error = log/write_test.err.$(Cluster).$(Process)
stream_output = false
stream_error = false
Requirements = (OpSys == "LINUX")
#globusrsl = (jobtype=single)(maxwalltime=999)
queue 10

