#!/usr/bin/env python

# $Id$

#mover states
IDLE, MOUNT_WAIT, ACTIVE, HAVE_BOUND, DISMOUNT_WAIT, DRAINING, OFFLINE, CLEANING, ERROR = [
    'IDLE', 'MOUNT_WAIT', 'ACTIVE', 'HAVE_BOUND', 'DISMOUNT_WAIT',
    'DRAINING', 'OFFLINE', 'CLEANING', 'ERROR']

#mover modes
READ, WRITE, CLEANING = ['READ','WRITE','CLEANING']

